### PR TITLE
Long with Ponytail with Crowns

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Wearing crown doesn't cut ponytail on the Long with Ponytail hair.
- High elves may have the Long with Ponytail hair.

# How to test:
Try this hairstyle and some type of crown in the Ruler Designer.

### CODE REVIEW

**Review by ercarp — CHANGES_REQUESTED** [review]
Seems to work perfectly for most of the crowns, but I found that the ponytail clips through a few of them, so may want to consider disabling the haircut for the following if possible:

- **Imperial Crown** (`male_headgear_secular_dde_hre_imperial_01`)
- **Cone-shaped Hat** (`male_headgear_secular_steppe_nobility_01`)
- **Reichskrone** (`male_headgear_secular_western_imperial_01`)
- **Bishop's Mitre** (`male_headgear_religious_catholic_high_01`)
- **Archbishop's Mitre** (`male_headgear_religious_dde_catholic_high_01`)
- **Patriarch's Headgear** (`male_headgear_religious_orthodox_high_01`)

<details><summary>Click to expand</summary>

image
image
image
image
image
image

</details>

**Byzantine Circlet** (`male_headgear_secular_byzantine_high_nobility_01`) has the same issue, but it doesn't look as jarring to me. Depending on how much it bothers you, you may disable it here as well.

<details><summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> Seems to work perfectly for most of the crowns, but I found that the ponytail clips through a few of them, so we may want to consider disabling the haircut for the following if possible:

Fixed in 695b8dd6f8c8f6d69c139616ccc190160c891bfd.

> Byzantine Circlet (male_headgear_secular_byzantine_high_nobility_01) has the same issue, but it doesn't look as jarring to me. Depending on how much it bothers you, you may disable it here as well.

Nah, banned this too just in case.

**Review by ercarp — CHANGES_REQUESTED** [review]
**Byzantine Circlet** is still clipping. You said you would disable it as well, so I'm assuming it's not intended. Other than that, LGTM!

<details><summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> Byzantine Circlet is still clipping. You said you would disable it as well, so I'm assuming it's not intended. Other than that, LGTM!

Fixed in dd0af67e56ceee753602324647648ed740ddd5fb.

**Review by ercarp — APPROVED** [review]
In that case, LGTM!

**Pull request merged**
