### PR TITLE
Magic Spells *Fire Lifestyle*

### LINKED ISSUE #1315: Elemental Spells - Fire
Planning not started yet: Create elemental fire spells as documented [here](https://docs.google.com/spreadsheets/d/1cXFqsVwHekKiyrowB0PA5Ia4zvXuuxnBAoug8Iusrj8/edit#gid=44673228).

Must take into account Spirit and Decay mechanic if we are even going to add that into release

### LINKED ISSUE #1337: Spellcasting Mechanical Framework
@helloruhe please add a description : ]

### LINKED ISSUE #1363: 'Burned' wound icon traits + Decals
- [x] Create an icon for 'Burned' (Burned trait 1)
- [x] Create an icon for 'Scalded' (Burned Trait 2)
- [x] Create an icon for 'Scorched' (Burned trait 3)
- [x] Create Decals for traits (optional, i might do this myself at some point or we can leave them as the regular wounded ones.)

### PR DESCRIPTION
**Pull request by sumankun**
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/899
reattached
but if someone gonna work on that firestyle branch you need to update that branch to current magic2024
## Changelog:
- Added Elemental fire magic spells and rituals
- Created spellcasting GUI, associated events, and the ability to cast spells

## Developer changelog:
- Added this thing.
- Changed that thing.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)
- [x] Spell tooltips are correct.
- [ ] Spell effects work as intended
- [ ] Event effects / loc work as intended
- [ ] Minimal impact on game performance (if possible)

Issues from Testers assigned to @helloruhe & @robmart:
- [x] Spell casting complete loc weird
- [x] County/Development tooltip updates
- [x] Spells targeting multiple titles can be cast without a target (might be fixed with list clear update)
- [x] Fix backdraft rank 2/3 not working/showing
- [x] Make sure backdraft consumes correctly
- [x] Clear list when selecting a single target spell
- [x] Clear list when selecting a new spell or rank
- [x] ~~Spell rank GUI dropdown bugged **UNABLE TO CONSISTENTLY REPLICATE**~~ Resolved with GUI overhaul
- [x] Choose title button has a weird active area
- [x] Spell rank game concept not showing tooltip
- [x] Minor localization changes
- [x] Fix ritual CD times
- [x] ~~Restrict focus selection~~ Moved to magic-2024
- [x] Fix Spirit/Decay trait assignment 
- [x] Fix mana resource disappearing
- [x] Vernal Solstice
- [x] ~~Gender doctrine loc~~ Moved to magic-2024
- [x] Clean error log **once everything above is completed**

# How to test:
- You can use add_elemental_fire_magic_lifestyle_xp 18000 in the debug menu to unlock all 18 perks and all spells
- You can choose a target for your spell by opening the interaction menu on your target and clicking "Cast Spell"
- Try to cast each spell on different targets at different times if possible. 
- Ensure each spell follows the appropriate cooldown and cast time timer (indicated on GUI)
- Ensure all restrictions on casting spells work, and it's clear what is preventing you from casting a spell. (E.G. if you cast a spell on someone's province you shouldn't be able to do it again if they still have the effect on the province, and the GUI should tell you that in the tooltip)
- Inspect text for spelling/grammar mistake or error text
- Ensure the spell actually follows the intended effect as outlined in the tooltip

### CODE REVIEW

**Comment by Rimaka94** [comment]
From my playtesting 6/3/2024 (06678d1):

1. **English Localization:** "The spell Summon Fire Elemental has completed it's casting." should be "The spell Summon Fire Elemental has completed its casting." for alerting localization of spell cast completion. (contraction to possessive of "its")
image
2. **Localization:** Hovering over the numerical value of a county's Control in spellbook returns only 'COUNTY_CONTROL_TOOLTIP' (spellbook_widget.gui > COUNTY_CONTROL_TOOLTIP)
image
3. **Localization:** Hovering over _Spell Rank_ doesn't give a tooltip. (looks like it should)
image

**Comment by Rimaka94** [comment]
Further testing from the above:

1. **Effects:** Backdraft (Level 1) is always consuming itself after finishing casting.
image

2. **Effects:** Lava Lash and Backdraft (all spells that can target counties/baronies?) can be casted without a county/barony target. It will finish casting, but doesn't seem to have any effect.
image

3. **UI:** Is it intended for final spell of each tree to look like an enlarged version of all 3 button states? (maybe it's a placeholder?)
image

4. **Magic GUI:** Selecting the maximum number of baronies with Backdraft Rank 2 or maximum number of counties with Backdraft Rank 3, you are prevented from casting on any other baronies/counties with any spell with a single barony or county (rank 1 Backdraft, rank 1 Lava Lash) unless they are the same selection as the three counties/baronies that were scoped. This will last until you de-select the counties/baronies from a spell that allows deselecting of multiple scopes. If all spells that allow selecting multiple scopes are on cooldown, this means you are effectively locked out from casting any single-target spell unless you select the same scope/target, as that is the only selection allowed.

Because scopes are saved through each spell or spell rank change, this means you can cast a County-scope spell at a spell rank that only allows selection of Barony scopes, and vice versa. As an example, if I select 1-3 County scopes with Backdraft Rank 3, I can then select Backdraft Rank 2 and the County-level scopes will be saved for the Rank 2 spell.

5. **Effects:** Backdraft Rank 2 / 3 are not working. No effect is seemingly applied regardless of number of baronies/counties selected. It is not consuming itself (like the Rank 1 bug) and casting any further spells at both barony/county level for the respective spell rank is not consuming Backdraft.

**Comment by Rimaka94** [comment]
Further bugs found from playtest continuation above:

1. **Magic GUI:** For targets that require 'Choose Title' (Lava Lash Rank 1, Backdraft Rank 1), you have to click around the text to open the next popup. Clicking any part of the 'Choose Title' text does not do anything. Is it possible to put the button interaction above the text itself?
image

2. **Magic GUI:** After a certain amount of playtime, the 'Spell Rank' dropdown will eventually bug out for the rest of the session (until loading save / reloading game) and merge each selection with both _Rank X_ and _magic\_gui\_-_. I haven't figured out what the trigger is for this yet.
image

**Comment by Rimaka94** [comment]
error.log as of 06678d1, also points to the COUNTY_CONTROL_TOOLTIP issue from a few posts above:

```
[14:38:40][pdx_gui_localize.cpp:167]: Unlocalized text 'COUNTY_CONTROL_TOOLTIP' at gui/spellbook_widget.gui:302, either localize it or use the raw_text property instead of text
[14:38:40][pdx_data_factory.cpp:1417]: Could not find data system function 'GetDevelopmentLevelString' in 'Title.GetProvince.GetCounty.GetDevelopmentLevelString'.
[14:38:40][pdx_data_factory.cpp:1032]: Failed converting statement for 'Title.GetProvince.GetCounty.GetDevelopmentLevelString'
[14:38:40][pdx_gui_localize.cpp:249]: gui/spellbook_widget.gui:321 - Failed parsing localized text: [Title.GetProvince.GetCounty.GetDevelopmentLevelString]

[14:38:40][pdx_gui_factory.cpp:914]: gui/spellbook_widget.gui:321 - Failed converting property 'text'(143)

[14:38:40][pdx_gui_localize.cpp:167]: Unlocalized text 'COUNTY_DEVELOPMENT_TOOLTIP' at gui/spellbook_widget.gui:323, either localize it or use the raw_text property instead of text
```

**Comment by Rimaka94** [comment]
**Localization (English):** The event description for **wc_elemental_ritual_events.1605.desc** in English contains an unnecessary space at the start of the 2nd paragraph: " One suggestion is to use them to augment our forces here..."

image

**Comment by helloruhe** [comment]
> 3\. Spell

these have been fixed, with the exception of number 3 which is just a GUI bug. Will probably look into all GUI bugs in one sweep.

**Comment by helloruhe** [comment]
> Further bugs found from playtest continuation above:
> 
> 1. **Magic GUI:** For targets that require 'Choose Title' (Lava Lash Rank 1, Backdraft Rank 1), you have to click around the text to open the next popup. Clicking any part of the 'Choose Title' text does not do anything. Is it possible to put the button interaction above the text itself?
>    image
> 2. **Magic GUI:** After a certain amount of playtime, the 'Spell Rank' dropdown will eventually bug out for the rest of the session (until loading save / reloading game) and merge each selection with both _Rank X_ and _magic_gui_-_. I haven't figured out what the trigger is for this yet.
>    image

will do these issues as well when i do a full GUI sweep, might just need to make button bigger tbh, but the tooltip thing is weird. as for the dropdown bug, I will look into that as well.

**Comment by helloruhe** [comment]
FInal perk tree buttons are weird, they don't have icons yet. placeholders for now

**Comment by helloruhe** [comment]
Updated the PR to reflect your issues, feel free to add more if needed. I'll edit/check things off as I get to them. @Rimaka94

**Comment by Rimaka94** [comment]
- Missing localization for `secret_elemental_fire_magic_user_type_desc`
<details>
<summary></summary>

image
</details>

- Missing localization for every magic doctrine combination of magic + gender
  - `doctrine_parameter_light_magic_gender_dominant`
  - `doctrine_parameter_disorder_magic_gender_unspecified`
  - `doctrine_parameter_elemental_fire_magic_gender_clerical`
  - etc...
<details>
<summary></summary>

image
</details>

- Faith with Fire Magic at Controlled states that you cannot learn through Pyromancy/Pyrotheurgy Focuses, but this does not stop you from selecting those focuses nor does it hinder your experience. Regardless of selection, it still progresses the Pyrosophist lifestyle trait. Is this how it is intended?
- I have not been able to acquire the Pyromancy/Pyrotheurgy lifestyle traits. I have only been able to acquire/progress Pyrosophist lifestyle traits on characters with faiths that allow learning through Pyrosophism. (Masonic/Gogic as examples)
  - Playing as Kolkar Clan (Maraudic) Pyrotheurgy for example gains you no lifestyle traits.
<details>
<summary></summary>

image
</details>

- As a faith that is non-Pyrosophist (Maraudic/Fetishistic) I will occasionally lose the ability to cast magic (mana resource disappears). Selecting a new perk when enough lifestyle experience is gained returns it temporarily.
  - I experienced this the most as Kolkar Clan (Maraudic) Pyrotheurgy and constantly casting Fire Elemental/Flame Shock on myself/neighbors.

**Comment by helloruhe** [comment]
@robmart merge this whenever you are free but let me know, so i can rebase the light lifestyle to the magic 2024 branch

**Pull request merged**
