### PR TITLE
Health Goes Down With Age

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Once again, just like in the vanilla game, health goes down with age allowing characters to die of old age.

# Tasks:
- [x] Check health of new spawned characters

# How to test:
Run the game for a few decades, confirm humans die of old age like in the vanilla game around 70-50 years.

On the other hand, elves and other long-lived races shouldn't die of old age when they're just 150 years old.

### CODE REVIEW

**Comment by ValianBlue** [comment]
_**Test 1: 61 Years**_

_For the most part, things seem to be working correctly however I spotted a number of oddities._

_One dwarf managed to live to 558. I could not discern why._

<details>
<summary>Oldest Dwarves</summary>


</details>

<details>
<summary>Belimryn Deepstone (558)</summary>


</details>

_At least four humans were older than age 100. 18 were age 70 and older. I estimate ~150 were age 60 and older._

_One observation I made is that all of these humans are landed with Barony tier titles and are under the Republic government type._

<details>
<summary>Oldest Humans</summary>


</details>

<details>
<summary>Mayor Chris of Quint (542)</summary>


</details>

<details>
<summary>Mayor Saltain of Florida (485)</summary>

image
</details>

<details>
<summary>Mayor Eberulf of Steelwatch (174)</summary>

image
</details>

<details>
<summary>Mayor Hastings of Adalbero (162)</summary>

image
</details>

_The elf populations seem to be stable, although from what I've seen the majority of elves are younger than 100. I infer that this is because of lethal events triggering such as assassinations, duels, or other mishaps killing off these elves before they can reach a hundred years of age._

<details>
<summary>High Elf Threshold</summary>

image
</details>

<details>
<summary>Night Elf Threshold</summary>

image
)
</details>

<details>
<summary>Highborne Threshold</summary>

image
</details>

**Review by ercarp — COMMENTED** [review]
Observed an AI game for **70 years**.

<details><summary>Click to expand</summary>

image

</details>

### Findings

**I noticed that most humans were dying of old age around 60-70**, which is fairly standard for Vanilla CK3, but not as common in the Warcraft universe as far as I know. I think, in general, humans should live to be at least 75 on average. It's especially anti-climatic in the case of characters like Tirion Fordring who were quite old.

- Daelin Proudmoore **died of old age at 69.**
- Llane Wrynn **died of old age at 69.**
- Aiden Perenolde **died of old age at 60.**
- Aliden Perenolde **died of old age at 61.**
- Tirion Fordring **died of old age at 65.**
- Galen Trollbane **died of old age at 63.**

<details><summary>View images</summary>

image
image
image
image
image
image

</details>

There were two instances of extremely early "natural deaths", but these may simply be outliers. Although I can imagine it being frustrating that a character as prominent as Varian Wrynn could die in this way:

- Horhunn Bronzebeard (Dwarf) **died of natural causes at age 13.**

<details><summary>View image</summary>

image

</details>

- Varian Wrynn (Human) **died of natural causes at age 18.**

<details><summary>View image</summary>

image

</details>

In one instance a night elf undead died of natural causes, which may not be intended to happen as they're immortal—unless this is simply a case of them decaying/rotting to death, in which case we should probably add a custom `death_reason` for that.

<details><summary>View image</summary>

image

</details>

The game spawned in some humans that were well over a lifespan considered realistic. Most of them died of old age after a few years, but I don't think humans this old should be spawning in at all unless there's a reason for it:

<details><summary>View images</summary>

image
image

</details>

**Overall though, I did not notice any elves or dwarves dying of old age at unreasonable ages.** 👍 However, I did notice some prominent characters dying of wounds which seemed kind of anti-climactic:

- Lor'themar Theron **died from his wounds at age 570.** _(27 years into playthrough)_
- Sylvanas Windrunner **died from her wounds at age 617.** _(34 years into playthrough)_
- Vereesa Windrunner **died from her wounds at age 281.** _(32 years into playthrough)_

As a side note, obesity seems to be rampant throughout all of Azeroth regardless of race. I saw a number of humans and elves who became obese and died due to complications of obesity (including Genn Greymane at age 66 and Anasterian Sunstrider at age 614). These types of deaths seem somewhat un-Warcraft to me, and should be limited by quite a large margin. But I understand this is not related to this particular issue, so maybe it should be addressed in another PR later on. Just something to keep in mind.

**Comment by zumbak04** [comment]
> _One observation I made is that all of these humans are landed with Barony tier titles and are under the Republic government type._

> The game spawned in some humans that were well over a lifespan considered realistic. Most of them died of old age after a few years, but I don't think humans this old should be spawning in at all unless there's a reason for it:

Should be fixed in 5bffffd784ffbd3bd8dcc4507e08a1ecdf81ecc9.

**Comment by zumbak04** [comment]
> _The elf populations seem to be stable, although from what I've seen the majority of elves are younger than 100. I infer that this is because of lethal events triggering such as assassinations, duels, or other mishaps killing off these elves before they can reach a hundred years of age._

Do you have saves? It may be due to new elves being born (so they're younger than your game time).

**Comment by zumbak04** [comment]
> **I noticed that most humans were dying of old age around 60-70**, which is fairly standard for Vanilla CK3, but not as common in the Warcraft universe as far as I know. I think, in general, humans should live to be at least 75 on average. It's especially anti-climatic in the case of characters like Tirion Fordring who were quite old.

Don't look average. Antonidas (one of the greatest mages with the strongest beard) died 71 year old.

**Comment by zumbak04** [comment]
> There were two instances of extremely early "natural deaths", but these may simply be outliers. Although I can imagine it being frustrating that a character as prominent as Varian Wrynn could die in this way:

Natural deaths happen before adulthood. You can see it on this [Graph](https://www.reddit.com/r/CrusaderKings/comments/j0ks4e/life_expectancy_and_cause_of_death_in_ck3/).

> In one instance a night elf undead died of natural causes, which may not be intended to happen as they're immortal—unless this is simply a case of them decaying/rotting to death, in which case we should probably add a custom death_reason for that.

Should be fixed in 295116db1c59b18cb547917722526d089b347466.

> However, I did notice some prominent characters dying of wounds which seemed kind of anti-climactic:

Should be fixed in 08af60baa5edebc79004ff02d76ec234e8c235ba.

> As a side note, obesity seems to be rampant throughout all of Azeroth regardless of race. I saw a number of humans and elves who became obese and died due to complications of obesity (including Genn Greymane at age 66 and Anasterian Sunstrider at age 614). These types of deaths seem somewhat un-Warcraft to me, and should be limited by quite a large margin. But I understand this is not related to this particular issue, so maybe it should be addressed in another PR later on. Just something to keep in mind.

I wouldn't fix it, 2 reasons:
- It's hilarious.
- It adds a nice realistic touch to the universe where we have never seen a person dying of a heart strike or cancer.

**Comment by ValianBlue** [comment]
> 
> 
> > _The elf populations seem to be stable, although from what I've seen the majority of elves are younger than 100. I infer that this is because of lethal events triggering such as assassinations, duels, or other mishaps killing off these elves before they can reach a hundred years of age._
> 
> Do you have saves? It may be due to new elves being born (so they're younger than your game time).

_I checked over this and that is definitely a contributing factor. I'll look into more on more extensive tests (100+ and 250+ years)._

**Review by ercarp — COMMENTED** [review]
Let an AI game run for **136 years**.

image

> Don't look average. Antonidas (one of the greatest mages with the strongest beard) died 71 year old.

Yes, I do actually retract my statement on that as I looked at the [lifespans on Wowpedia](https://wowpedia.fandom.com/wiki/Life_spans) and it classified 60 as old and 70 as venerable for humans, so I believe the current ages are correct and don't need to be changed.

> > The game spawned in some humans that were well over a lifespan considered realistic. Most of them died of old age after a few years, but I don't think humans this old should be spawning in at all unless there's a reason for it:
> 
> Should be fixed in [5bffffd](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/5bffffd784ffbd3bd8dcc4507e08a1ecdf81ecc9).

I'm still seeing some humans who are 200+ years old, although there are considerably fewer of them now. They seem to be mostly Mayors:

<details><summary>Click to expand</summary>

image
image

</details>

I'm also noticing that there are a lot of **_Bubonic Plague_** deaths, which wasn't really a thing in Warcraft. Do we have plans to tone that down at some point? Or maybe get rid of it entirely?

Overall, aside from the issue of some really old humans still spawning, I thought everything looked good for the most part and Sylvanas (as an example) was still alive after 136 years, so it looks like the issue with her dying of wounds was solved.

**Comment by zumbak04** [comment]
> I'm still seeing some humans who are 200+ years old, although there are considerably fewer of them now. They seem to be mostly Mayors:

Should be fixed in 921149250ce8a5a399b2cd991cf4f22c7f5bebd0.

> I'm also noticing that there are a lot of Bubonic Plague deaths, which wasn't really a thing in Warcraft. Do we have plans to tone that down at some point? Or maybe get rid of it entirely?

That's for another PR, opened an [Issue](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/619).

**Review by ercarp — COMMENTED** [review]
### Human Old Age Deaths

Old age deaths seem closer to Vanilla CK3 values now, although I noticed there was a significant uptick in old age deaths compared to the previous build, so whatever changes you made seems to have affected this. Not saying it's a bad thing though:

<details><summary>Click to expand</summary>

image
image

</details>

**Thoras Trollbane** died at **age 75** _(39 years into playthrough)_

<details><summary>Click to expand</summary>

image

</details>

**Archmage Antonidas** died at **age 84** _(34 years into playthrough)_

<details><summary>Click to expand</summary>

image

</details>

**Llane Wrynn** died at **age 69** _(28 years into playthrough)_

<details><summary>Click to expand</summary>

image

</details>

I think this was the oldest human I saw die of old age:

<details><summary>Click to expand</summary>

image

</details>

### Oddities

**Aegwynn** died of old age 2 years into a playthrough. Is this intended? I thought she was immortal or something.

<details><summary>Click to expand</summary>

image

</details>

**Mekkatorque** also died of old age just 12 years into a playthrough. In terms of the Warcraft timeline, this means he would have died before the Third War (whereas we see him in Battle for Azeroth, two decades later, where he's still quite sprightly for his age). He is certainly an old gnome, but not old enough to be on death's door just yet if you ask me.

<details><summary>Click to expand</summary>

image

</details>

I did not observe any dwarves dying of old age earlier than intended.

**The following may not be relevant, but I thought I would include them in case they are:**

**Kael'thas** died of **smallpox** at age 574 (13 years into playthrough)

<details><summary>Click to expand</summary>

image

</details>

**Anasterian** died of cancer 21 years into the playthrough. [Much like with Bubonic Plague](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/619), I wonder if we should substitute cancer with some other illness? I don't think cancer exists in the Warcraft universe, or if it does, it's healable by priests.

<details><summary>Click to expand</summary>

image

</details>

**Illidan** died in Maiev's dungeons less than a year into the playthrough.

<details><summary>Click to expand</summary>

image

</details>

Death reasons are also missing localization, but I think you already noticed that. Other than that, I would say everything looks good to me and the oddities mentioned above all come from a single playthrough so they may not mean anything at all.

**Found zero humans spawning in above their indeed lifespan.** 👍

**Comment by zumbak04** [comment]
> Aegwynn died of old age 2 years into a playthrough. Is this intended? I thought she was immortal or something.

Changed in f32f0c7827b89e2cfaf6af4401bd96ba34bf81ec.

> I noticed there was a significant uptick in old age deaths compared to the previous build, so whatever changes you made seems to have affected this.

Don't think I changed anything since your last review. May be random.

> Mekkatorque also died of old age just 12 years into a playthrough. In terms of the Warcraft timeline, this means he would have died before the Third War (whereas we see him in Battle for Azeroth, two decades later, where he's still quite sprightly for his age). He is certainly an old gnome, but not old enough to be on death's door just yet if you ask me.

Fixed in 4968e29817430c6ffee99c97ec4f4d396d9e8749. He's supposed to be younger.

> I wonder if we should substitute cancer with some other illness?

I wouldn't and we didn't in CK2 since it's not associated with a real virus or bacteria. Also, cancer has a unique mechanic where the chance grows with age. There's no close analogy in Warcraft.

> Death reasons are also missing localization, but I think you already noticed that. Other than that, I would say everything looks good to me and the oddities mentioned above all come from a single playthrough so they may not mean anything at all.

Fixed in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/621.

**Review by ercarp — APPROVED** [review]
> 
> 
> > Aegwynn died of old age 2 years into a playthrough. Is this intended? I thought she was immortal or something.
> 
> Changed in [f32f0c7](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/f32f0c7827b89e2cfaf6af4401bd96ba34bf81ec).

To clarify, I don't think she was ever immortal at birth, it's more so that she was able to extend her life with magic once she became the Guardian of Tirisfal.

> Aegwynn served as the Guardian of Tirisfal **for over 1,000 years**. Following the end of her reign, she would eventually serve as Jaina Proudmoore's chamberlain for a time **near the end of her life**.

The above quote from Wowpedia indicates that she died some kind of a natural death, although I'm not 100% caught up on Aegwynn's lore so I'm not sure what the exact circumstances of her death were. But if I had to guess, I would say maybe being a Guardian is similar to the [One Ring](http://tolkiengateway.net/wiki/The_One_Ring) from LOTR and its ability to extend the user's life beyond a normal lifespan. And once she gave up the Guardian's mantle, she started aging naturally again, and died of old age.

But there's nothing that needs changing here. I'm just rambling.

> I wouldn't and we didn't in CK2 since it's not associated with a real virus or bacteria. Also, cancer has a unique mechanic where the chance grows with age. There's no close analogy in Warcraft.

That's fair.

> > Death reasons are also missing localization, but I think you already noticed that. Other than that, I would say everything looks good to me and the oddities mentioned above all come from a single playthrough so they may not mean anything at all.
> 
> Fixed in #621.

In that case, everything on this branch looks good to me!

**Review by TheGroxEmpire — COMMENTED** [review]
- I'm not sure if it's caused by this PR but the death causes are missing their loc:
<details>

image
image
image
image

</details>

- Humans appeared to die out starting at 64 - 80 as intended.
- Dragons, Trolls, Tauren, and Nerubian appeared to have Humans life expectancy. Trolls and Tauren could have almost than double of Humans life expectancy. Dragons and Nerubians should live for thousands of years.
<details>

image
image

</details>

- I found a lot of long living races died early by natural causes
<details>

image

image
image

</details>

- It might be because some long lived race characters are not receiving their +long-lived health buff:
<details>

image
</details>

**Comment by zumbak04** [comment]
> I'm not sure if it's caused by this PR but the death causes are missing their loc:

Should be fixed with the master merge.

> Trolls and Tauren could have almost than double of Humans life expectancy.

Why? Only Cairne was over 100. It's said to be rare.
Rastakhan is blessed by loa.

**Comment by zumbak04** [comment]
> I found a lot of long living races died early by natural causes

4 characters look like they died in childhood (they have just 1 personal trait).
The other 2 have wounds and illnesses.

> It might be because some long lived race characters are not receiving their +long-lived health buff:

The buff is for the game start characters because they spawn with low health.

**Comment by TheGroxEmpire** [comment]
> Why? Only Cairne was over 100. It's said to be rare.

According to the Sean "Loreology" Copeland, the current head of lore
 > Loreology on Twitter (2014-06-12) “@Loreology How old is a tauren canonically when they’re an adult, middle aged and old?” “Here’s what I have: Tauren reach “old age” ~ 95 and “venerable old age” ~110.”
(https://wowpedia.fandom.com/wiki/Life_spans#cite_note-loreology1-89)

**Review by TheGroxEmpire — APPROVED** [review]
The rest looks good to me!

**Pull request merged**
