### PR TITLE
3D Hotfixes

### PR DESCRIPTION
**Pull request by Chomski2**
## Changelog:
Hotfix of some of the 3D stuff

- [x] Re added gnome goggles
- [x] Re added rexxar mask
- [x] Re added Zandalari imperial clothes
- [x] Re added goblin hats
- [x] High elf armor fixxed
- [x] Tusks fixxed

## Tests:
- [ ] There are no new errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

### CODE REVIEW

**Comment by Raged50** [comment]
LGTM, no error issues, requires one additional tester

**Comment by Chomski2** [comment]
Additional work is needed and is not longer ready for merge

**Review by ElMariuso — APPROVED** [review]
Good to me!

**Comment by Raged50** [comment]
LGTM

**Pull request merged**
