### PR TITLE
Female Model for Male Harpies

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Assigned the **_Female Harpy_** model to **_Male Harpies_** as a temporary workaround to fix the invisible Male Harpies.
  - _(Note: In the future, we may look at trying to create a custom model for Male Harpies or trying to use code to disable Male Harpies altogether, but I think applying this change as a temporary workaround will be preferable to having invisible character models.)_

<details><summary>Image</summary>

image

</details>

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
1. To view the changes in-game, downgrade your **Crusader Kings III** to `1.5.0.1` and look for **Male** characters with the **_Harpy_** creature trait using the **Character Finder** panel.

### CODE REVIEW

**Review by CantTouchThisJinTao — APPROVED** [review]
Checked all 3 start dates and all males seem to have female model. Not noticing any issues.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Review by TheDrPibb1999 — APPROVED** [review]
LGTM no issues!

**Review by sumankun — APPROVED** [review]
LGTM

**Pull request merged**
