### PR TITLE
Character sexualities

### PR DESCRIPTION
**Pull request by Grekopithikos**
## Changelog:
Many characters who have stated lovers and soulmates now have set sexualities.
Dagran and Moira get married when they become soulmates
The couples Genn and Mia, alongside Nielas and Aegwynn become soulmates when they get married

All Sayaads are now automatically bisexual
Sayaads are more likely to grow up to be lustful

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Check if Sayaadi children grow up to be bisexual and most likely lustful

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Aegwynn isn't set to Soulmate with Nielas Aran
<details>

image

</details>

Other than that, it appears to be working correctly.

**Comment by Grekopithikos** [comment]
>Aegwynn isn't set to Soulmate with Nielas Aran

Isn't that because he's dead?

**Comment by TheGroxEmpire** [comment]
> > Aegwynn isn't set to Soulmate with Nielas Aran
> 
> Isn't that because he's dead?

That is true. Curious why would we set up it as Lovers when it doesn't matter because he's dead. But it's a non issue.

**Review by TheGroxEmpire — APPROVED** [review]

**Comment by Grekopithikos** [comment]
>That is true. Curious why would we set up it as Lovers when it doesn't matter because he's dead. But it's a non issue.

Well it was mostly for the sake of lore details and just in case we ever get an earlier bookmark

**Pull request merged**
