### PR TITLE
Green Eyes for Blood Elves

### PR DESCRIPTION
**Pull request by ercarp**
ℹ️ **Development Notice**: Please note that this branch is based on [1-8-1-update](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/1-8-1-update), which means it **_should not_** be merged into `master` until after the `1-8-1-update` branch has been merged.

## Changelog:
- **High Elf** eyes become green when they have the Sin'dorei culture.

<details><summary>Image</summary>

image

</details>

- **Sin'dorei** culture use red and yellow color palettes

<details><summary>Image</summary>

image

</details>

## To-do list:
- [x]  Make blood elves use red clothing:
- [x]  Create the appropriate genes.
- [x]  Create the appropriate `.asset`.
- [x]  Create `blood_elf` texture variations.

## ⚠️ Known issues

1. Temple holders use translucent void as clothes
<details><summary>Image</summary>

image

</details>

2. Some Sin'dorei dont use `blood_elven_gfx`

<details><summary>Image</summary>

image

</details>

3. Lor'themar Theron have a piece of armor clipping

<details><summary>Image</summary>

image

### CODE REVIEW

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Review by CantTouchThisJinTao — APPROVED** [review]
LGTM

**Review by TheDrPibb1999 — APPROVED** [review]
LGTM :D Should we eventually implement a recolor for their armor as well?

**Review by ElMariuso — APPROVED** [review]
I think it look good

**Pull request merged**
