### PR TITLE
5th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed some high elves being bald.
- Camels counter casters once more.
- Fixed `yearly.1090` spawning family without race traits.
- The Horde Invasion no longer happens if you start  in the 603 or 605 startdates.
- The camera can't go outside the map borders.
- Fixed an issue where the Union decision notification could show with a blank Union name.
- Fixed an issue where adding the Drunkard to a dwarf maked his beards disapear.

## Developer changelog:
- Fixed `localization_reader.cpp:239` and `jomini_script_system.cpp:169` in `wc` files.
- Replaced `physique_good_2` by `strong`.
- Fixed `location` error in `set_race_effect`.
- Fixed `scandi_adventurer_region_trigger` error in `viking_conquest_ai_score_value`.

# How to test:
`event yearly.1090` in the console to fire the event.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- The Horde Union on later start dates starts with no Regent and stays as such.
<details>

image
image
</details>

- Camera can still go out of the border by a bit on the corners:
<details>

image
image
image
image

</details>

- Unrelated bug. Union decision notification will appear with blank name until you open the tab:
<details>

image
image
</details>

- The rest of the bugs are fixed.

**Comment by zumbak04** [comment]
> * The Horde Union on later start dates starts with no Regent and stays as such.

Yes, it's mentioned in the Horde features.
<details>
<summary>Click to expand</summary>

image

</details>

> * Camera can still go out of the border by a bit on the corners:

It's fine. The camera region is a square.

> * Unrelated bug. Union decision notification will appear with blank name until you open the tab:

Fixed in 37fc67faffa03a51aae92d4035a7113afa7602de.

**Comment by robmart** [comment]
> > * Camera can still go out of the border by a bit on the corners:
> 
> It's fine. The camera region is a square.

The square could be a bit tighter I think. In most places at the edge your camera is halfway in the void. Having it tighter would look better and not have any negative effects IMO.

**Review by TheGroxEmpire — APPROVED** [review]
All bugs seem to be fixed, LGTM!

**Review by TheDrPibb1999 — APPROVED** [review]
Went down the list and had no issues and all seemed to be fixed, blood elves were haired, the 1090 event worked, no horde invasions, unions were good. And all bugs addressed by Grox were fixed and well rounded on my end!

**Pull request merged**
