### PR TITLE
Cultist Clothes

### LINKED ISSUE #425: Goblin Hat in Barbershop
**Describe your suggestion in full detail below:**
Just noticed, we haven't added the goblin top hat to the Barbershop, ooopsie.

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Scourge characters wear robes and hoods. Councilors and high nobles wear horned hoods. Their knights wear dark-colored armor.
- Court chaplains of Death religious family wear robes and horned hoods.
- Kel'Thuzad and other humans converted to Mord'truari have Scourge culture in the year 603 and 605 bookmarks.
- Added new clothes and headgears to the Barbershop.
- Scourge's **_Offer Vassalage_** interaction changes the culture of vassal unless it's vrykul or nerub.

# Tasks:
- [x] Localize draenei clothes
- [x] Add headgear and clothes to options
- [x] Scourge armor
- [x] Scourge vassals accept Scourge culture

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Run the 603 and 605 bookmarks, check how Scourge characters look.

Resolved #425.

### CODE REVIEW

**Review by CantTouchThisJinTao — COMMENTED** [review]
Not completely sure about some of the hoods, Cultist Hood and Cultist Horned hood can tend to end sticking into the neck, I think it'd look better if they ended a little bit lower instead. I like the overall look of the hoods it's just them ending on the neck like that looks a bit weird to me.

<details>
<summary>Hood1</summary>

example1

</details>

The screenshot below shows a slight clipping issue on the left as well but it's barely noticeable 

<details>
<summary>Hood2</summary>

example2+clipping

</details>

Marshalls also currently just look like regular knights even when landed, it would be cool if they had a helmet, is this intended for a future PR?

<details>
<summary>Marshall</summary>

marshalcouncillor

</details>

Outfits/colours in general look good to me.

**Comment by zumbak04** [comment]
> Not completely sure about some of the hoods, Cultist Hood and Cultist Horned hood can tend to end sticking into the neck, I think it'd look better if they ended a little bit lower instead. I like the overall look of the hoods it's just them ending on the neck like that looks a bit weird to me.

Lowered in 27e915b8651658ba5aee8d7a2acd9b155aabc202.

> The screenshot below shows a slight clipping issue on the left as well but it's barely noticeable

Yes, I can't notice it.

> Marshalls also currently just look like regular knights even when landed, it would be cool if they had a helmet, is this intended for a future PR?

This chainmail coif is a headgear.

**Review by CantTouchThisJinTao — APPROVED** [review]
Yeah I think the hoods look better. See what other people think about them.
Everything seems to be working anyway.

**Review by CatWitchLily — COMMENTED** [review]
I think they look good. 
I searched through the Scourge characters and noticed a couple not donning hoods. Is that expected?

**Comment by zumbak04** [comment]
> I think they look good. I searched through the Scourge characters and noticed a couple not donning hoods. Is that expected? 

Yes. They wear martial outfits.

**Review by ElMariuso — APPROVED** [review]
LGTM!

**Review by Holt228 — COMMENTED** [review]
Cultist Clothes cases:

1. No unexpected errors


**Expected result**: There are no errors in wc files in Documents\Paradox Interactive\Crusader Kings III\logs\error.log except portrait_decals.cpp:101
**Actual result**: No unexpected errors in wc files
**Environment**: Windows 10, CK III 1.4.4 (Azure), GOA Pre-alpha cultist-clothes branch

2. RAM usage

**Expected result**: The mod takes less than 5.5 GB in the Task Manager (Windows)
**Actual result**: The mod takes up 4,9 GB in the Task Manager
**Environment**: Windows 10, CK III 1.4.4 (Azure), GOA Pre-alpha cultist-clothes branch

**Review by TheDrPibb1999 — APPROVED** [review]
LGTM!!

**Review by Holt228 — APPROVED** [review]
Cultist Clothes:

1. 
**ER**: Scourge characters wear robes and hoods. Councilors and high nobles wear horned hoods. Their knights wear dark-colored armor
**AR**: Scourge characters wear robes and hoods depending on their status. Chaplains and spymasters wear horned hoods, chancellors and stewards wear normal cultural clothing. 

2.
**ER**: Court chaplains of Death religious family wear robes and horned hoods.
**AR**: Court chaplains of Death religious family wear robes and horned hoods.

3. 
**ER**: Kel'Thuzad and other humans converted to Mord'truari have Scourge culture in the year 603 and 605 bookmarks
**AR**: Kel'Thuzad and other humans converted to Mord'truari have Scourge culture in the year 603 and 605 bookmarks

4. 
**ER**: New clothes and headgear options show up in the Barbershop
**AR**: New clothes and headgear options show up in the Barbershop

5. 
**ER**: Scourge's Offer Vassalage interaction changes the culture of vassal unless it's vrykul or nerub
**AR**: Scourge's Offer Vassalage interaction changes the culture of vassal unless it's vrykul or nerub.

Comment: 

No errors besides those in wc files, the mod takes up 4,9 GB of RAM.

**Pull request merged**
