### PR TITLE
Maiev Personality Traits

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- ~~Changed Maiev's personality traits to **Callous**, **Arrogant**, **Vengeful**, and **Diligent**.~~
- 9d60ae3d3e605ae1595a7f3e903158b09022dab4: Changed Maiev's traits to **Diligent**, **Vengeful**, **Zealous**, and **Stubborn**.
  - _Old traits were **Chaste**, **Arrogant**, **Wrathful**, and **Diligent**._

<details><summary>Screenshot</summary>

image

</details>

### Reasoning

We discussed Maiev's current traits on the Discord server and came to the conclusion that these traits would be a better fit for her character.

From [Wowpedia](https://wowpedia.fandom.com/wiki/Maiev_Shadowsong#Personality):

> Maiev is a driven **(Ambitious)** and ruthless **(Callous)** individual, utterly dedicated **(Diligent)** to her mission to see Illidan either recaptured or killed **(Vengeful)**. Almost every thought she has is poisoned by her obsession with the demon hunter; even wistful memories of her youth inevitably come back to Illidan.

> She feels entirely justified in her actions and considers her cause to be a righteous one **(Stubborn/Callous)**, accepting personal responsibility for the many losses and setbacks she's suffered only under very specific circumstances; more commonly, she lays blame for her defeats at the feet of others, either for not adequately supporting her or finding fault with her methods **(Arrogant/Arbitrary)**.

> Maiev believes that there is little wrong with utilizing questionable methods for the sake of destroying a greater evil **(Callous/Sadistic)**. She is quick to anger **(Wrathful)** and not above risking rash and destructive actions, exerting control over her thirst for vengeance and remaining civil in the face of opposition with considerable effort.

> Her powers as a Warden appear to be substantially enhanced by her thirst for vengeance **(Vengeful)**, and as a former high priestess of the moon goddess, she retains ancient knowledge that even Shandris Feathermoon was unaware of, such as the darker and forbidden aspects of Elune. **(Zealous/Deceitful/Callous)**

> She is fairly xenophobic, believing her people have been weakened by their association with the "lesser races" of the Alliance and their problems. **(Arrogant)**

### CODE REVIEW

**Comment by ValianBlue** [comment]
_I suggest changing Diligent to Ambitious, but the new set of traits work nonetheless._

**Review by runtd — APPROVED** [review]
I'd be fine with both dilligent and Ambitious so no matter if you replace it or not I approve the changes.

**Review by hamjustine — APPROVED** [review]
Vengeful was so obvious, i approve those changes =)

**Review by arithon — CHANGES_REQUESTED** [review]
I'd vote for Diligent, Vengeful, Zealous, as suggested in the dev-channel.

**Review by zumbak04 — COMMENTED** [review]
> I'd vote for Diligent, Vengeful, Zealous, as suggested in the dev-channel.

Agree.

**Comment by ercarp** [comment]
> 
> 
> I'd vote for Diligent, Vengeful, Zealous, as suggested in the dev-channel.

Changed in 9d60ae3d3e605ae1595a7f3e903158b09022dab4 but I gave her Stubborn as well since she's a lore-important character and therefore can/should have four personality traits.

**Review by arithon — APPROVED** [review]
I'm ok if Zumbak doesn't mind the 4 traits.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
