### PR TITLE
Models

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added placeholder static models for the murlocs, furbolgs, quilboars and kobolds.

# How to test:
Check these models in-game and tell your opinion.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- The adult murlocs fins on portrait model are intruding with some of the UI e.g., hitting UI text, hitting portrait above them. Suggestion: Make the adult murlocs a bit shorter on portrait, or at least their fins. The baby murlocs are the acceptable portrait model height to me.
<details>

image
image
</details>

- Female quilboars should have shorter tusks than the male quilboars. (https://www.wowhead.com/npc=5863/geopriest-gukkrok#modelviewer)
<details>
<details>
<summary>In-game</summary>

image
</details>
<details>
<summary>Wowhead models</summary>

Female:
image
Male:
image
</details>
</details>
</details>

- Furbolgs model looks unfinished and low res compared to other model.
<details>

image
</details>

**Comment by zumbak04** [comment]
> * The adult murlocs fins on portrait model are intruding with some of the UI e.g., hitting UI text, hitting portrait above them. Suggestion: Make the adult murlocs a bit shorter on portrait, or at least their fins. The baby murlocs are the acceptable portrait model height to me.

I don't want to hurt the murlocs and cut their spikes because of this. It will affect all portraits. Even where they stand tall.
Shortening the model isn't an option too. I made it so the camera is focused on their "face" like it's with the humans.

> * Female quilboars should have shorter tusks than the male quilboars. (https://www.wowhead.com/npc=5863/geopriest-gukkrok#modelviewer)

Made it customizable in 51d71a12b0ebcdb2e1bd28216ba83d6735d47215. Females may have big tusks, but most of them will have small ones.

> * Furbolgs model looks unfinished and low res compared to other model.

IIRC, it's 12 years old and there's no better model than this one.

**Review by TheGroxEmpire — COMMENTED** [review]
> I don't want to hurt the murlocs and cut their spikes because of this. It will affect all portraits. Even where they stand tall.
Shortening the model isn't an option too. I made it so the camera is focused on their "face" like it's with the humans.

Fair point, it's not intrusive enough to commit massive crime to the murloc kind.

> Made it customizable in 51d71a1. Females may have big tusks, but most of them will have small ones.

Good idea, they look good.

>IIRC, it's 12 years old and there's no better model than this one.

Yeah it was released in Wrath. Would it be possible to get WC3 Reforged model? They have decent furbolg model.

**Comment by zumbak04** [comment]
> Yeah it was released in Wrath. Would it be possible to get WC3 Reforged model? They have decent furbolg model.

I got the furbolg model using CascView, but then a file format hell happened. I work in Blender, the models saved in .mdx format. Blender has an addon to export .mdl format, but the plugin to convert .mdx to .mdl doesn't work.
In short, it looks possible, but I'm not willing to solve it now.

**Review by TheGroxEmpire — APPROVED** [review]
> I got the furbolg model using CascView, but then a file format hell happened. I work in Blender, the models saved in .mdx format. Blender has an addon to export .mdl format, but the plugin to convert .mdx to .mdl doesn't work.
In short, it looks possible, but I'm not willing to solve it now. Maybe later.

I've read from a [WC3 Reforged forum](https://us.forums.blizzard.com/en/warcraft3/t/hi-is-there-any-way-to-extract-models-from-reforged-and-import-them-into-blender/25256/4) that they were using [Retera Model Studio: Reforged Edition](https://github.com/Retera/ReterasModelStudio) for exporting the models to Blender.
But yeah, it's not something that is pressing compared to the effort to figure it out, so I won't halt this PR solely because of that.
Though I humbly insist that we update the furbolg model someday in the future.

**Review by PapaWarius — APPROVED** [review]

**Comment by zumbak04** [comment]
> I've read from a [WC3 Reforged forum](https://us.forums.blizzard.com/en/warcraft3/t/hi-is-there-any-way-to-extract-models-from-reforged-and-import-them-into-blender/25256/4) that they were using [Retera Model Studio: Reforged Edition](https://github.com/Retera/ReterasModelStudio) for exporting the models to Blender.
> But yeah, it's not something that is pressing compared to the effort to figure it out, so I won't halt this PR solely because of that.
> Though I humbly insist that we update the furbolg model someday in the future.

Still don't have time thus I'll convert it to an issue to be implemented in the future.

**Pull request merged**
