### PR TITLE
KINDA Vanilla Hairs

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Made a variation of Straight Pointy Beard called Straight Pointy Goatee for the males.
- Added a new male hairstyle, Bald Top.

# How to test:
Open the Ruler Designer, find the new hair and beard. tell me your opinion.

Alternatively, to take a closer look at Bald Top:
1) Run the game with the [debug mode](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode)
2) Press `~`, the tilde, click **_Portrait Editor_**
3) In the ethnicity list find `green_orc`, click **_Randomize DNA_**.
4) Click **_3D View_** and move the opened window somewhere to empty space. You can rotate the character there.
5) Spam **_Randomize DNA_** until you see the bald top hairstyle.

### CODE REVIEW

**Review by Deuce20201 — COMMENTED** [review]
Whenever I randomize appearance in portrait editor, I only get the same portrait: front bald back hair. (when I'm trying to get a bald orc)

**Comment by zumbak04** [comment]
> Whenever I randomize appearance in portrait editor, I only get the same portrait: front bald back hair. (when I'm trying to get a bald orc). Is this the only bald portrait for orcs?

On your screenshots, everything looks like you haven't clicked on randomize DNA and it's the same portrait.

**Comment by zumbak04** [comment]
> Whenever I randomize appearance in portrait editor, I only get the same portrait: front bald back hair. (when I'm trying to get a bald orc). Is this the only bald portrait for orcs?

Oh, I get it now. Yes, that's the only half-bald hairstyle in the entire CK3 and the mod.

**Comment by Deuce20201** [comment]
> > Whenever I randomize appearance in portrait editor, I only get the same portrait: front bald back hair. (when I'm trying to get a bald orc). Is this the only bald portrait for orcs?
> 
> On your screenshots, everything looks like you haven't clicked on **_Randomize DNA_** and it's the same orc. So I'm confused by your question.

I should have clarified that all 3 are the same picture, just in different angles.

**Comment by zumbak04** [comment]
> But no matter how many times I randomize appearance, I never get a complete bald portrait

You won't in the Portrait Editor.

**Review by TheGroxEmpire — COMMENTED** [review]
Bald Top, Straight Pointy Beard called Straight Pointy Goatee for the males are appearing in the game. Green orcs are also seen being generated with Bald Top.
I want to suggest that you also give Dwarves random DNA generator to give them Bald Top also. I think it would be fitting for them.
<details>

image
image

**Comment by zumbak04** [comment]
> I want to suggest that you also give Dwarves random DNA generator to give them Bald Top also. I think it would be fitting for them.

Added in cfcc3a26b955daeeb2188c4cf7d9dda0745d91c5.

**Review by TheGroxEmpire — APPROVED** [review]
>Added in cfcc3a2.

Can confirm it's on the Dwarves now.

**Pull request merged**
