### PR TITLE
Single Charge Position

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- Changed all single charge CoA positions so we no longer need to raise our CoAs a bit higher to be centered. This is an updated mask:
<details>
<summary>Click to expand</summary>

image

</details>

# How to test:
Check our CoAs positions, tell if they're centered still.

### CODE REVIEW

**Comment by MemeWizard** [comment]
The most are fine, but some are a bit higher than it feels they should be.

<details>
<summary>Click to expand</summary>

image
image
image
image
image
image
image

</details>

**Review by runtd — APPROVED** [review]
Everything seems alright for me

**Comment by zumbak04** [comment]
> The most are fine, but some are a bit higher than where it feels they should be.

Check in 85f6a128ea1363b93676967bbf3dc2956cea5f8c.

**Review by MemeWizard — APPROVED** [review]
b

**Pull request merged**
