### PR TITLE
Night Elf Ethnicity Rework

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Remade the current ethnicity used by night elves.
- Cultures that used either `highborne_ethos` or `night_elven` ethnicities have been replaced with the reworked version for testing purposes.

## Notes:
- The troll ethnicity uses the current `night_elven` ethnicity as a template, so be aware that it could break if replaced with the reworked version.

# How to test:
There are two ways you can test this:
1. Generate `nelf_rework` or `highborne_rework` ethnicities using either the Ruler Designer or [Debug Portrait Editor](https://ck3.paradoxwikis.com/Console_commands#Debug_mode).
2. Alternatively, you can start a new game and look for characters using the reworked portraits in-game.

### CODE REVIEW

**Comment by ercarp** [comment]
Some image previews for those who can't test in game at the moment:
image
image
image
image
image
image
image
image

**Review by zumbak04 — COMMENTED** [review]
Mostly they're fine, but I generated a really spooky face.
Take a look, maybe you will find genes to improve.
I feel it's something with eyes.
<details>
<summary>Preview</summary>

image

</details>
<details>
<summary>Genes</summary>

```
ruler_designer_2882143103={
	type=female
	id=0
	genes={ 		hair_color={ 216 142 216 142 }
 		skin_color={ 218 83 218 83 }
 		eye_color={ 167 113 167 113 }
 		gene_chin_forward={ "chin_forward_neg" 146 "chin_forward_neg" 146 }
 		gene_chin_height={ "chin_height_pos" 199 "chin_height_pos" 199 }
 		gene_chin_width={ "chin_width_neg" 68 "chin_width_neg" 68 }
 		gene_eye_angle={ "eye_angle_neg" 153 "eye_angle_neg" 153 }
 		gene_eye_depth={ "eye_depth_neg" 90 "eye_depth_neg" 90 }
 		gene_eye_height={ "eye_height_neg" 121 "eye_height_neg" 121 }
 		gene_eye_distance={ "eye_distance_neg" 138 "eye_distance_neg" 138 }
 		gene_eye_shut={ "eye_shut_neg" 95 "eye_shut_neg" 95 }
 		gene_forehead_angle={ "forehead_angle_neg" 65 "forehead_angle_neg" 65 }
 		gene_forehead_brow_height={ "forehead_brow_height_neg" 191 "forehead_brow_height_neg" 191 }
 		gene_forehead_roundness={ "forehead_roundness_neg" 144 "forehead_roundness_neg" 144 }
 		gene_forehead_width={ "forehead_width_neg" 230 "forehead_width_neg" 230 }
 		gene_forehead_height={ "forehead_height_neg" 110 "forehead_height_neg" 110 }
 		gene_head_height={ "head_height_neg" 182 "head_height_neg" 182 }
 		gene_head_width={ "head_width_neg" 112 "head_width_neg" 112 }
 		gene_head_profile={ "head_profile_neg" 38 "head_profile_neg" 38 }
 		gene_head_top_height={ "head_top_height_neg" 102 "head_top_height_neg" 102 }
 		gene_head_top_width={ "head_top_width_neg" 140 "head_top_width_neg" 140 }
 		gene_jaw_angle={ "jaw_angle_neg" 77 "jaw_angle_neg" 77 }
 		gene_jaw_forward={ "jaw_forward_neg" 118 "jaw_forward_neg" 118 }
 		gene_jaw_height={ "jaw_height_neg" 111 "jaw_height_neg" 111 }
 		gene_jaw_width={ "jaw_width_pos" 123 "jaw_width_pos" 123 }
 		gene_mouth_corner_depth={ "mouth_corner_depth_pos" 220 "mouth_corner_depth_pos" 220 }
 		gene_mouth_corner_height={ "mouth_corner_height_neg" 174 "mouth_corner_height_neg" 174 }
 		gene_mouth_forward={ "mouth_forward_neg" 136 "mouth_forward_neg" 136 }
 		gene_mouth_height={ "mouth_height_neg" 77 "mouth_height_neg" 77 }
 		gene_mouth_width={ "mouth_width_neg" 117 "mouth_width_neg" 117 }
 		gene_mouth_upper_lip_size={ "mouth_upper_lip_size_neg" 189 "mouth_upper_lip_size_neg" 189 }
 		gene_mouth_lower_lip_size={ "mouth_lower_lip_size_neg" 181 "mouth_lower_lip_size_neg" 181 }
 		gene_mouth_open={ "mouth_open_pos" 0 "mouth_open_pos" 0 }
 		gene_neck_length={ "neck_length_neg" 151 "neck_length_neg" 151 }
 		gene_neck_width={ "neck_width_pos" 34 "neck_width_pos" 34 }
 		gene_bs_cheek_forward={ "cheek_forward_neg" 76 "cheek_forward_neg" 76 }
 		gene_bs_cheek_height={ "cheek_height_pos" 8 "cheek_height_pos" 8 }
 		gene_bs_cheek_width={ "cheek_width_pos" 9 "cheek_width_pos" 9 }
 		gene_bs_ear_angle={ "ear_angle_neg" 0 "ear_angle_neg" 0 }
 		gene_bs_ear_inner_shape={ "ear_inner_shape_pos" 138 "ear_inner_shape_pos" 138 }
 		gene_bs_ear_bend={ "ear_both_bend_pos" 36 "ear_both_bend_pos" 36 }
 		gene_bs_ear_outward={ "ear_outward_pos" 4 "ear_outward_pos" 4 }
 		gene_bs_ear_size={ "ear_size_pos" 51 "ear_size_pos" 51 }
 		gene_bs_eye_corner_depth={ "eye_corner_depth_neg" 101 "eye_corner_depth_neg" 101 }
 		gene_bs_eye_fold_shape={ "eye_fold_shape_neg" 43 "eye_fold_shape_neg" 43 }
 		gene_bs_eye_size={ "eye_size_pos" 27 "eye_size_pos" 27 }
 		gene_bs_eye_upper_lid_size={ "eye_upper_lid_size_pos" 136 "eye_upper_lid_size_pos" 136 }
 		gene_bs_forehead_brow_curve={ "forehead_brow_curve_pos" 219 "forehead_brow_curve_pos" 219 }
 		gene_bs_forehead_brow_forward={ "forehead_brow_forward_pos" 99 "forehead_brow_forward_pos" 99 }
 		gene_bs_forehead_brow_inner_height={ "forehead_brow_inner_height_neg" 6 "forehead_brow_inner_height_neg" 6 }
 		gene_bs_forehead_brow_outer_height={ "forehead_brow_outer_height_pos" 31 "forehead_brow_outer_height_pos" 31 }
 		gene_bs_forehead_brow_width={ "forehead_brow_width_pos" 112 "forehead_brow_width_pos" 112 }
 		gene_bs_jaw_def={ "jaw_def_pos" 8 "jaw_def_pos" 8 }
 		gene_bs_mouth_lower_lip_def={ "mouth_lower_lip_def_pos" 129 "mouth_lower_lip_def_pos" 129 }
 		gene_bs_mouth_lower_lip_full={ "mouth_lower_lip_full_neg" 36 "mouth_lower_lip_full_neg" 36 }
 		gene_bs_mouth_lower_lip_pad={ "mouth_lower_lip_pad_neg" 240 "mouth_lower_lip_pad_neg" 240 }
 		gene_bs_mouth_lower_lip_width={ "mouth_lower_lip_width_neg" 8 "mouth_lower_lip_width_neg" 8 }
 		gene_bs_mouth_philtrum_def={ "mouth_philtrum_def_pos" 14 "mouth_philtrum_def_pos" 14 }
 		gene_bs_mouth_philtrum_shape={ "mouth_philtrum_shape_pos" 0 "mouth_philtrum_shape_pos" 0 }
 		gene_bs_mouth_philtrum_width={ "mouth_philtrum_width_pos" 57 "mouth_philtrum_width_pos" 57 }
 		gene_bs_mouth_upper_lip_def={ "mouth_upper_lip_def_pos" 208 "mouth_upper_lip_def_pos" 208 }
 		gene_bs_mouth_upper_lip_full={ "mouth_upper_lip_full_neg" 53 "mouth_upper_lip_full_neg" 53 }
 		gene_bs_mouth_upper_lip_profile={ "mouth_upper_lip_profile_neg" 66 "mouth_upper_lip_profile_neg" 66 }
 		gene_bs_mouth_upper_lip_width={ "mouth_upper_lip_width_neg" 23 "mouth_upper_lip_width_neg" 23 }
 		gene_bs_nose_forward={ "nose_forward_pos" 53 "nose_forward_pos" 53 }
 		gene_bs_nose_height={ "nose_height_neg" 151 "nose_height_neg" 151 }
 		gene_bs_nose_length={ "nose_length_neg" 121 "nose_length_neg" 121 }
 		gene_bs_nose_nostril_height={ "nose_nostril_height_pos" 51 "nose_nostril_height_pos" 51 }
 		gene_bs_nose_nostril_width={ "nose_nostril_width_pos" 52 "nose_nostril_width_pos" 52 }
 		gene_bs_nose_profile={ "nose_profile_pos" 115 "nose_profile_pos" 115 }
 		gene_bs_nose_ridge_angle={ "nose_ridge_angle_pos" 87 "nose_ridge_angle_pos" 87 }
 		gene_bs_nose_ridge_width={ "nose_ridge_width_neg" 165 "nose_ridge_width_neg" 165 }
 		gene_bs_nose_size={ "nose_size_pos" 16 "nose_size_pos" 16 }
 		gene_bs_nose_tip_angle={ "nose_tip_angle_neg" 118 "nose_tip_angle_neg" 118 }
 		gene_bs_nose_tip_forward={ "nose_tip_forward_pos" 71 "nose_tip_forward_pos" 71 }
 		gene_bs_nose_tip_width={ "nose_tip_width_pos" 84 "nose_tip_width_pos" 84 }
 		face_detail_cheek_def={ "cheek_def_02" 163 "cheek_def_02" 163 }
 		face_detail_cheek_fat={ "cheek_fat_03_pos" 83 "cheek_fat_03_pos" 83 }
 		face_detail_chin_cleft={ "chin_cleft" 0 "chin_cleft" 0 }
 		face_detail_chin_def={ "chin_def" 60 "chin_def" 60 }
 		face_detail_eye_lower_lid_def={ "eye_lower_lid_def" 140 "eye_lower_lid_def" 140 }
 		face_detail_eye_socket={ "eye_socket_01" 58 "eye_socket_01" 58 }
 		face_detail_nasolabial={ "nasolabial_03" 132 "nasolabial_03" 132 }
 		face_detail_nose_ridge_def={ "nose_ridge_def_pos" 69 "nose_ridge_def_pos" 69 }
 		face_detail_nose_tip_def={ "nose_tip_def" 227 "nose_tip_def" 227 }
 		face_detail_temple_def={ "temple_def" 187 "temple_def" 187 }
 		expression_brow_wrinkles={ "brow_wrinkles_04" 233 "brow_wrinkles_04" 233 }
 		expression_eye_wrinkles={ "eye_wrinkles_02" 108 "eye_wrinkles_02" 108 }
 		expression_forehead_wrinkles={ "forehead_wrinkles_01" 12 "forehead_wrinkles_01" 12 }
 		expression_other={ "cheek_wrinkles_both_01" 59 "cheek_wrinkles_both_01" 59 }
 		complexion={ "complexion_5" 181 "complexion_5" 181 }
 		gene_height={ "normal_height" 176 "normal_height" 176 }
 		gene_bs_body_type={ "body_fat_head_fat_low" 85 "body_fat_head_fat_low" 85 }
 		gene_bs_body_shape={ "body_shape_average_clothed" 121 "body_shape_triangle_half" 70 }
 		gene_bs_bust={ "bust_clothes" 180 "bust_default" 180 }
 		gene_age={ "old_3" 99 "old_3" 99 }
 		gene_eyebrows_shape={ "no_eyebrows" 181 "no_eyebrows" 181 }
 		gene_eyebrows_fullness={ "no_eyebrows" 161 "no_eyebrows" 161 }
 		gene_body_hair={ "body_hair_sparse" 0 "body_hair_sparse" 0 }
 		hairstyles={ "high_elven_hairstyles" 107 "high_elven_hairstyles" 107 }
 		beards={ "night_elven_beards" 218 "night_elven_beards" 218 }
 		eye_accessory={ "normal_eyes" 222 "normal_eyes" 222 }
 		teeth_accessory={ "normal_teeth" 0 "normal_teeth" 0 }
 		eyelashes_accessory={ "normal_eyelashes" 190 "normal_eyelashes" 190 }
 		gene_bs_ear_lenght={ "floppy_ear_length" 230 "floppy_ear_length" 230 }
 		special_eyebrows={ "night_elven_eyebrows" 174 "night_elven_eyebrows" 174 }
 		special_eyes={ "magic_eyes" 74 "magic_eyes" 74 }
 		gene_bs_mouth_tusks={ "mouth_fangs" 0 "mouth_fangs" 0 }
 		static_tusks={ "no_static_tusks" 0 "no_static_tusks" 0 }
 		gene_bs_ear_tip={ "ear_tip_pos" 0 "ear_tip_pos" 0 }
 		gene_bs_fingers={ "fingers_troll" 0 "fingers_troll" 0 }
 		clothes={ "western_bedchamber" 100 "most_clothes" 0 }
 }
	entity={ 0 0 }
}
```

</details>
One more. I think it's a too flat nose.
<details>
<summary>Preview</summary>

image

</details>
<details>
<summary>Genes</summary>

```
ruler_designer_2290215506={
	type=female
	id=0
	genes={ 		hair_color={ 182 96 182 96 }
 		skin_color={ 221 67 221 67 }
 		eye_color={ 162 100 162 100 }
 		gene_chin_forward={ "chin_forward_neg" 157 "chin_forward_neg" 157 }
 		gene_chin_height={ "chin_height_pos" 168 "chin_height_pos" 168 }
 		gene_chin_width={ "chin_width_neg" 140 "chin_width_neg" 140 }
 		gene_eye_angle={ "eye_angle_neg" 169 "eye_angle_neg" 169 }
 		gene_eye_depth={ "eye_depth_neg" 102 "eye_depth_neg" 102 }
 		gene_eye_height={ "eye_height_neg" 127 "eye_height_neg" 127 }
 		gene_eye_distance={ "eye_distance_neg" 134 "eye_distance_neg" 134 }
 		gene_eye_shut={ "eye_shut_neg" 119 "eye_shut_neg" 119 }
 		gene_forehead_angle={ "forehead_angle_neg" 82 "forehead_angle_neg" 82 }
 		gene_forehead_brow_height={ "forehead_brow_height_neg" 162 "forehead_brow_height_neg" 162 }
 		gene_forehead_roundness={ "forehead_roundness_neg" 144 "forehead_roundness_neg" 144 }
 		gene_forehead_width={ "forehead_width_neg" 228 "forehead_width_neg" 228 }
 		gene_forehead_height={ "forehead_height_neg" 104 "forehead_height_neg" 104 }
 		gene_head_height={ "head_height_neg" 173 "head_height_neg" 173 }
 		gene_head_width={ "head_width_neg" 100 "head_width_neg" 100 }
 		gene_head_profile={ "head_profile_neg" 54 "head_profile_neg" 54 }
 		gene_head_top_height={ "head_top_height_neg" 74 "head_top_height_neg" 74 }
 		gene_head_top_width={ "head_top_width_neg" 139 "head_top_width_neg" 139 }
 		gene_jaw_angle={ "jaw_angle_neg" 108 "jaw_angle_neg" 108 }
 		gene_jaw_forward={ "jaw_forward_neg" 118 "jaw_forward_neg" 118 }
 		gene_jaw_height={ "jaw_height_neg" 80 "jaw_height_neg" 80 }
 		gene_jaw_width={ "jaw_width_pos" 120 "jaw_width_pos" 120 }
 		gene_mouth_corner_depth={ "mouth_corner_depth_pos" 177 "mouth_corner_depth_pos" 177 }
 		gene_mouth_corner_height={ "mouth_corner_height_neg" 81 "mouth_corner_height_neg" 81 }
 		gene_mouth_forward={ "mouth_forward_neg" 89 "mouth_forward_neg" 89 }
 		gene_mouth_height={ "mouth_height_neg" 77 "mouth_height_neg" 77 }
 		gene_mouth_width={ "mouth_width_neg" 162 "mouth_width_neg" 162 }
 		gene_mouth_upper_lip_size={ "mouth_upper_lip_size_neg" 117 "mouth_upper_lip_size_neg" 117 }
 		gene_mouth_lower_lip_size={ "mouth_lower_lip_size_neg" 150 "mouth_lower_lip_size_neg" 150 }
 		gene_mouth_open={ "mouth_open_pos" 0 "mouth_open_pos" 0 }
 		gene_neck_length={ "neck_length_neg" 128 "neck_length_neg" 128 }
 		gene_neck_width={ "neck_width_pos" 62 "neck_width_pos" 62 }
 		gene_bs_cheek_forward={ "cheek_forward_pos" 15 "cheek_forward_pos" 15 }
 		gene_bs_cheek_height={ "cheek_height_pos" 195 "cheek_height_pos" 195 }
 		gene_bs_cheek_width={ "cheek_width_pos" 31 "cheek_width_pos" 31 }
 		gene_bs_ear_angle={ "ear_angle_neg" 0 "ear_angle_neg" 0 }
 		gene_bs_ear_inner_shape={ "ear_inner_shape_pos" 249 "ear_inner_shape_pos" 249 }
 		gene_bs_ear_bend={ "ear_both_bend_pos" 120 "ear_both_bend_pos" 120 }
 		gene_bs_ear_outward={ "ear_outward_pos" 54 "ear_outward_pos" 54 }
 		gene_bs_ear_size={ "ear_size_pos" 54 "ear_size_pos" 54 }
 		gene_bs_eye_corner_depth={ "eye_corner_depth_neg" 129 "eye_corner_depth_neg" 129 }
 		gene_bs_eye_fold_shape={ "eye_fold_shape_pos" 206 "eye_fold_shape_pos" 206 }
 		gene_bs_eye_size={ "eye_size_pos" 62 "eye_size_pos" 62 }
 		gene_bs_eye_upper_lid_size={ "eye_upper_lid_size_pos" 0 "eye_upper_lid_size_pos" 0 }
 		gene_bs_forehead_brow_curve={ "forehead_brow_curve_pos" 59 "forehead_brow_curve_pos" 59 }
 		gene_bs_forehead_brow_forward={ "forehead_brow_forward_pos" 41 "forehead_brow_forward_pos" 41 }
 		gene_bs_forehead_brow_inner_height={ "forehead_brow_inner_height_neg" 75 "forehead_brow_inner_height_neg" 75 }
 		gene_bs_forehead_brow_outer_height={ "forehead_brow_outer_height_pos" 102 "forehead_brow_outer_height_pos" 102 }
 		gene_bs_forehead_brow_width={ "forehead_brow_width_pos" 229 "forehead_brow_width_pos" 229 }
 		gene_bs_jaw_def={ "jaw_def_pos" 27 "jaw_def_pos" 27 }
 		gene_bs_mouth_lower_lip_def={ "mouth_lower_lip_def_pos" 211 "mouth_lower_lip_def_pos" 211 }
 		gene_bs_mouth_lower_lip_full={ "mouth_lower_lip_full_pos" 35 "mouth_lower_lip_full_pos" 35 }
 		gene_bs_mouth_lower_lip_pad={ "mouth_lower_lip_pad_pos" 89 "mouth_lower_lip_pad_pos" 89 }
 		gene_bs_mouth_lower_lip_width={ "mouth_lower_lip_width_neg" 106 "mouth_lower_lip_width_neg" 106 }
 		gene_bs_mouth_philtrum_def={ "mouth_philtrum_def_pos" 59 "mouth_philtrum_def_pos" 59 }
 		gene_bs_mouth_philtrum_shape={ "mouth_philtrum_shape_pos" 106 "mouth_philtrum_shape_pos" 106 }
 		gene_bs_mouth_philtrum_width={ "mouth_philtrum_width_pos" 170 "mouth_philtrum_width_pos" 170 }
 		gene_bs_mouth_upper_lip_def={ "mouth_upper_lip_def_pos" 75 "mouth_upper_lip_def_pos" 75 }
 		gene_bs_mouth_upper_lip_full={ "mouth_upper_lip_full_neg" 192 "mouth_upper_lip_full_neg" 192 }
 		gene_bs_mouth_upper_lip_profile={ "mouth_upper_lip_profile_neg" 66 "mouth_upper_lip_profile_neg" 66 }
 		gene_bs_mouth_upper_lip_width={ "mouth_upper_lip_width_neg" 18 "mouth_upper_lip_width_neg" 18 }
 		gene_bs_nose_forward={ "nose_forward_pos" 64 "nose_forward_pos" 64 }
 		gene_bs_nose_height={ "nose_height_neg" 138 "nose_height_neg" 138 }
 		gene_bs_nose_length={ "nose_length_neg" 119 "nose_length_neg" 119 }
 		gene_bs_nose_nostril_height={ "nose_nostril_height_neg" 5 "nose_nostril_height_neg" 5 }
 		gene_bs_nose_nostril_width={ "nose_nostril_width_pos" 32 "nose_nostril_width_pos" 32 }
 		gene_bs_nose_profile={ "nose_profile_hawk_pos" 78 "nose_profile_hawk_pos" 78 }
 		gene_bs_nose_ridge_angle={ "nose_ridge_angle_pos" 39 "nose_ridge_angle_pos" 39 }
 		gene_bs_nose_ridge_width={ "nose_ridge_width_neg" 88 "nose_ridge_width_neg" 88 }
 		gene_bs_nose_size={ "nose_size_pos" 21 "nose_size_pos" 21 }
 		gene_bs_nose_tip_angle={ "nose_tip_angle_neg" 115 "nose_tip_angle_neg" 115 }
 		gene_bs_nose_tip_forward={ "nose_tip_forward_pos" 69 "nose_tip_forward_pos" 69 }
 		gene_bs_nose_tip_width={ "nose_tip_width_neg" 41 "nose_tip_width_neg" 41 }
 		face_detail_cheek_def={ "cheek_def_01" 157 "cheek_def_01" 157 }
 		face_detail_cheek_fat={ "cheek_fat_02_pos" 19 "cheek_fat_02_pos" 19 }
 		face_detail_chin_cleft={ "chin_cleft" 0 "chin_cleft" 0 }
 		face_detail_chin_def={ "chin_def" 135 "chin_def" 135 }
 		face_detail_eye_lower_lid_def={ "eye_lower_lid_def" 29 "eye_lower_lid_def" 29 }
 		face_detail_eye_socket={ "eye_socket_03" 46 "eye_socket_03" 46 }
 		face_detail_nasolabial={ "nasolabial_01" 102 "nasolabial_01" 102 }
 		face_detail_nose_ridge_def={ "nose_ridge_def_neg" 216 "nose_ridge_def_neg" 216 }
 		face_detail_nose_tip_def={ "nose_tip_def" 73 "nose_tip_def" 73 }
 		face_detail_temple_def={ "temple_def" 184 "temple_def" 184 }
 		expression_brow_wrinkles={ "brow_wrinkles_01" 106 "brow_wrinkles_01" 106 }
 		expression_eye_wrinkles={ "eye_wrinkles_01" 254 "eye_wrinkles_01" 254 }
 		expression_forehead_wrinkles={ "forehead_wrinkles_02" 14 "forehead_wrinkles_02" 14 }
 		expression_other={ "cheek_wrinkles_both_01" 22 "cheek_wrinkles_both_01" 22 }
 		complexion={ "complexion_5" 55 "complexion_5" 55 }
 		gene_height={ "normal_height" 154 "normal_height" 154 }
 		gene_bs_body_type={ "body_fat_head_fat_low" 106 "body_fat_head_fat_low" 106 }
 		gene_bs_body_shape={ "body_shape_average_clothed" 80 "body_shape_triangle_half" 29 }
 		gene_bs_bust={ "bust_clothes" 113 "bust_shape_1_full" 113 }
 		gene_age={ "old_4" 16 "old_4" 16 }
 		gene_eyebrows_shape={ "no_eyebrows" 56 "no_eyebrows" 56 }
 		gene_eyebrows_fullness={ "no_eyebrows" 81 "no_eyebrows" 81 }
 		gene_body_hair={ "body_hair_sparse" 0 "body_hair_sparse" 0 }
 		hairstyles={ "high_elven_hairstyles" 155 "high_elven_hairstyles" 155 }
 		beards={ "night_elven_beards" 5 "night_elven_beards" 5 }
 		eye_accessory={ "normal_eyes" 210 "normal_eyes" 210 }
 		teeth_accessory={ "normal_teeth" 0 "normal_teeth" 0 }
 		eyelashes_accessory={ "normal_eyelashes" 100 "normal_eyelashes" 100 }
 		gene_bs_ear_lenght={ "floppy_ear_length" 225 "floppy_ear_length" 225 }
 		special_eyebrows={ "night_elven_eyebrows" 58 "night_elven_eyebrows" 58 }
 		special_eyes={ "magic_eyes" 202 "magic_eyes" 202 }
 		gene_bs_mouth_tusks={ "mouth_fangs" 0 "mouth_fangs" 0 }
 		static_tusks={ "no_static_tusks" 0 "no_static_tusks" 0 }
 		gene_bs_ear_tip={ "ear_tip_pos" 0 "ear_tip_pos" 0 }
 		gene_bs_fingers={ "fingers_troll" 0 "fingers_troll" 0 }
 		clothes={ "western_bedchamber" 100 "most_clothes" 0 }
 }
	entity={ 0 0 }
}
```

</details>

**Comment by ercarp** [comment]
> Mostly they're fine, but I generated a really spooky face.

Addressed these problems in 92eaa0ce8d8ce29e02cc396c45bad6164c7ef43f. The game _should_ no longer generate that many spooky-looking elves. The drawback is that male night elves will look a bit more feminine.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Comment by ercarp** [comment]
Changed base branch directly to `master` as the Night Elves use caucasian as a template.

**Review by TheDrPibb1999 — APPROVED** [review]
I did about 200 random gens of each sex and of each of the reworks, I think they look amazing and I did not see any of those spooky faces mentioned by earlier reviews. I did notice that very very rarely my night elf would be randomly gened with the gold/amber eyes, which I think is an amazing feature as the lore states night elves born with this color are "destined for greatness" or alined with druidic powers, awesome little touch. Same for the highborn rework, great all around. great work ercarp once more :)

**Review by zumbak04 — APPROVED** [review]
Can be merged.

**Pull request merged**
