### PR TITLE
No Randomly Generated Families for Lore-Important Characters

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Added exceptions to certain lore-important characters to no longer generate random families at the start of a game.

**Full list of included characters**:

<details><summary>Click to expand</summary>

                    ## Humans
			AND = {
				exists = character:60036
				this = character:60036 # Uther the Lightbringer
			}
			AND = {
				exists = character:48435
				this = character:48435 # Priscilla Ashvane
			}
			AND = {
				exists = character:59000
				this = character:59000 # Archmage Antonidas
			}
			AND = {
				exists = character:5000
				this = character:5000 # Medivh
			}
			AND = {
				exists = character:60014
				this = character:60014 # Tirion Fordring
			}
			AND = {
				exists = character:38002
				this = character:38002 # Galen Trollbane
			}
			AND = {
				exists = character:46100
				this = character:46100 # Arugal
			}
			
			
			## Orcs & Ogres
			
			AND = {
				exists = character:10021
				this = character:10021 # Go'el/Thrall
			}
			AND = {
				exists = character:10005
				this = character:10005 # Kilrogg
			}
			AND = {
				exists = character:52000
				this = character:52000 # Cho'gall
			}
			AND = {
				exists = character:10015
				this = character:10015 # Gul'dan
			}
			AND = {
				exists = character:10050
				this = character:10050 # Orgrim
			}
			AND = {
				exists = character:10002
				this = character:10002 # Dal'rend Blackhand
			}
			AND = {
				exists = character:10100
				this = character:10100 # Drek'thar
			}
			AND = {
				exists = character:10656
				this = character:10656 # Rehgar Earthfury
			}
			
			
			## Dwarves
			AND = {
				exists = character:12002
				this = character:12002 # Dagran Thaurissan
			}
			AND = {
				exists = character:22001
				this = character:22001 # Falstad Wildhammer
			}
			
			
			## Night Elves
			AND = {
				exists = character:340018
				this = character:340018 # Fandral Staghelm
			}
			AND = {
				exists = character:340003
				this = character:340003 # Tyrande (Theocracy)
			}
			AND = {
				exists = character:340100
				this = character:340100 # Shandris Feathermoon
			}
			
			
			## High Elves/Blood Elves
			AND = {
				exists = character:42077
				this = character:42077 # Halduron Brightwing (minor-ish character, maybe generated family is okay)
			}
			AND = {
				exists = character:42078
				this = character:42078 # Dar'Khan Drathir (minor-ish character, maybe generated family is okay)
			}
			AND = {
				exists = character:42304
				this = character:42304 # Grand Magister Belo'vir
			}
			AND = {
				exists = character:42075
				this = character:42075 # Lor'themar Theron
			}
			AND = {
				exists = character:42306
				this = character:42306 # Grand Magister Rommath
			}
			AND = {
				exists = character:42003
				this = character:42003 # Kael'thas Sunstrider
			}
			
			
			## Dragons/Draconic
			AND = {
				exists = character:62202
				this = character:62202 # Nefarian (Theocracy)
			}
			AND = {
				exists = character:62203
				this = character:62203 # Onyxia
			}
			AND = {
				exists = character:62400
				this = character:62400 # Alexstrasza (Theocracy)
			}
			AND = {
				exists = character:62401
				this = character:62401 # Korialstrasz (Theocracy)
			}
			
			
			## Trolls
			AND = {
				exists = character:57000
				this = character:57000 # Zul'jin
			}
			AND = {
				exists = character:68001
				this = character:68001 # Vol'jin
			}
			
			## Demons
			AND = {
				exists = character:430400
				this = character:430400 # Balnazzar
			}
			AND = {
				exists = character:360000
				this = character:360000 # Kazzak
			}
			
			## Undead
			AND = {
				exists = character:5806
				this = character:5806 # Moroes
			}
			AND = {
				exists = character:10014
				this = character:10014 # Ner'zhul (the Lich, not the Orc)
			}

</details>

## What does this mean?

Normally, **ruler characters** without any pre-existing children will have random families generated for them when the game starts. Think someone like Medivh or Uther. We don't know of them having any children, they appear as rulers in some bookmarks, and so the game would normally spawn them in with a spouse and some children.

Adding them to this list ensures they will not have spouses or children generated in any bookmark in which they appear as rulers. Additionally, Scourge characters will not generate families by default either, so they do not need to be added (unless they appear as non-Scourge rulers in earlier bookmarks).

# How to test:
- Make suggestions on characters that should be either added to or removed from this list of exceptions.

To look for applicable characters, start the game with [Debug Mode](https://ck3.paradoxwikis.com/Console_commands#Debug_mode) on and use the Character Finder to find lore-important rulers with children that **do not** have a Historical ID (this means they were generated by the game).

**Note**: We do not want to add every lore character to this list of exceptions. With most minor lore characters and NPCs, we **_want_** them to have randomly generated families.

### CODE REVIEW

**Comment by TheDrPibb1999** [comment]
Sylvanas Windrunner could be added

**Comment by TheDrPibb1999** [comment]
as well as alleria windrunner, all never had kids

**Comment by ercarp** [comment]
> 
> 
> Sylvanas Windrunner could be added



> 
> 
> as well as alleria windrunner, all never had kids

Neither Alleria nor Sylvanas currently appear as rulers in any of the bookmarks, with the exception of Sylvanas being a ruler in the Third War bookmark — but presumably because since she's undead, the game doesn't generate a spouse or children for her. I've added some clarifications to the main post.

<details><summary>Click to expand</summary>

image

</details>

**Comment by MemeWizard** [comment]
> Added exceptions to certain lore-important characters to no longer generate random families at the start of a game.

I suggest you to create a new gamerule and make it default then.

**Comment by ercarp** [comment]
> 
> 
> > Added exceptions to certain lore-important characters to no longer generate random families at the start of a game.
> 
> I suggest you to create a new gamerule and make it default then.

We don't really want that though. The minor lore characters outnumber the important ones by a large margin, and we still want most of them to generate random families. I've already added exceptions for most (if not all) of the major lore characters in `game_rule_events.txt`.

If we were to do it the opposite way with a custom game rule and have every historical character spawn without a generated family, it would take a lot more effort to go through and make an exception for the minor lore characters. It would be completely backwards.

Feel free to elaborate on your suggestion if I'm misunderstanding something.

**Comment by MemeWizard** [comment]
> If we were to do it the opposite way with a custom game rule and have every historical character spawn without a generated family, it would take a lot more effort to go through and make an exception for the minor lore characters. It would be completely backwards.

No-no-no-no-no, why do we ever need to do that

> Feel free to elaborate on your suggestion if I'm misunderstanding something.

Add game rule that block important lore characters from having a generated family and make it default?
Just like how `on_generate_families_ai_only` blocks player from having a generated family, add a new one that's blocks important lore characters from having a generated family.

**Comment by ercarp** [comment]
> Add game rule that block important lore characters from having a generated family and make it default?
> Just like how `on_generate_families_ai_only` blocks player from having a generated family, add a new one that's blocks important lore characters from having a generated family.

You do realize we would still have to go and assign some sort of flag to these important lore characters so the game rule recognizes them as such? So the workload would be the same, if not _more so_ since we'd have to create a custom game rule instead of using what Paradox has already built into the game.

This is all pretty standard practice for any full conversion mod.

**Comment by MemeWizard** [comment]
> You do realize <...>

I realized that you don't understand what I'm talking about and it will be easier to show than to explain
I added that gamerule in #186 - check it

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
