### PR TITLE
Death Perks

### PR DESCRIPTION
**Pull request by robmart**
## Changelog:
- Added 17 Necromantic Perks:
  - Frost Presence: Give access to Frost elemental tree. Can give Frost Fever with Give Disease.
  - Death Aura: Increase the amount of casualties your enemies take in battle by 10%
  - Eternal Suffering: New torture events, torturing someone will give them higher prowess if you resurrect them. Can create Banshees with Raise Dead.
  - Death Pact: You and your Knights with the Undead Infusion gain increased mana generation when one of your Knights dies in battle
  - Fleshcrafting: Increase the stats of all your undead. Can create Abominations with Raise Dead.
  - Anti-Magic Barrier: Slightly increase overall magic resistance. Scales based on Magic Conductivity and Intrigue or Learning, whichever is higher.
  - Rotten Lands: Can create Ghouls with Raise Dead.
  - Death's Advance: Your knights with the Undead being trait gain +5 prowess. Increase your army speed by 10%.
  - Unholy Ground: You gain 0.01 mana conductivity per 5 counties with Death Corruption, capped to 0.05. Can give Crypt Fever with Give Disease.
  - Necrosis: Your plagues now have chances of causing permanent injuries. This includes epidemics from the Epidemic spell.
  - Blood Presence: Health Bonus, and Increase your mana conductivity.
  - Blood Boil: Can give Blood Plague with Give Disease.
  - Blood Siphon: Killing an enemy in battle has a chance to remove a non-magical injury
  - Vampiric Aura: Decrease your chances to be injured in battles by a lot. Increase scheme resistance. Can create vampires with Raise Dead.
  - Blood Gorged: Being injured or having a bad health increase your mana conductivity by a lot.
  - Mark of Blood: Small random chance to give enemies Advantage or Prowess debuffs in battle
  - Supernatural Beauty: Gain 5 attraction opinion, 1 max seduction scheme and -5 seduction scheme phase duration, -10 scheme phase duration against lovers

## Developer changelog:
- Added this thing.
- Changed that thing.
- 
## TODO:
- [ ] Banshee, Ghoul, Vampire, Revenant trait modifiers and balancing
- [ ] Epidemic traits balancing
- [ ] Epidemic modifiers

## Art TODO:
- [ ] Abomination 3D static model
- [ ] Banshee appearance
- [ ] Ghoul 3D static model
- [ ] Vampire appearance
- [ ] Vampire trait icon
- [ ] Revenant trait icon
- [ ] Frost Fever trait icon
- [ ] Crypt Fever trait icon
- [ ] Blood Plague trait icon
- [ ] Death ritual icons

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:

### CODE REVIEW

**Comment by Rimaka94** [comment]
## Test Criteria
:x: Check that Necromancy **perks** are working as their Descriptions state.

_Marks:_
✅ - working as expected
❌ - not working as expected
⚠️ - was unable to confirm if working as expected, needs more testing/confirmation
🔶 - may or may not be an issue, noted for your discretion

Note: I was not supposed to review perks yet, apologies. Dropping these notes here even though they aren't finished in case it helps at all.

## In-depth Testing
### 🧟 Reanimator Branch
- ✅ _Frost Presence_ properly allows access to the Cryomancer tree.
- ⚠️ _Death Aura_ may be working properly, uncertain how to confirm if modifier is applied.
- ❌ _Eternal Suffering_ Seems to have a chance to give +1 to a pool which gives X amount of prowess upon being raised, however, the target does not ever gain any extra prowess from this upon being raised, after being executed. This may not be properly adding to the pool, or it may not be accessing it upon being raised.
  - 🔶 The description text for Torture's event is **sometimes** empty, see screenshot. I am unsure if this is due to this perk, or another issue.
  - ❌ Does not state that it allows you to be able to raise Banshees in perk description.

<details>
<summary>[SCREENSHOTS] Eternal Suffering torture event localization</summary>

image
image
</details>

- ❌ _Death Pact_ does not seem to be working. I was unable to get this to trigger on me and my knights when one of my other knights died in battle, after multiple attempts.
- ✅ _Fleshcrafting_ appears to be properly increasing the Base skills to raised undead.
  - ❌ Does not state that it allows you to be able to raise Abominations in perk description.

### 💀 Deathbringer Branch
- ✅ _Anti-Magic Barrier_ is properly adding scaling magic resistance.
  - 🔶 My feedback: This seems to be really difficult to get even a single point of magic resistance.
- ✅ _Death's Advance_ properly gives +5 prowess to your Knights, and is removed when they are no longer your Knight. Army movement speed properly applied.
- ✅ _Unholy Ground_ is properly giving +1% mana conductivity per every 5 counties with Death Corruption.
- 🔶 **Perk 8** missing.

### 🩸 Hematurge Branch
- ✅ _Blood Presence_ properly adds health boost/mana conductivity.
- ⚠️ Unsure if _Blood Siphon_ working properly, was unable to get this to trigger in a number of battles possibly due to the strict requirement. My character did not seem to ever be involved in personally killing any knights which is likely why, but my knights did under my character as Commander, and did not seem to trigger at all while my character was Maimed, and sometimes Wounded.
- ✅ _Vampiric Aura_ properly gives scheme resistance, but I'm assuming the less-chance-to-be-wounded is working as well as this is difficult to test.
- ✅ _Blood Gorged_ properly increases Mana Conductivity when injured.
- ✅ _Mark of Blood_ properly has a chance to apply Mark of Blood modifier for 30 days to enemy knights, after fighting.
- 🔶 **Perk 8** missing.

**Review by Rimaka94 — COMMENTED** [review]
## Test Criteria
🔶 Check that Necromancy **perks** are working as their Descriptions state.
_There's nothing here in my opinion that seems broken that should stop you from merging except **possibly** Blood Siphon. However, there were some other things I was uncertain of how to fully confirm in-game as well as some functionality that may or may not be working as expected that I've noted for you._

_Marks:_
✅ - working as expected
❌ - not working as expected
⚠️ - was unable to confirm if working as expected, needs more testing/confirmation
🔶 - may or may not be an issue, noted for your discretion


## In-depth Testing
### 🧟 Reanimator Branch
- ✅ **Frost Presence:** Properly gives access to the Cryomancer tree when character has an Arcane lifestyle focus.
- ⚠️ **Death Aura:** Uncertain how to confirm this is working in-game, assuming the +10% Fatal Casualties bonus is applied properly as perk describes.
- ⚠️ **Eternal Suffering:** Variable properly stacks up when torturing, but when the target is raised, I'm not certain if prowess is being applied. A character with +2 in the pool for example when raised went from a Base 5 prowess to Base 6, rather than the expected 7. I believe this is due to raised characters getting a brand new Base prowess value unrelated to the original character, as a character raised with 0 in the pool can still have a different Base prowess value on the new character.
  - 🔶 When torturing a target that already has +5, you can still get a message saying they'll get +1 Prowess. However, it properly does not add more than +5 to the pool.
  - 🔶 When raising a target that has not been tortured, you'll still see 'Prowess increases by 0' in the tooltip when using Raise Dead. Not necessarily an issue.
- ✅ **Death Pact:** Properly gives you and your Undead Knights +20% Mana Regen character modifier when a friendly Undead knight dies in battle.
- **Fleshcrafting:** Raised characters are properly giving the Fleshcrafted character modifier upon being raised.

### 💀 Deathbringer Branch
- ✅ **Anti-Magic Barrier:** Properly increases magic resistances scaling on Intrigue or Learning + Mana Conductivity.
- 🔶 **Death's Advance:** 10% army movement speed properly applied. Properly applies +5 Prowess to Undead Knights you have. However, this bonus does not go away when the character is no longer your knight in your court. The bonus does go away when the character leaves your court.
- ✅ **Unholy Ground:** Properly gives 1% Mana Conductivity per 5 counties with Death Corruption.
- ✅ **Necrosis:** Properly gives a 10% chance to apply Wounded when using Give Disease on target.

### 🩸 Hematurge Branch
- ✅ **Blood Presence:** Confirmed the health bonus applies, and Mana Conductivity bonus properly applies.
- ⚠️ **Blood Siphon:** I was not able to confirm if this is working properly. I tested with two individual knights in my army, Immortal + wounded_2, and fought multiple fights with the perk unlocked. After ~10 kills on each knight in fights, neither successfully healed wounded_2.
- ⚠️ **Vampiric Aura:** Confirmed hostile's scheme initial success chance -20% working properly. I am uncertain of the best way to confirm the -50% injury chance in battle however.
- 🔶 **Blood Gorged:** Properly gives bonus to Mana Conductivity when you have any type of injury and at "Near death" health status. Does not give at the "Poor health" stage, but this might be intended.
- ✅ **Mark of Blood:** Properly has a chance to apply debuff to enemy knights. No issues with localization.
- ✅ **Supernatural Beauty:** Correctly applies attraction opinion+, scheme phase length reduction works correctly vs Lovers, correctly gives +1 max seduction schemes, correctly gives phase length reduction for seduction schemes

**Review by Rimaka94 — APPROVED** [review]
Per comments in discord channel

- dummy faith/culture are properly hidden, have not found a way to get them to show up in game unexpectedly
- properly can no longer raise characters with the Undead trait / Titanforged classification
- all previously reported issues have been resolved or explained
- no new issues to report since the latest changes following implementation of the dummy culture/faith

approved from my in-game testing pov

**Comment by FelModder** [comment]
I'm Late to the party of Reviewing this Perk Tree but since i have done it here's a short review of the features:

### Reanimator Branch: ✅
- Everything in this branch is working perfectly and is fairly balanced.

### Deathbringer Branch: ✅
- **Anti-Magic Barrier:** Working as intended but needs a buff since it barely is increasing any resistance.
- **Unholy Ground:** Working as intended but needs to mention if it is capped to only 1% for five counties you hold or will it increase by another 1% if you hold 10 counties. _Crypt Fever_ works with the _Give Disease Spell_.
- Rest of the spells and perks from the branch are working perfectly and is fairly balanced.

### Hematurge Branch: ✅
- **Blood Siphon:** Didn't find a way to be able to confirm if it was working properly.
- Rest of the spells and perks from the branch are working perfectly and is fairly balanced.

**Pull request merged**
