### PR TITLE
Hammer of twilight

### PR DESCRIPTION
**Pull request by sejtalk**
## Changelog:
- [x] Added Hammer of Twilight artifact.

- [x] Added icon for it

- [ ] Removed the event that adds it to onyxia for testing purposes

Balancing Spreadsheet:
https://docs.google.com/spreadsheets/d/18zS-FAte6nsejx7rpzSmVuioRXps3iWSvSkx_xRJSWI/edit#gid=1165316868

# How to test:
Select Onyxia that rules the duchy of Wyrmborg and check that she has the artifact

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
583 start is crashing the game. Error logs:
[error.log](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/10046824/error.log)

**Comment by sejtalk** [comment]
> 583 start is crashing the game. Error logs: [error.log](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/10046824/error.log)

It's because it's based on [1.5.0-preview-adaptation](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/1.5.0-preview-adaptation) which crashes in 583 start

**Comment by arithon** [comment]
looks good to me :)

**Review by arithon — APPROVED** [review]
looks good to me

**Review by TheGroxEmpire — APPROVED** [review]
Looks good then. The artifact is in the game and with appropriate stats.

**Pull request merged**
