### PR TITLE
Mantid Names

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Mantids don't use nerubian names anymore.
<details>
<summary>Males</summary>

```
A'duz A'haso Allin'ha Ar Ar'ak Ar'i Asse'tha Avaxe Ax Ax'ierret
Axazak Axxalthok Axxul'zun Ayyakkik Az Azzezi El'thisi Erol've Exarran Ezzex
Gal'vik Gan'bak Ganik Gavvith Gayyath Gekorrik Gi'da Gikze Girraruk
Githul'jil Gizok'ik Gol'tal Haz'rak Hazop'tak Helthas Hethesil
Hizzethin Hokarra I'vil Ik'tharrak Ikkorrax Ikur'ret Il'juther Ilthin
Inokzim Irrarras It'ek Ithi Ivoxik Ixi'hol Iz'raruk Ja'ze Jal'ler Jaz'tim
Jazik'al Jevvekkith Jixulox Ki'tharrin Kil'vakik Kin'buxim Kla Klakza Klalir'ris
Klarrak'tem Klet'kak Klet'te Klethi'jam Kli Kli'zik Klin Kloz'raz Krathunam
Krek'vath Kro'hox Krolak Krul'risex Kza'yaz Kzi'das Kzikkikkis Kzil'ra Kzit
Kzukazzak Kzup'tith Larrathak Lekza Li'kinis Likkixik Lirozit Lix'ith Lokivik
Lor'lo Lul'rek Luyyix Manathik Marun'bal Masakze Maxxil'jok Milthil
Mit'toxak Monil'tim Movvik Mozan'bo Mu'dezzok Nak Nal Nan'bil Naxarus Nazzi Ni
Nu Nu'thi O'di Ot'ki Ozzal Pat'akka Pil'lazzot Pil'za Pit'ex Pithaxxil
Pix Qa'rik Qal'lis Qalthukkith Qathek Qelukkir Qeyyik Qi'razza Qik
Qixxisuz Quk'vivot Rakkunak Ral'kith Ral'zet Rek'hana Rik Rik'ta Rozzeevat
Ruvit'ko Saviri Sazza'vo Sekexoth Sezi'mi Shas Shek Shi'kim Shi'zuk Shil'zik
Shizirik Sho Shorru'zix Shovavum Sik'thikim Sizuvuk Ska'juxxat Ska'zithak
Skanol'rak Skarasa Skix Skizisam Skoyye Skuvikkiz Sosu'yos Sra'vi Srak'thalal
Srar'lo Srasesut Srena'jin Sri'zir Srurali Sruthixxol Ta'rak Ta'vaz That'ha
Thos'ha Til'thathi Tila'jok Tzak'tak Tzathat Tze'hak Tzeyyixik Tzez'rer Tziz
Tzuk'thir Uluth Up'tux Urrak'thik Uz'rat Vanak'im Varalo Vel'lak Vo'thaz
Xal'tukkak Xat'zeth Xex'i Xi Xik Xilthux Xot'kaz Xoz'tik Xut'on Za'harak Zak
Zan'sarrak Zavessa Zil'thuthik Zilo Zizzur'lik Zolavul Zulin
```

</details>
<details>
<summary>Females</summary>

```
A'thi A'ze A'ziezzal Ak'at Ak'ves Al'hiesh Alal'thier An'ze An'zil Aneer'ver
Ar'hi Ar'thir At'zier Ath'a Ath're Av'heshee Av'i Callith'rish
Cassish'ri Cek'her Cel'zee Ces'hee Cetesh'ith Ceth'ri Cil'zathie Cot'ze E'ha
El'zath El'zir Eleza Er'ene Esat'zet Esavas Ev'haz Ev'hiesesh Ex'irriel Hak'ath
Harrev'et Hat'zaz Hatesi Hav'eerraz Hek'vez Herak'ish Het'atel Ir'vinet Irek'zith
Is'alez Ise'thesh Ish'vie Itha Jannat'az Jar'et Jar'thierriz Jas'ishesh Jav'hiella
Javerre Jeles'ir Jerrex'ieth Jes'her Jes'hiesez Jeseshaz Ji'hesh Jil've
Jithiser Jot'ash Lak'zeli Lash'veniz Lash'viereel Lashar'vet Le'zet
Lek'vith Lelal'vesh Ler'hanee Leth'ithar Lolir'he Mat'hazzi
Meth'rassez Methiv'ha Mevizzez Mol'va Mosh'eet Nazalar
Neler'ha Ner'va Ner'veesees Ner'zeza Neth'ath Nik'ha Nor'he Ok'zeez Olash'ver
Ot'heel Ot'ziel Otar'hath Oth'veezzer Qar'e Qash'var Qathith're Qek've Qel'ha
Qel'vi Qen'halleeth Qenesee Qer'that Qeshar Qesit'ze Qireti Qossath'rie Rak'zessas
Ralik'zez Rannak'va Rar'zaseeth Rasa'her Rat'itet Ravali Rek'ze Rel'ha
Resh'rat Ret'herish Reth'a Rik'tharie Rit'zazes Ror'ze Sak'zar Salthalles
Sash'veeras Shak'thella Shal'za She'ha Shen'he Shir'he Shish'i Shish'vesh Sik'vath
Sith'ras Sok'hee Sosal've Tallan'zet Tar'ethith Tas'i Tat'i Terarat Tes'ieth
Teshieles Thal'hie Thash'vatheth Thathesi Thek'het Ther'hie Ther'thee Thes'eth
Thesev'haz Ti'hessit Tol'kash Vak'hasesh Val'zat Vath'val Vel'thezal Venelesh
Ver'zer Vet'zeez Vit'zera Voseleesh Vossen'ze Xar'hanash Xate Xel'kalla Xen'he
Xeshateth Xeshele Xeshi'hit Xeti Xex'ase Xil'hel Xil've Xir'thethees Xoneen'hi
Xosheer'ves Za'hesh Za'zanneesh Zak'vat Zateena Zath'valeel Zaziv'as Zeniltheth
Zer'zash Zera Zeshe Zetie Zhanathat Zhasith Zhek'he Zhel'ha Zhenieseth Zhetiel'va
Zhev'he Zhevesh Zhik'iner Zhil'heth Zhir'zene Zho'zeel Zhol'viennat Zhonnata
Zhot'hi Zhoth'vas Zok'har Zol'kel Zorevel
```

</details>

# How to test:
Check mantids use these names in-game and tell your opinion.

### CODE REVIEW

**Review by robmart — COMMENTED** [review]
Could find no issues in-game, the mantids use the names just fine.

Weird names:
* Ax 
* Az 
* Ham 
* Li 
* Milthil
* Nu 
* Pix 
* Rik 
* Shek 
* A lot of names without apostrophies sound too human/smooth for them to be Mantid names

**Comment by zumbak04** [comment]
> * Ax
> * Az
> * Ham
> * Li
> * Milthil
> * Nu
> * Pix
> * Rik
> * Shek

Removed in 71d1f270d622846ed68b27430e26c3b388c4a006.

> * A lot of names without apostrophes sound too human/smooth for them to be Mantid names (most of them seem to be male names)

Which ones? Not all mantid names are with apostrophes.
https://wowpedia.fandom.com/wiki/Mantid#Notable

**Comment by robmart** [comment]
> > * A lot of names without apostrophes sound too human/smooth for them to be Mantid names (most of them seem to be male names)
> 
> Which ones? Not all mantid names are with apostrophes.
> https://wowpedia.fandom.com/wiki/Mantid#Notable

These are the ones I could pick out that I thought sounded strange, some of the are quite weird but others are mostly me nit-picking.

```
* Asona 
* Athirun 
* Casil 
* Galir 
* Girvas 
* Helthas 
* Hethesil 
* Hilari
* Ilirra 
* Ilthin
* Irrarras 
* Krathunam
* Larrathak 
* Manathik 
* Menirot 
* Movvik 
* Pisonu 
* Purrevon 
* Rozzeevat
* Shovavum 
```

```
* Annalie 
* Ashieree 
* Esavas 
* Hatesi 
* Jeshennar 
* Lalthi 
* Lesil 
* Mara 
* Mathare
* Methe 
* Molthas 
* Monierri 
* Qenesee 
* Rallana 
* Relleli 
* Salthalles
* Teshieles 
* Thathesi 
* Zeniltheth
* Zera 
* Zeshe 
* Zetie 
* Zhanathat 
* Zhasith 
* Zhenieseth 
* Zhevesh 
* Zhonnata
* Zorevel
```

**Review by robmart — APPROVED** [review]
LGTM

**Review by TheGroxEmpire — APPROVED** [review]
Names look good for me too.

**Pull request merged**
