### PR TITLE
Holy Light icons by Kal

### PR DESCRIPTION
**Pull request by ElMariuso**
## Changelog:
- Added the icon of the Argent Dawn faith
- Added the icon of the surrender to inquisition interaction
- Added all artifacts (some are unused for the moment)

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Open the game and check or check the screenshots.

### CODE REVIEW

**Comment by Grekopithikos** [comment]
Could you make a new icon for the Masonic faith as well?
#435

**Comment by helloruhe** [comment]
@ElMariuso what needs to be done for this to be merged

**Comment by ElMariuso** [comment]
Kal said he want to darken and desature them

**Review by helloruhe — APPROVED** [review]
looks fine as it is

**Pull request merged**
