### PR TITLE
Pale Genes

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- Replaced color replace and other operations by 2 genes: `gene_paleness` and `gene_albino`.

# How to test:
Open the Ruler Designer, try to add sick traits like Ill, Lover's Pox, and Albino to characters. Their skin and hair color should be changed.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
``gene_paleness`` and ``gene_albino`` work correctly.

Suggestion: Maybe we should just use pale skin for sickness trait. It is not that realistic that your hair suddenly turn pale for most sickness. It's also pretty contrast for multi-colored hair like what Night Elves have.
<details>

Normal:
image

Ill:
image

</details>

**Comment by ulricee** [comment]
The pale orcs seems to have a humanlike tanned skin if they're albinos.





I don't know if that's a bug or a feature but I think it should be informed.

**Comment by zumbak04** [comment]
> The pale orcs seems to have a humanlike tanned skin if they're albinos.

> I don't know if that's a bug or a feature but I think it should be informed.

It's already informed.
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/97

**Comment by zumbak04** [comment]
> Suggestion: Maybe we should just use pale skin for sickness trait. It is not that realistic that your hair suddenly turn pale for most sickness. It's also pretty contrast for multi-colored hair like what Night Elves have.

Done in 224d9bc5265c88acf5f12ea529f8d9b11b5422b6.

**Review by TheGroxEmpire — APPROVED** [review]
My suggestion was applied correctly.

**Comment by ulricee** [comment]
Their is nothing else for me to add

**Pull request merged**
