### PR TITLE
Pygmy flag update

### PR DESCRIPTION
**Pull request by Rekutur**
Adding 10 CoAs for the Pygmy culture&implementing them.

# How to test:
Test if the CoAs have the desired dimensions.
Test if there are any issues with the CoAs.
Launch the game and check if the pygmies use the CoAs.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
Currently it's not applied to the generated Pygmy ruler CoA at start of the game. It's not possible to test them in the game.

**Review by TheGroxEmpire — COMMENTED** [review]
So far I only found one Pygmy with one of the new CoAs, the rest are still using Central African CoA.

<details>

image

</details>

**Comment by Rekutur** [comment]
Hey, so the AI is weighed 70% to choose one of the Pygmy CoAs when a new house is created, you think I should raise this chance?

**Review by TheGroxEmpire — COMMENTED** [review]
The changed modifier to 90% doesn't seem to work as expected. I only found one Pygmy CoA still and it's from the same house. Also, the directly implemented CoAs doesn't appear to work:
<details>

image

</details>

**Review by TheGroxEmpire — APPROVED** [review]
The CoA has been successfully implemented into the game.

**Pull request merged**
