### PR TITLE
2nd Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed an issue where Life and Shadow religious families could pick Sky Burials tenet reforming their faiths.
- Fixed an issue where `can_has_sexual_relation_with_character_tooltip_first_not` wasn't localized. The trigger appears when you try to romance someone of the wrong race.
- Changed the name of `d_twilights_hammer` to Twilight's Hammer.
- Fixed an issue where Belorism had the head of faith, but its doctrine said it had no.
- Fixed an issue where the Sunwell Cult (the title that holds the Sunwell) wasn't a vassal of Quel'thalas.
- The Head of Faith titles have "the" article before their names.

## Developer changelog:
- Resaved furbolg textures as .dds.
- Deleted duplicated triggers.
- Fixed errors mentioning `taken_duchies_num` in `error.log`.
- Fixed `pdxassetutil.cpp:907` from `error.log`. 
- Fixed many errors that happened during the game from `error.log`.

# How to test:
Test if the changes mentioned in the Changelog are correct and appear in-game.

### CODE REVIEW

**Review by Deuce20201 — COMMENTED** [review]
"The Head of Faith titles have "the" article before their names."

Meaning this?:

**Comment by zumbak04** [comment]
> "The Head of Faith titles have "the" article before their names."
> 
> Meaning this?:

Yes.

**Review by Deuce20201 — APPROVED** [review]
"1.Fixed an issue where Life and Shadow religious families could pick Sky Burials tenet reforming their faiths.
2.Fixed an issue where can_has_sexual_relation_with_character_tooltip_first_not wasn't localized. The trigger appears when you try to romance someone of the wrong race.
3.Changed the name of d_twilights_hammer to Twilight's Hammer.
4.Fixed an issue where Belorism had the head of faith, but its doctrine said it had no.
5.Fixed an issue where the Sunwell Cult (the title that holds the Sunwell) wasn't a vassal of Quel'thalas.
6.The Head of Faith titles have "the" article before their names.


1. Works
2. Works
3. Works
4. Works
5. Works
6. Works

**Review by TheDrPibb1999 — APPROVED** [review]
All six changes worked for me as well, looks solid. good stuff :D

**Pull request merged**
