### PR TITLE
11th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed Old Staroverstvo having no localization after a reformation.
- Ogre and Saurok provinces in 603 and 605 bookmarks having Fetishistic faith instead of their racial faith.
- Fixed Dark governments are not able to use castle buildings.
- Fixed spawned Grommash being born in 540s.
- Fixed unlocalized `can_have_sexual_relation_with_trigger_tooltip_first_not` appeared in conditions when you tried to marry wrong race.
- Fixed demon Eredar having no beards and hairs.
- Fixed Sylvanas not having her tears in the year 605 bookmark.
- Fixed not getting a notification when the spouse turns undead.
- Fixed the Alliance not creating after the Horde wins Stormwind.
- Fixed Kael'thas having a beard.
- Fixed Groundwizzle dynasty having Ogre race trait and being Gnoll culture.

## Developer changelog:
- Fixed `copy_inheritable_appearance_from` error due to the character being purged from game files.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Confirm bugfixes from the changelog works.

A few tips:
Right-click a character > Debug section > Become Undead to make a character undead.
Start in the year 583 bookmark, `event WCDRA.998` to spawn Grommash.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
Things that have not been fixed are marked  in **bold**:

> Fixed Old Staroverstvo having no localization after a reformation.

Reforming Staroverstvo now has correct localization.

> Ogre and Saurok provinces in 603 and 605 bookmarks having Fetishistic faith instead of their racial faith.

All landed Ogre and Saurok now don't have Fetishistic faith.

> Fixed Dark governments are not able to use castle buildings.

I was able to use and build castle as all Dark Government.

> Fixed spawned Grommash being born in 540s.

Using ``event WCDRA.998`` on 603 bookmark spawn Grommash that born in 556. 

> Fixed unlocalized can_have_sexual_relation_with_trigger_tooltip_first_not appeared in conditions when you tried to marry wrong race.

I can't marry races that aren't compatible; can't find the unlocalized condition.

> Fixed demon Eredar having no beards and hairs.

Some Eredar male now have hairs and beards.

> Fixed Sylvanas not having her tears in the year 605 bookmark.

I can see Sylvanas tear mascara in bookmark 605.

> Fixed not getting a notification when the spouse turns undead.

Undead spouse are correctly firing a divorce event.

> Fixed the Alliance not creating after the Horde wins Stormwind.

Can confirm that Alliance is now being created after Horde captured Stormwind.

> Fixed Kael'thas having a beard.

**Kael'thas still has beard on bookmark 605.**

<details>

image

</details>

**Review by TheGroxEmpire — APPROVED** [review]
Kael'thas is not having beard after I pulled the recent origin.

**Review by CantTouchThisJinTao — COMMENTED** [review]
Fixed Old Staroverstvo having no localization after a reformation. **✓**

Ogre and Saurok provinces in 603 and 605 bookmarks having Fetishistic faith instead of their racial faith.

**I noticed on region in eastern kingdoms that was ruled by a Gogic Ogre but the province was Fetishistic. He had Fetishistic Ogre courtiers due to this**

<details>
<summary>Dandred in eastern kingdoms</summary>

DandredRegionOgrefetishistic

</details>

**There was also a Ogre Trait on a Gnoll Culture/Fetishistic character (human visuals) character in the Asannaes region in Kalimdor, not sure what's going on with this character so thought I'd mention it just in case. (He exists with his family in all start dates).**

<details>
<summary>Tharg Gnoll Ogre Fetishistic</summary>

OgreGnolls583

</details>

Fixed Dark governments are not able to use castle buildings. **✓**

Fixed spawned Grommash being born in 540s. **✓**

Fixed unlocalized can_have_sexual_relation_with_trigger_tooltip_first_not appeared in conditions when you tried to marry wrong race.  **✓**   **I can't marry races that aren't compatible; can't find the unlocalized condition.** - same as Grox 

Fixed demon Eredar having no beards and hairs. **✓**

Fixed Sylvanas not having her tears in the year 605 bookmark. **✓**

Fixed not getting a notification when the spouse turns undead. **✓**

Fixed the Alliance not creating after the Horde wins Stormwind. **✓**

Fixed Kael'thas having a beard. **✓**

**Comment by zumbak04** [comment]
> I noticed one region in eastern kingdoms that was ruled by a Gogic Ogre but the province was Fetishistic. He had Fetishistic Ogre courtiers due to this

Fixed in 468937c41760270aae47f202235c37250db75ca7.

> There was also a Ogre Trait on a Gnoll Culture/Fetishistic character (human visuals) character in the Asannaes region in Kalimdor, not sure what's going on with this character so thought I'd mention it just in case. (He exists with his family in all start dates).

Fixed in ed8a1850312fdf45a20a4463fd82107470f50eac.

**Review by CantTouchThisJinTao — APPROVED** [review]
All LGTM :)

**Pull request merged**
