### PR TITLE
try_to_set_race_effect Memory Leak

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- `try_to_set_race_effect` took too much space in RAM, 2 GB. Putting it in an event fixed a problem.

# How to test:
Run the CK3, open the [Task Manager](https://en.wikipedia.org/wiki/Task_Manager_(Windows)) to check the RAM. Upon the main menu loading, CK3 should use about 3GB of RAM.

<details>
<summary>Click to expand</summary>

image

</details>

### CODE REVIEW

**Comment by Remerod** [comment]
I think mine uses more? Here a pic of menu
image
One when the game loads 
image
And one when the game is closed
image

I'm not really the guy to ask about performance and such, but since you said it was urgent i tried it out ;)

**Review by CatWitchLily — COMMENTED** [review]
On the menu, my game uses 3.8gb of ram, which is a bit more than 3gb. If this difference is expected then I have no other problems with it.

**Comment by Remerod** [comment]
Ok, new try, here some new screenshots of just CK3 Warcraft
On startup
image

In Menu
image

**Review by Remerod — APPROVED** [review]
For me it uses about 3gb ram as I have shown with my pics that i shared. So it works for me

**Review by robmart — APPROVED** [review]
Master (Main menu): 
image

Master (in-game);
image


Fix (main menu):
image

Fix (in-game):
image

Not quite reduced to 3GB for me, but significantly reduced regardless.

**Comment by zumbak04** [comment]
> On the menu, my game uses 3.8gb of ram, which is a bit more than 3gb. If this difference is expected then I have no other problems with it.

It's fine.

**Comment by robmart** [comment]
@CatWitchLily Can you approve it so it can be merged?

**Pull request merged**
