### PR TITLE
Ruler Designer Tweaks and Humpbackness

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- You can select **_Special Eyes_** in the Ruler Designer and Barbershop.
- The eyes no longer become colorless with age.
**_How to test:_** can be tested in the Ruler Designer changing age.
- Hunchbacked characters actually have hunchback now.
- Added a tusk variation for orcish females, Small Forward.

## Developer changelog:
- If you have the [Debug Mode](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode) enabled, you can select **_Tusks_** in the Ruler Designer.

# How to test:
Check if everything exists in the game and tell your opinion.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
Big tusks and small tusks upward are often clipping through the cheeks on older Orcish character. Usually happens after 40-50 years of age.
<details>

image
image
image
image
image
image

</details>

- Hunchbacked character animation are sometimes frozen or just idling but moving. Some idle animation are not compatible and it defaulted to frozen or idle animation. I think animations that have ``idle:`` infront are not working for them. I saw them doing some non idle animation without problem.
<details>

Frozen idle:
image

Pretty sure he should have a reaction animation here:
image

Working animation:
image

</details>

**Comment by zumbak04** [comment]
> Big tusks and small tusks upward are often clipping through the cheeks on older Orcish character. Usually happens after 40-50 years of age.

Rotated them a bit so should be fixed now.

> * Hunchbacked character animation are sometimes frozen or just idling but moving. Some idle animation are not compatible and it defaulted to frozen or idle animation. I think animations that have `idle:` infront are not working for them. I saw them doing some non idle animation without problem.

I unlocked other animations, let's hope they're not too broken in 55de972f44f53b4bb1605ab2715d56749f0c3bd5.

**Review by TheGroxEmpire — COMMENTED** [review]
- The tusks are fixed, no more clipping from what I found.
- I used the Full Barbershop addon to test the animation. The animation where I marked as red "X" are not working. The dungeon animation are also messed up:
<details>

image
image

Female (left) huncbacked, male (right) not hunchbacked:
image
</details>

**Comment by zumbak04** [comment]
> * I used the Full Barbershop addon to test the animation. The animation where I marked as red "X" are not working.

The addon doesn't work right. That's Bold animation.
<details>
<summary>Click to expand</summary>

image

</details>

That's hunchbacked with Bold animation.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> That's hunchbacked with Bold animation.

Tho... I see why they were idle now.

<details>
<summary>Click to expand</summary>

image

</details>
I think I'll revert my changes and lock animations. Hunchbacked break them.

**Comment by zumbak04** [comment]
> The dungeon animation are also messed up:

This and other weird animations are locked in 9071ff852bc4dbf13f2443e5785ef82d171a4487.

**Review by TheGroxEmpire — COMMENTED** [review]
- These are other weird animation I found. I didn't see this animation being changed in 9071ff8 and I'm assuming that the Barbershop animation is not restricted. So correct me if you already had these animations locked:
<details>

image
image
image
image
image
image
image
</details>

**Comment by zumbak04** [comment]
> * These are other weird animation I found. I didn't see this animation being changed in [9071ff8](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/9071ff852bc4dbf13f2443e5785ef82d171a4487) and I'm assuming that the Barbershop animation is not restricted. So correct me if you already had these animations locked:

They all should be locked in b6d1ec8e107403ec2c1e8f93372d288e9e96d3e7.

**Review by TheGroxEmpire — COMMENTED** [review]
Okay, I checked through the rest of the animation file and these are the rest of the animations that are commented (Not locked) but look weird. I think these should be the last of them:
<details>

image
image
image
image
image
image
</details>

**Comment by zumbak04** [comment]
> Okay, I checked through the rest of the animation file and these are the rest of the animations that are commented (Not locked) but look weird. I think these should be the last of them:

Locked in 0111d62c6dc49b7f279014ae189999b399882b0a.

**Review by TheGroxEmpire — APPROVED** [review]
That should be all from me.

**Pull request merged**
