### PR TITLE
Historical Plagues

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- The Plague starts in Andorhal at the beginning of the year 603 bookmark.
  - Alexei, Illucia, Jandice Barovs, and Pharamond Rivendare convert to the Scourge faith.
- If you play from the year 583 bookmark, the Scourge AI starts a Plague scheme after 6 years of ruling.
- Lordaeron cities get more development.
- The Plague spawns 75% more troops.
- Calm and Patient characters would like to join the Plague scheme.

# Tasks:
- [x] The Scourge should check for a few kingdoms away

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Test if features work in the year 603 bookmark.

Start in the year 583 bookmark, use `event WCCSC.1` to spawn the Scourge. Confirm the Scourge AI opens a Plague scheme.

### CODE REVIEW

**Review by Melnerag — COMMENTED** [review]
### Plague Starts
The Scourge correctly Plagues Lordaeron in 603. 
In 583, the Scourge _sometimes_ plagues Lordaeron. I tried to figure out why, I only have a working theory as the code is not entirely clear to me. But it seems that sometimes the Scourge destroys Wintergarde in a normal war, at a time that it should be plagueing it.

Is there a way to monitor variable values so I can investigate the hypothesis while testing?

### Plague of Lordaeron
I ran 10 observations of 603 mark, in all 10 the Scourge lost the plague war against Lordaeron. They seem to have a good start, typically going up to 40% warscore initially, but are then wiped out by the combined armies of the Alliance. 

It might be a problem with how the Unions work, or the Plague itself, or just the Plague of Lordaeron which we want to succeed close to 100% of the time.

**Comment by zumbak04** [comment]
> Is there a way to monitor variable values so I can investigate the hypothesis while testing?

The Scourge can't plague realms outside the diplomatic range. So to get to Lordaeron, they need to conquer Wintergarde or something closer.

> I ran 10 observations of 603 mark, in all 10 the Scourge lost the plague war against Lordaeron. They seem to have a good start, typically going up to 40% warscore initially, but are then wiped out by the combined armies of the Alliance.

I buffed troops in 901282d5f1f32e1bf6a13eccdb5be0a6dacbe27e.

**Review by TheGroxEmpire — COMMENTED** [review]
- Weldon Barov converted to Scourge. Canonically he should have fled and survived (https://wowpedia.fandom.com/wiki/Weldon_Barov)

- I discovered the same problem as Melnerag. It seems that the Scourge sometimes doesn't expand close enough to Lordaeron, making them not eligible to plague Lordaeron. Would it be possible to "weight" them to expand further to east much earlier on?

- Starting at 583. While the Scourge is scheming for plague in Lordaeron. If the current ruler of Lordaeron dies, the scheme must reset. The AI doesn't reset the scheme. On one playthrough I had Scourge not doing scheme until well over 600 AD because of that. The scourge got destroyed after 600 AD

**Comment by zumbak04** [comment]
> Weldon Barov converted to Scourge. Canonically he should have fled and survived

Changed in b7d8475f54c3eff9b39e5af0d52ed66b2bd58c52.

> I discovered the same problem as Melnerag. It seems that the Scourge sometimes doesn't expand close enough to Lordaeron, making them not eligible to plague Lordaeron. Would it be possible to "weight" them to expand further to east much earlier on?

It will very rushy. Allowed it without diplo range in 282af0fde789dc567c48f751736462311930ce42.

> Starting at 583. While the Scourge is scheming for plague in Lordaeron. If the current ruler of Lordaeron dies, the scheme must reset. The AI doesn't reset the scheme. On one playthrough I had Scourge not doing scheme until well over 600 AD because of that. The scourge got destroyed after 600 AD.

Fixed in 282af0fde789dc567c48f751736462311930ce42.

**Review by TheGroxEmpire — COMMENTED** [review]
> Changed in b7d8475.
- This seems to work. However the 603 events seemed to be hardcoded for Weldon Barov to always convert to Deathbringer faith. 5 out of 5 tries he always converted.

> Fixed in 282af0f
- This doesn't seem to work consistently. I tried 6 playthrough where I used debug to have someone kill Terenas during the plague scheme and it only restarted twice.

**Comment by zumbak04** [comment]
> * This seems to work. However the 603 events seemed to be hardcoded for Weldon Barov to always convert to Deathbringer faith. 5 out of 5 tries he always converted.

Fixed in 16dae6e233247e148160cff04befe27cc4c1d0d6.

> * This doesn't seem to work consistently. I tried 6 playthrough where I used debug to have someone kill Terenas during the plague scheme and it only restarted twice.

Changed in 8eeb1c998f5a0454430ee763f51e02cfc861d402.

**Review by TheGroxEmpire — APPROVED** [review]
My issues are fixed. The Scourge is a lot more aggressive in refreshing the plague scheme, but I think it makes it even better. Some courtier that doesn't approve Deathbringer faith could also be seen not converting when their liege did.

**Review by Panabana — CHANGES_REQUESTED** [review]
Year 603 tests
On 1st observation run, plague mechanics on year 603 bookmark started correctly and progressed well until Ner'zhul was about to win a second war - Great Invasion war - with Lordaeron. So far so good.
But then he was executed by a sargerite seemingly from the Vrykul Feigr's court.
<details>
<summary>Click to expand</summary>

image
</details>

On 2nd observation run, the Scourge starts according to plague features. After the Scourge wins over Lordaeron, they start a Great Invasion war with Dalaran, but lose. This leads to the Scourge empire being destroyed and Ner'zhul did nothing more, ruling "The Deathbringers" duchy+counties only.


Will test this startdate more, and the 583 startdate as well.

**Review by Panabana — APPROVED** [review]
2nd round of tests worked on both bookmarks.

Only noticeable bug: Portrait bug of Ner'zhul where his ice block turned into a huge square

**Comment by zumbak04** [comment]
> Only noticeable bug: Portrait bug of Ner'zhul where his ice block turned into a huge square

I can't confirm. Do you use other mods?

**Comment by Panabana** [comment]
> 
@zumbak04 

Just GoA in the playset.
<details>
<summary>Click to expand</summary>

image
</details>

Here's image of the Lich King icicle. Bug seems to happen when starting early bookmark with 110% scaling.
<details>
<summary>Click to expand</summary>

image)
</details>

**Comment by zumbak04** [comment]
> Here's image of the Lich King icicle. Bug seems to happen (sometimes) when starting early bookmark with 110% scaling.

It's not a bug. His model can't fit in the frame.

**Review by Holt228 — APPROVED** [review]
1)
ER: The Plague starts in Andorhal at the beginning of the year 603 bookmark. Alexei, Illucia, Jandice Barovs, and Pharamond Rivendare convert to the Scourge faith.
AR: The Plague starts in the Grand City of Andorhal at the beginning of the year 603 bookmark. Alexei, Illucia, Jandice Barovs, and Pharamond Rivendare convert to the Scourge faith as soon as the plague starts.

2) 
ER: The Scourge AI starts a Plague scheme after 6 years of ruling in case you started from 583 bookmark.
AR: The Scourge AI starts a Plague scheme after 6-7 years of ruling in case you started from 583 bookmark (varied during 5 conducted tests).

3) 
ER: Being Calm and Patient doesn't add any negative opinion modifiers for joining a Plague scheme
AR: Being Calm and Patient doesn't add any negative opinion modifiers for joining a Plague scheme

4) 
ER: There are no errors in wc files
AR: There are also errors in wc_story_cycle_scourge_invasion_events.txt line: 27, 94, 114, 134, 154, 174, 194. All errors are related to _[jomini_script_system.cpp:169]_. None of them impede the gameplay.

5) 
ER: The mod takes less than 5.5 GB in the Task Manager
AR: The mod takes somewhere around 4,9-5,7 GB in the Task Manager, depending on the time played and the bookmark chosen. 

Comment: It usually reaches 5,7 GB after running for about half an hour. (Seems to be consistent during 3 separate tests, all starting at 583 bookmark.) 603 bookmark consistently takes up 5,2 GB in the Task Manager.

**Pull request merged**
