### PR TITLE
1.4.0 Scripted Hotfix

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed a bug where scripted characters like Llane Wrynn were bald.

# How to test:
Just check this one bug is gone.

### CODE REVIEW

**Review by Deuce20201 — APPROVED** [review]
Llane, among others, all have hair

**Review by ElMariuso — CHANGES_REQUESTED** [review]
Everybody LGTM but Gul'dan have fancy hair.
<details>
<summary>Click to expand</summary>

(image`)
</details>

**Comment by zumbak04** [comment]
> Everybody LGTM but Gul'dan have fancy hair.

Fixed in 3fa9c36ca6f2688481639b1f349d1738e3a955ac.

**Review by ElMariuso — APPROVED** [review]
> 
> 
> > Everybody LGTM but Gul'dan have fancy hair.
> 
> Fixed in [3fa9c36](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/3fa9c36ca6f2688481639b1f349d1738e3a955ac).

LGTM !

**Pull request merged**
