### PR TITLE
Demonic Models

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Exported WoW models for 3 demonic races:
  - Annihilans
  - Observers
  - Ered'ruin

## Tasks:
- [x] Cut models on the HUD in circle form.

# How to test:
Use...
 - `add_trait creature_annihilan` to become an annihilan.
 - `add_trait creature_observer` to become an observer.
 - `add_trait creature_eredruin` to become a ered'ruin.

### CODE REVIEW

**Review by ValianBlue — COMMENTED** [review]
_The models successfully updated on applying the specific traits. They are static (motionless), although that's likely a WIP issue._

<br>

_The Annihilan model is clipped on the character screen, and multi person event screen. It seems to be okay for single person events. At a Glance, the Annihilan is perfect._

<details>
<summary>Annihilan (Character Screen)</summary>


</details>

<details>
<summary>Annihilan (At a Glance)</summary>


</details>

<details>
<summary>Annihilan (Single Person Event)</summary>


</details>

<details>
<summary>Annihilan (Multi Person Event)</summary>


</details>

<br>

_The Observer model is the best of the three, especially on the character screen. It does look small on the event screens, especially the single person events. At a Glance, the Observer should be moved up so the eye is more center, and perhaps zoomed out a bit more._

<details>
<summary>Observer (Character Screen)</summary>


</details>

<details>
<summary>Observer (At a Glance)</summary>


</details>

<details>
<summary>Observer (Single Person Event)</summary>


</details>

<details>
<summary>Observer (Multi Person Event)</summary>


</details>

<br>

_The Ered'ruin model is clipped on all screens. At a Glance, the Ered'ruin should be moved up so it's more center._

<details>
<summary>Ered'ruin (Character Screen)</summary>


</details>

<details>
<summary>Ered'ruin (At a Glance)</summary>


</details>

<details>
<summary>Ered'ruin (Single Person Event)</summary>


</details>

<details>
<summary>Ered'ruin (Multi Person Event)</summary>


</details>

**Comment by zumbak04** [comment]
> At a Glance, the Observer should be moved up so the eye is more center, and perhaps zoomed out a bit more.

Zoomed out? Thus make it smaller?

**Comment by zumbak04** [comment]
> They are static (motionless), although that's likely a WIP issue.
We don't animate WoW models.

> The Annihilan model is clipped on the character screen

It's impossible to fix due to their sizes.

> At a Glance, the Observer should be moved up so the eye is more center, and perhaps zoomed out a bit more.
Done in 68a087223c1875c425b1fe89b54fa6ad5b7677f5 except made it bigger.

> At a Glance, the Ered'ruin should be moved up so it's more center.
Done in 68a087223c1875c425b1fe89b54fa6ad5b7677f5.

**Review by ValianBlue — APPROVED** [review]
> 
> 
> > They are static (motionless), although that's likely a WIP issue.
> 
> We don't animate WoW models.
> 
> > The Annihilan model is clipped on the character screen
> 
> It's impossible to fix due to their sizes.
> 
> > At a Glance, the Observer should be moved up so the eye is more center, and perhaps zoomed out a bit more.
> 
> Done in [68a0872](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/68a087223c1875c425b1fe89b54fa6ad5b7677f5) except made it bigger.
> 
> > At a Glance, the Ered'ruin should be moved up so it's more center.
> 
> Done in [68a0872](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/68a087223c1875c425b1fe89b54fa6ad5b7677f5).



_Latest changes are working and verified._

**Review by CantTouchThisJinTao — APPROVED** [review]
LGTM, not really noticing any issues personally. Ered'ruin seems a little bit high when a character is selected.

<details>
<summary>Click to expand</summary>

eredruinck3goa

</details>

but all other screen seem perfect, due to limitations with the model I'd say it's currently pretty close to perfect so happy to approve (moving it for the above screen will potentially cause issues on the others).

**Pull request merged**
