### PR TITLE
8th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed an issue where characters created in the Ruler Designer were giving a wrong race trait.
   - **_How to test:_** create a character via the Ruler Designer.
- Fixed an issue where Varia, mother of Llana Wrynn could be black.
- Deleted duplicate characters that made characters with no names, no traits, and at the max age, visible in the Character Finder.
   - **_How to test:_** observe characters in the Character Finder sorted by descending age.
- Fixed an issue where vrykul commanders wore no clothes.
- Fixed an issue where the game could spawn characters with an underscore in the name.
   - **_How to test:_** observe human character in the Character Finder.
- Fixed an issue where orcish hybrids got tusks clipped with lips due to inheriting tusks but no strong mouth genes.
- Fixed Draenei hoof clipping when they were below 16.
   - **_How to test:_** open the game in the Debug mode, press the tilde, open the `Portrait Editor`, find the `draenei_ethicity` in the list, set the **_Age_** to **_0%_**, observe the hooves.

# Developer changelog:
- Localized `SKULL_NAME`.
- Updated the German name localization.
- Deleted not declared trigger, `is_renault_trigger`.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Draenei Hooves for age <16 looks good from Portrait Editor.
- Using the Character Finder. There was a character that doesn't get their race trait assigned:
<details>

Human trait + Human culture = 2558 results.
image

Human culture only = 2559.
image

</details>

- Ruler Designer are giving traits appropriately every time.
- I created a hybrid from male Night Elf and female Orcs. Both male and female child hybrid doesn't seems to have clipping issues on their tusk. The male offspring inherited the mouth structure of an orcs. while the female offspring didn't have tusk at all.
- No naked Vrykul commander appeared on my playtest.
- Varia appeared to have white skin color.

**Comment by zumbak04** [comment]
> * Using the Character Finder. There was a character that doesn't get their race trait assigned:

He got 🐽
<details>
<summary>Click to expand</summary>

image

</details>

**Review by CantTouchThisJinTao — APPROVED** [review]
Everything appears to be fixed/working as intended.
I experienced no wrong traits on ruler designed characters.
Varia appeared white in every load.
No duplicate characters appeared.
Vrykul commanders wore clothes.
No characters with underscores in their names were seen.
Noticed no tusk or hoof clipping (although hooves looked weird at age 0 and got better as the Draenei aged).

The only issue I noticed really was in the character finder, some characters appeared to be a different race to what they actually were.

<details>
<summary>Click to expand</summary>

ck38thbugcrusadecharacterelfhuman

</details>

**Comment by zumbak04** [comment]
> The only issue I noticed really was in the character finder, some characters appeared to be a different race to what they actually were.

And when you clicked there were looking like humans?

**Review by TheGroxEmpire — APPROVED** [review]
Everything seems to be working accordingly then!

**Pull request merged**
