### PR TITLE
Baby Tauren Model

### PR DESCRIPTION
**Pull request by ercarp**
ℹ️ **Development Notice**: Please note that this branch is based on [1-8-1-update](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/1-8-1-update), which means it **_should not_** be merged into `master` until after the `1-8-1-update` branch has been merged.

## Changelog:
- Added a custom static model for **Baby Tauren**.
  - This is used by **_Tauren_**, **_Yaungol_**, and **_Taunka_** between ages 0 to 9, after which they experience a magical growth spurt and become chonky at the age of 10.

<details><summary>Image</summary>

image

</details>

## ⚠️ Known issues

1. The model's eyes are permanently closed.
   - _(Note: I tried to fix this but it's not as easy as it looks, especially when limited to working with GIMP. If anyone else wants to take a crack at it, be my guest. -ercarp)_

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
1. Start up **Crusader Kings III** in version `1.8.2` and look for **_Tauren_** characters. You can use the `age -# [character ID]` command if you can't find any Child characters.
2. Report bugs and give feedback.

### CODE REVIEW

**Review by CantTouchThisJinTao — COMMENTED** [review]
I'd suggest maybe moving the baby up a bit so it isn't peeking over like this:

<details>
<summary>Baby peeking</summary>

babytaurenportrait

</details>

Might mess up the look of the baby though when selected. If it does then yeah i'm fine with the current view.

<details>
<summary>AdultBabyTaunka</summary>

taunkababyadult

</details>

Found a few Taunka that were 9 or under but had adult portraits. Didn't notice this issue with Yaungol or Tauren

**Comment by ercarp** [comment]
> I'd suggest maybe moving the baby up a bit so it isn't peeking over like this:
> Might mess up the look of the baby though when selected. If it does then yeah i'm fine with the current view.

Unfortunately if I move the model up _too much_, it will look like it's floating in mid-air in the character view. However, I did try to adjust it a *tiny* bit and I feel like it's not as bad anymore - but it varies a little.

<details><summary>Image</summary>

image

</details>

> Found a few Taunka that were 9 or under but had adult portraits. Didn't notice this issue with Yaungol or Tauren

Thanks for pointing this out, seems I had missed one modifier. Fixed in bb95234dcb543597049892f223d8d626285751c1.

**Review by CantTouchThisJinTao — APPROVED** [review]
LGTM

**Review by TheDrPibb1999 — APPROVED** [review]
LGTM :DD

**Review by ElMariuso — APPROVED** [review]
I think it look good for the moment

**Pull request merged**
