### PR TITLE
Lore changes to Aliden Perenolde and Falconcrest

### PR DESCRIPTION
**Pull request by CrazierIvan**
## Changelog:
Removed Trusting and Content from Aliden Perenolde, replaced by Ambitious and Lustful. The reason being, a man who starts a rogue state because he got skipped in succession is in no way Content. Aliden also canonically had a mistress called Elyza.
Replaced Aliden's intrigue education with martial, because he's depicted as an armored warrior in WoW, and appears to be familiar with military matters in the books, but I'm open to reverting that. There's also some grounds for making it into Diplomatic.
Removed Just from Kevin Falconcrest, replaced with Ambitious, Patient, Deceitful. According to the RPG lore, Kevin is a somewhat disloyal underling, who wants to replace Aliden as the leader eventually. I don't know what was the justification for the old Just trait, he is not particularly Just in any source.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Load into the TFT bookmark, see the traits.

### CODE REVIEW

**Comment by CrazierIvan** [comment]
My first attempt to mod CK3 and my first PR, there may be more in the future.

**Comment by Grekopithikos** [comment]
> Aliden also canonically had a mistress called Elyza.

Source?

**Comment by Grekopithikos** [comment]
oh never mind I couldn't find her because of the typo
https://warcraft.wiki.gg/wiki/Elysa

**Comment by Grekopithikos** [comment]
Maybe Falconcrest could have the disloyal trait?

**Comment by Grekopithikos** [comment]
> Replaced Aliden's intrigue education with martial, because he's depicted as an armored warrior in WoW

> [While his armor would imply that he was a warrior, his skills indicated he was a priest](https://warcraft.wiki.gg/wiki/Aliden_Perenolde#Notes).

**Comment by CrazierIvan** [comment]
Falconcrest and Perenolde both have Ambitious, so there's already going to be a hefty opinion penalty as it is - but I can add Disloyal too.
In regards to the education, I'm open to opinions. Military education made the most sense to me at the time, as a former noble turned leader of a gang of raiders. He's not really doing any courtly intrigue, or scholaring and development.

**Review by Grekopithikos — APPROVED** [review]
Alright makes sense
LGTM (Looks Good To Me)
Make sure to update from master before you merge

**Pull request merged**
