### PR TITLE
Less Likely Interracial AI

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- The AI is less likely to seduce, romance, and marry different race:
   - When you try to marry, you will get the Different Race debuff.
   - When you try to Seduce or Romance, the success chance will be lowered.
   - The AI never takes concubines of a different race.
   - The AI doesn't create interracial couples with and between its courtiers.
   - The human and high elven AI tolerates interracial marriages between each other by 50%.
   - The human and elven AI tolerates interracial marriages between each other by 25%.

# How to test:
Enter the observe mode and observe the game for a few years. Pay special attention to the Horde since it settles on human and dwarven lands.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- I don't receive the different race opinion debuff from these arrangement:

<details>

image
image

</details>

- It's still pretty often to get interracial marriages from the AI. More so on not so differing faith (Astray etc):
<details>

image
image
image

</details>

- It doesn't say that I'm going to have less chance from doing interracial seduction / romance if they are a lowborn:
<details>

image
image
image

</details

**Comment by zumbak04** [comment]
> * I don't receive the different race opinion debuff from these arrangement:

> * It doesn't say that I'm going to have less chance from doing interracial seduction / romance if they are a lowborn:

As I said, the elves and humans are an exception. They don't mind.

**Comment by TheGroxEmpire** [comment]
> As I said, the elves and humans are an exception. They don't mind.

Okay, I think it's pretty logical for Human and High Elves. But Human and Night Elves are not that often to be paired on Warcraft

**Comment by zumbak04** [comment]
> * It's still pretty often to get interracial marriages from the AI. More so on not so differing faith (Astray etc):

The first one is a political alliance due to VERY high desire (about +100 from this). I think it's the max possible. I've seen it too. Others, not sure. I can increase the debuff though.

**Review by TheGroxEmpire — COMMENTED** [review]
> The first one is a political alliance due to VERY high desire (about +100 from this). I think it's the max possible. I've seen it too. Others, not sure. I can increase the debuff though.

I think increasing the debuff could work and it'll likely also fix the Orc X another race combination. The more radical approach would be to nerf the bonus from political alliances, I don't think marriages in Warcraft serves as alliances for the most part anyway.

- I also think that you should include the debuff for Night Elves X Humans. There's no canon example of those couple. (https://wow.gamepedia.com/Half-night_elf)

**Comment by zumbak04** [comment]
> I think increasing the debuff could work and it'll likely also fix the Orc X another race combination. The more radical approach would be to nerf the bonus from political alliances, I don't think marriages in Warcraft serves as alliances for the most part anyway.

Done in e0f718e4f886958dc7b62dc151197e116f52d2c6.

> * I also think that you should include the debuff for Night Elves X Humans. There's no canon example of those couple. (https://wow.gamepedia.com/Half-night_elf)

Done, but they get the half of the debuff.

**Review by TheGroxEmpire — COMMENTED** [review]
- Didn't know exactly how this happened. I think there's a random event that triggers the AI to have an affair with random lowborn. Here's bastard Half Orc-Trolls with a lowborn Troll father:
<details>

image

</details>

- Night elves, High Elves, Human usually exchange courts which makes it more likely for them to marry each other due to ``marrying up`` opinion bonus despite the -75 opinion debuff:
<details>

image
image
image
image

</details>

- I have a feeling that these alliances opinion bonus would make interracial marriages happen often on high tier title (Lordaeron, Quel'thalas, etc). What do you think about it?
<details>

image
image
</details>

- The increase on opinion debuff seems to work, there were much less Orcs marrying other races. It still happens in rare case after the conquered races convert to Corruptic religion but still acceptable:
<details>

image
</details>

**Comment by zumbak04** [comment]
> * Didn't know exactly how this happened. I think there's a random event that triggers the AI to have an affair with random lowborn. Here's bastard Half Orc-Trolls with a lowborn Troll father:

Should be fixed in 352c2e157ed8b393ca3b26507965cd8550315126. If you notice it again, tell me.

> * Night elves, High Elves, Human usually exchange courts which makes it more likely for them to marry each other due to `marrying up` opinion bonus despite the -75 opinion debuff:

> * I have a feeling that these alliances opinion bonus would make interracial marriages happen often on high tier title (Lordaeron, Quel'thalas, etc). What do you think about it?

I did a few tweaks in dbf3ddb6aef4df7ec63a28b046a8707f37d42f97. More in the commit comment.

**Review by TheGroxEmpire — COMMENTED** [review]
- This is really cursed. I think the alliance opinion bonus is at fault here yet again:
<details>

image
image
</details>

- For some reason the ``difference race`` debuff for non Elves got reduced back to -100. Allowing these to happen often:
<details>

image
image
image
image

</details>

- There are Red Dragon bastards with Green Dragon culture from Red Dragon father and Green Dragon mother:
<details>

image
image

</details>

**Comment by zumbak04** [comment]
> * This is really cursed. I think the alliance opinion bonus is at fault here yet again:

> * For some reason the `difference race` debuff for non Elves got reduced back to -100. Allowing these to happen often:

That's because you're a player. Anyway, I'm bringing back the plain debuff in 432891b46e32e008316b5c062efe94af66e53ce1 because I don't want to overcomplicate it.

> * There are Red Dragon bastards with Green Dragon culture from Red Dragon father and Green Dragon mother:

Dragons are allowed to mate.

**Review by TheGroxEmpire — COMMENTED** [review]
I didn't find many interracial marriages. In fact, it is just the Northern EK emperors that did. Lordaeron and Quelthalas are doing interracial marriages too often. This is along multiple playtests / generations and they mostly marry other races. The rest are good though.

<details>

image
image
image
image
image
</details>

**Comment by zumbak04** [comment]
> I didn't find many interracial marriages. In fact, it is just the Northern EK emperors that did. Lordaeron and Quelthalas are doing interracial marriages too often. This is along multiple playtests / generations and they mostly marry other races. The rest are good though.

They're emperors thus there are more options for them since MANY want to marry them.

**Review by Deuce20201 — APPROVED** [review]
I think the current system is good. I observed for about 25 in game years and I saw only 1 interacial marriage, between the heir of Quael'Thalas and Lordaeron.  Which you said is possible in the changelog.

**Review by TheGroxEmpire — APPROVED** [review]
All things considered then.

**Pull request merged**
