### PR TITLE
Terrain-3 Bugfixes & Changes

### LINKED ISSUE #614: Change Temple of Atal'Hakkar location
**Describe your suggestion in full detail below:**

The Temple of Atal'Hakkar, in Swamp of Sorrows, has its temple holding on the shore of the lake. I think it should be moved onto the island in the middle of the lake, like it is shown in game. The Barony covers both areas, but the visual for the holding shows it on the shoreline outside of the lake.

### PR DESCRIPTION
**Pull request by ValianBlue**
Closes #662. Resolves #614 #623 #625 #626 #1056 #1067.

_Given the scope of `terrain-2` has expanded to greater dimensions, its original purpose was to rectify several bugs and inaccuracies. While there is still more work pertaining to issue #342 to be addressed, this PR will cover immediate bugs._

## Changelog:
- Complete rework of the _Venomweb_ Vale region in Tirisfal Glades.
- Added trees to Northern Eastern Kingdoms regions.
- Added "urban" terrain to the areas associated with Capital City (Lordaeron), Stromgrade (Arathi Basin), and Stratholme (Eastern Lordaeron).
- Numerous bugfixes covered here: https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/662#issuecomment-977424839

### 1067
- Added a crossing point between province 16 (STONECAIRN) and province 2384 (TREGATE).

## Known Issues:
- Redoing the trees in the Eastern Kingdoms has consequently reset all of the tree placements on the map.

## Planned Changes & Requests
- For the next PR, the rest of the changes from #662 up to the TRANSLATE project will be implemented. Notably including the Silithus overhaul.
- Correction of the remaining inaccuracies listed in #342.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
(This section shamelessly copied from @ercarp)

Consider the following when giving your feedback:

**Gameplay:** For pertinent bugs, verify if the bugfixes are working as intended.

**Canonicity:** Compare the map changes to ensure accuracy according to the information made available by official canon.

**Familiarity:** Observe whether or not the changes are recognizable and fitting for their respective locations.

**Aesthetics:** Comment on the general look and appeal on the changes. Suggestions should be as specific as possible.

Additionally, ensure that necessary gameplay features like Holdings are not obscured by map changes such as trees, water, or steep cliffs.

### CODE REVIEW

**Comment by VespertinePetrichor** [comment]
Consider adding more tree cover to these areas in Quel'thalas and Zul'Aman.
image

**Review by Gaben1025 — CHANGES_REQUESTED** [review]
North EK looks good

## What to add IMO:

Grim Batol trees
Great Utgarde trees
Azuremyst Isles trees
North Kalimdor trees
Feralas trees
Eldre'thalas trees

## Also this little gfx issue:
image

**Comment by ValianBlue** [comment]
#  Changelog
@VespertinePetrichor  @Gaben1025 

## 8e0f8aa;
>Added trees to several regions in the Northern Eastern Kingdoms.

<details>
<summary>Quel'thelas</summary>

image
</details>

<details>
<summary>Eversong Woods</summary>

image
</details>

<details>
<summary>Ghostlands & Zul'Aman</summary>

image
</details>

<details>
<summary>Eastern Lordaeron</summary>

image
</details>

<details>
<summary>Western Lordaeron</summary>

image
</details>

<details>
<summary>Gilneas, Silverpine Forest & Hillsbrad Foothills</summary>

image
</details>

<details>
<summary>Hinterlands & Arathi Basin</summary>

image
</details>

## cfdfb76;
>Added trees to the Grim Batol, Great Utgarde & Azuremyst Isles regions.

<details>
<summary>Grim Batol</summary>

image
</details>

<details>
<summary>Great Utgarde</summary>

image
</details>

<details>
<summary>Azuremyst Isles</summary>

image
</details>

## debb03c;
>Corrected the impassible terrain gfx bug.

<details>
<summary>Bug</summary>

image
</details>

<details>
<summary>Fix</summary>

image
</details>

## e8a3056;
>Added trees to the Northern Kalimdor, Feralas & Eldre'thalas regions.

### Northern Kalimdor
<details>
<summary>Ashenvale</summary>

image
</details>

<details>
<summary>Azshara</summary>

image
</details>

<details>
<summary>Moonglade & Winterspring</summary>

image
</details>

<details>
<summary>Darkshore, Felwood & Mount Hyjal</summary>

image
</details>

### Feralas & Eldre'thalas
<details>
<summary></summary>

image
</details>

## 98e153b;
>Beautification of Silithus. Changes implemented from #662.

<details>
<summary></summary>

image
</details>

## f7dc338;
>Beautification of the Feathermoon Isles. Relocated the South Seas Islands. Changes implemented from #662.

### Feathermoon Isles
<details>
<summary></summary>

image
</details>

### South Seas Islands
<details>
<summary>Before</summary>

image
</details>

<details>
<summary>After</summary>

image
</details>

**Review by Gaben1025 — APPROVED** [review]
LGTM

**Pull request merged**
