### PR TITLE
Custom Uther Hairstyle

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Added a custom hairstyle for Uther
- Added it to his portrait modifier so he changes to use the custom hairstyle at age >=40.

# How to test:
- Give feedback on the custom hairstyle.

### CODE REVIEW

**Review by TheDrPibb1999 — APPROVED** [review]
Awesome work, nothing more to say - looks great and proper for Uther, is it possible to give him the title "the Light Bringer"? Hairstyle is perfect

**Comment by ercarp** [comment]
> 
> 
> Awesome work, nothing more to say - looks great and proper for Uther, is it possible to give him the title "the Light Bringer"? Hairstyle is perfect

There's already a flag in his history file for him to receive the Lightbringer title. Not sure if it's been implemented yet though, it's probably a leftover from CK2 import.

**Comment by zumbak04** [comment]
Why it has a doubtful tag?

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
