### PR TITLE
Kaldrskegg flag pack 2

### PR DESCRIPTION
**Pull request by tiefield**
## Changelog:
-Added several COA icons made by Kaldrskegg !
  
-Organized the COA into new Warcraft  category and added color code so they are now available for COA editing (examples being Human, Outland Tribal, Undead, Demons, Elven etc)

-A few of the Initial COA I made before the new Icons were added for counties in Kingdom of Stormwind. 

-Adds some foundation for the AI generating COA for the different races

### CODE REVIEW

**Review by helloruhe — CHANGES_REQUESTED** [review]
fix errors pls

**Comment by edmund-h** [comment]
also please write a description for the PR

**Comment by helloruhe** [comment]
errors in colored_emblem_lists.txt are still there

**Comment by robmart** [comment]
Superseded by #1432

**Pull request closed without merging**
