### PR TITLE
Character Errors

### PR DESCRIPTION
**Pull request by zumbak04**
### **Councilors:**
  - **Shandris Feathermoon** is a Marshal of the Kaldorei since the year 50.
  - **Zul** is a Chancellor of the Zandalari since the year 566.
  - **Yazma** is a Spymaster of the Zandalari since year 560.
  - **Katrana Prestor** is a Chancellor of Stormwind since the year 600.
  - **Sylvanas Windrunner** is a Marshal of Quel'thalas since the year 603.
  - **Halduron Brightwing** is a Marshal of Quel'thalas since the year 605.
  - **Lireesa Windrunner** is a Marshal of Quel'thalas since the year 156.
  - **Gul'dan** is a Chancellor of the Horde since the year 583.
  - **Nagaz** is a Spymaster of the Horde since the year 583.
  - **Drak'thul** is a Court Chaplain of Gul'dan since the year 583.
  - **Orgrim Doomhammer** is a Marshal of the Horde since the year 583.
  - **Drek'thar** is a Court Chaplain of the Frostwolfs since the year 583.
  - **Garona** is a Spymaster of Gul'dan since the year 583.
  - **Egerton Erlgadin** is a Steward of Stormwind since the year 567.
  - **Anduin Lothar** is a Marshal of Stormwind since the year 565.
  - **Pathonia Shaw** is a Spymaster of Stormwind since the year 560.
  - **Mathias Shaw** is a Spymaster of Stormwind since the year 600.
  - **Natalie Seline** is a Court Chaplain of Stormwind since the year 580.
  - **Laurena** is a Court Chaplain of Stormwind since the year 585.
  - **Moroes** is a Steward of Medivh since the year 558.
  - **Reginald Windsor** is a Marshal of Stormwind since the year 590.
  - **Cho'gall** is a Court Chaplain of the Horde since the year 583.
  - **Kel'Thuzad** is a Spymaster of Dalaran since the year 561.
  - **Modera** is a Marshal of Dalaran since the year 565.
  - **Ansirem Runeweaver** is a Court Chaplain of Dalaran since the year 571.
  - **Rhonin** is a Steward of Dalaran since the year 601.
  - **Drenden** is a Spymaster of Dalaran since the year 601.
  - **Kael'thas Sunstrider** is a Chancellor of Dalaran since the year 583.
### **Opinions:**
  - **Blackhand**, **Nagaz**, **Teron'gor**, **Fel'dan**, **Ragnok**, and **Drak'thul** have the Loyal Servant opinion of **Gul'dan**.
  - **Conrad Kurzen** has the Loyal Servant opinion of **Mai'zoth** since the year 603.
  - **Aiden Perenolde** has the Envy opinion of **Terenas II**.
  - **Sigismund Blackthorn** has Loyal Servant opinion of **Sylvanas** since the year 605.
- **Go'el** is named **Thrall** after he gets to **Aedelas**.

## Developer changelog:
- Added `add_patron_trait_character_effect` and `add_fan_trait_character_effect` for future use.
- `purge_historical_character_effect` removes parents only if they exist.
- Fixed errors mentioning `history/characters`.

# Tasks:
- [x] Replace opinions

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Confirm characters have the mentioned opinions and councilors.

### CODE REVIEW

**Review by Darknight367 — CHANGES_REQUESTED** [review]
Most of the characters have their respective council titles. But....

Drenden and Kel'Thuzad are both spymasters of Dalaran as per in the changelog. But in 583 Kel'Thuzad is the spymaster of Dalaran. While in 603 it's Drenden.

Gul'dan instead of being a chancellor is a steward and so is Zul. However, Zul is the chancellor in 603.

Haldurion is a chancellor instead of Marshall.

Egerton is a chancellor instead of a steward.

Rhonin is a steward of Anastarien in 603, but he is the steward of Kirin Tor in 605

Pathonia is still the spymaster of Stormwind in 603 and 605

And Drak'Thul doesn't have the Loyal Servant modifier.

**Comment by zumbak04** [comment]
> Drenden and Kel'Thuzad are both spymasters of Dalaran as per in the changelog. But in 583 Kel'Thuzad is the spymaster of Dalaran. While in 603 it's Drenden.
> 
> Gul'dan instead of being a chancellor is a steward and so is Zul. However, Zul is the chancellor in 603.
> 
> Haldurion is a chancellor instead of Marshall.
> 
> Egerton is a chancellor instead of a steward.
> 
> Rhonin is a steward of Anastarien in 603, but he is the steward of Kirin Tor in 605
> 
> Pathonia is still the spymaster of Stormwind in 603 and 605
> 
> And Drak'Thul doesn't have the Loyal Servant modifier.

Good catch! Fixed in c40065f503734c0308734ce69d4d85b70c0d33fa.

**Comment by ercarp** [comment]
All of the council positions work. ✔️

>* **Blackhand**, **Nagaz**, **Teron'gor**, **Fel'dan**, **Ragnok**, and **Drak'thul** have the Loyal Servant opinion of **Gul'dan**.
>* **Conrad Kurzen** has the Loyal Servant opinion of **Mai'zoth** since the year 603.
>* **Aiden Perenolde** has the Envy opinion of **Terenas II**.
>* **Sigismund Blackthorn** has Loyal Servant opinion of **Sylvanas** since the year 605.
>* **Go'el** is named **Thrall** after he gets to **Aedelas**.

Works. ✔️

Should we add the Loyal Servant opinion modifier to Nathanos as well? Perhaps from 583 onwards, or whenever he became buddy-buddy with Sylvanas. He was already working with her before he was raised into undeath.

> Nathanos Marris was the first and only human ranger as well as the only human ranger lord, the highest rank in the Farstriders' hierarchy below ranger-general, appointed as such by Ranger-General Sylvanas Windrunner.

**Review by Darknight367 — COMMENTED** [review]
All looks good! Though Egerton is still a chancellor.

**Comment by zumbak04** [comment]
> Should we add the Loyal Servant opinion modifier to Nathanos as well (towards Sylvanas)? Perhaps from 583 onwards, or whenever he became buddy-buddy with Sylvanas. He was already working with her before he was raised into undeath.

Added in ceca3bcfcb6910da2cad111359b541121e9fc48b.

**Comment by zumbak04** [comment]
> All looks good! Though Egerton is still a chancellor.

Fixed in 156b7f6da62452af8839020cd29cff804f57be74.

**Review by ercarp — APPROVED** [review]
Had a look and Shandris is now Tyrande's Marshal and Nathanos has the Loyal Servant opinion of Sylvanas. 👍 If you're not adding anything else, I would approve these changes.

<details><summary>Click to expand</summary>

image
image

</details>

**Review by Darknight367 — APPROVED** [review]
All look good!

**Review by TheGroxEmpire — APPROVED** [review]
I can confirm all of the councilors and opinions have been implemented correctly.

**Pull request merged**
