### PR TITLE
Draenei Ethnicity

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- @ercarp: Reworked the current draenei ethnicity. New one is called `draenei_ethnicity_rework` and is based on the models used in _World of Warcraft_.
- Assigned hairstyles and beards to draeneis.
- @zumbak04: Imported missing female draenei horns from WoW.
- @ercarp: Added **Man'ari Eredar** ethnicity.

# How to test:
- Check the Draenei Eredar and Man'ari Eredar ethnicities in the Ruler Designer and give feedback on what you think could be improved or changed.
- Consider the following when testing: **1)** are the generations unique enough, **2)** are the hairstyles and beards fitting, **3)** and do they (in your subjective opinion) look good? If not, try to be specific about what could be changed to fix whatever is wrong with them.

# Tasks:
- [x] Design the Draenei ethnicity. [Guidelines](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/wiki/Ethnicity-Guidelines). I (@zumbak04) have added horns, tails, tendrils you will need for the Draenei but we've not worked on their genes: how their faces and bodies look. That's a task to do.
- [ ] Fix a bug where you can pick 2 horns: if you generate a Draenei and then pick horns in the Horns tab.
- [x] Add Man'ari Eredars. 
- [x] Localize female Draenei horns.
- [x] Add female Draenei horns to customization.
- [x] Localize male Draenei horns.
- [x] Add male Draenei horns to customization
- [x] Fix child tendrils
- [x] Force child to have small horns
- [x] Check for errors

### CODE REVIEW

**Review by zumbak04 — COMMENTED** [review]
Sort hairstyles and beards for them in `Warcraft-Guardians-of-Azeroth-2\gfx\portraits\portrait_modifiers`. Sometimes they get very not-draeneish options.

<details>
<summary>Click to expand</summary>

image
image

</details>

If you don't know how tell me, I can explain and show examples.

**Review by IronyOwl — COMMENTED** [review]
Looks like good variety on females. Less so on males, since they're all stocky and bearded, but they're still distinct from each other.

Hairstyles look really good on females. Beards and what I can see of hair looks good on men.

Attempts at horns/forehead patterns on males is hit or miss. The ones that are obviously horns or heavy plates look good, but there's some that look like thin plates jutting up and it doesn't look natural. The angled views tend to look better because they have more 3D shape to them, but the straight-on view for some of them looks really weird.

Noses strike me as off on both genders. It's less noticeable on women, but I think some of them are too sharply defined and so stand out from the rest of the face. Most noses on men are good, but some have really pronounced external edges to the nostrils and it makes them look very human and un-Draenei.

**Review by CantTouchThisJinTao — COMMENTED** [review]
I think the chosen hairstyles/beards are fitting for both genders. I would however say potentially adding more tendril options would be good if possible to allow more unique looking generations for the males (they look different enough but sometimes they can look similar).
After reading IronyOwls comment I had a closer look at the noses and thought that maybe the noses are a little bit too big/the nostrils were too big. Although with ck3's editor it's probably impossible to get the perfect Draenei nose, also Velen has big nostrils anyway so i guess it's good, maybe adding more variety to nose shapes etc in the future would be a good addition. Good for now though.

**Review by CantTouchThisJinTao — APPROVED** [review]

**Comment by IronyOwl** [comment]
The longer I look at the noses the better they look, so maybe nevermind me.

I think my issue with the headplates is a combination of no visible angling and being able to see hair behind it, which together makes it look like a thin plate standing straight up near the front of the head. When I look at the head-on image below, my eyes see the red lines on the angled version.
<details>
<summary>Click to expand</summary>


</details>

Meanwhile, the same exact pattern without hair still looks straight upright to me, but more centered on the head and generally like I'd expect a frill or horn-like-thing to look.
<details>
<summary>Click to expand</summary>


</details>

**Comment by ercarp** [comment]
> The longer I look at the noses the better they look, so maybe nevermind me.

Regardless, looking at the draenei noses in-game, I feel like they should have been a bit softer. I reduced the range of `nose_ridge_def` and `nose_tip_def` genes in 328bedbcb3a0bcb6cd7f229c9d2eed9f66786a43 to prevent the generation of very sharp-looking noses.

> Looks like good variety on females. Less so on males, since they're all stocky and bearded, but they're still distinct from each other.

I made slight adjustments to the dimorphism gene in the latest commit. You can see if it made it any better. I do see what you mean though, some of the male draenei look very similar.

**Review by IronyOwl — APPROVED** [review]
I don't notice any difference in the male faces, but females definitely have softer nose bridges now.

Man'ari look really good. Good variety and most of them look demonic, but they're also just aesthetically pleasing.

**Review by TheGroxEmpire — APPROVED** [review]
I looked over all model between Draenei and Man'ari and they looked to be accurate to their canon representation and superb. I don't think there is more to improve other than having wider shoulder on male Draenei which is not possible on CK3. Well done I'd say.

**Pull request merged**
