### PR TITLE
High Elven Heritage Armor

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added heavy armor for high elven commanders.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

## Tasks:
- [x] Add new headgears and clothes to the Barbershop

# How to test:
Open the game, check how high elven commanders look.

### CODE REVIEW

**Review by Holt228 — APPROVED** [review]
1. Checking if the armor is actually in the game
ER: Blood elf commanders use different variations of new high elven armor
AR: Blood elf commanders use 3 variations of the new high elven armor
2. Checking if character outfit can be changed to high elven armor via Barbershop
ER: All High elven armor variations can be chosen in the Barbershop
AR: Only one random armor variation can be chosen in the Barbershop
3. WC errors
ER: There are no errors in wc files in Documents\Paradox Interactive\Crusader Kings III\logs\error.log except portrait_decals.cpp:101
AR: There are no errors in wc files in Documents\Paradox Interactive\Crusader Kings III\logs\error.log except portrait_decals.cpp:101
4. RAM usage
ER: The mod takes less than 5.5 GB in the Task Manager (Windows)
AR: The mod takes up 4.8 GB in the Task Manager (Windows) after 30 minutes of playtime on Speed 5

**Comment by zumbak04** [comment]
> By default some of these hairstyle has "reduced" version of them, like when wearing this headgear

I tried to set the same hair version when you wear the masks.

> Disfigured character could maybe have their headwear removed:

Done!

Other body clippings should be fixed too.

**Review by TheGroxEmpire — COMMENTED** [review]
- I can confirm that it is no longer possible to clip with muscle / weight modifier
- Disfigured trait is also confirmed to remove the helmet
- Some hairstyles are still causing the clipping issue. I'm not sure which hairstyles are relevant so I'll just list all the problematic hairstyle:
<details>

<summary> Male Hairstyle </summary>

- Young Vigman
- Long with Two Braids
- Medium Wavy
- Curly Bowl
- Mullet
- Very Long Wild
- Pageboy
</details>

<details>

<summary> Female Hairstyle </summary>

- Messy Braid
- Brigand's Daughter
- Crown Braid
- Fish Tails
- Double Buns
- Ribboned
- Very Long Wavy
- Large Bun
- Jeanne d'Arc
</details>

**Review by TheDrPibb1999 — CHANGES_REQUESTED** [review]
I can confirm with the above review in regards to the fixed changes as well as the still problematic hairstyles, I have also noted that Facial hairs clip through the helmet I will list below 
<details>
<summary>Beards</summary>

- Big Bushy Beard
- Long Wavy Beard
- Big Wavy Beard
- Big Chinstrap Beard 
- Big Wild Beard
- Single Braid Beard
- Long Straight Rough Beard
- Wizard (obviously)

</details>

Also the royal cloak does clip through the breast gem
<details>
<summary>Cloak</summary>

Capture


</details>

other than that, I think the set looks amazing, will there be a recolor of the blood elves' culture? In 605 the sin'dori aesthetics and eye color are the exact same as the high elves, with the exception of Kael'thas, which his subjects should have a different color armor then the high elven culture

**Pull request merged**
