### PR TITLE
New loading screens

### PR DESCRIPTION
**Pull request by Gaben1025**
## Changelog:
- Made "runestone" better quality
- Added new loading screen images

### CODE REVIEW

**Comment by Gaben1025** [comment]
I would remove the image titled "bagdhad" because we already have it as the menu image

**Comment by zumbak04** [comment]
> I would remove the image titled "bagdhad" because we already have it as the menu image
Fair, may replace it.

> Also, should I format these loading screens to the correct dds format?
What format? They look correct.

**Comment by Gaben1025** [comment]
> > I would remove the image titled "bagdhad" because we already have it as the menu image
> 
> Fair, may replace it.
> 
> > Also, should I format these loading screens to the correct dds format?
> 
> What format? They look correct.

Not sure the exact name, the one that names dds image not display anything in file explorer

**Comment by zumbak04** [comment]
> Not sure the exact name, the one that names dds image not display anything in file explorer

They're visible for me.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by Gaben1025** [comment]
> > Not sure the exact name, the one that names dds image not display anything in file explorer
> 
> They're visible for me.
> 
> Click to expand

Right, the format the you told me to use for the other images makes the preview image something default, so should I use the same format for these?

**Comment by zumbak04** [comment]
> Right, the format the you told me to use for the other images makes the preview image something default, so should I use the same format for these?

I don't get what format.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
