### PR TITLE
Gorehowl

### PR DESCRIPTION
**Pull request by sejtalk**
## Changelog:

- [x] Added Gorehowl
- [x] Added icon for it
- [x] Added it to inventory of Grommash

Balancing Spreadsheet:
https://docs.google.com/spreadsheets/d/18zS-FAte6nsejx7rpzSmVuioRXps3iWSvSkx_xRJSWI/edit#gid=1165316868

# How to test:
Select Grommash Hellscream in 603 bookmark and check his inventory

### CODE REVIEW

**Review by TheGroxEmpire — APPROVED** [review]
Can confirm it's on the game, equip-able. and has the same stats.
<details>

image

</details>

**Review by arithon — APPROVED** [review]
looks good to me

**Review by TheDrPibb1999 — APPROVED** [review]
LGTM

**Review by ElMariuso — APPROVED** [review]
LGTM

**Pull request merged**
