### PR TITLE
12th Bug Crusade

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed Arthas and some other lore characters producing children with huge lips.
- Fixed the Scourge vassalizing a top liege (and thus everything) if the CB targeted counties owned by the top liege.
  - If the CB targets the primary title, vassalizing is intended.
- Fixed the Scourge ignoring truces after it appeared.
- Fixed human spouses converted to scourge culture were naked.

## Developer changelog:
- Fixed `end_scourge_effect` errors.

# Tasks:
- [x] The Scourge AI shouldn't declare war if has a truce
- [x] The Scourge shouldn't vassalize top liege and vassals if they have other titles beyond taken titles

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Use `event WCCSC.1` console command to spawn the Scourge.

### CODE REVIEW

**Review by Panabana — COMMENTED** [review]
Tests worked according to instructions! 

1 noticeable thing (maybe I'm wrong): Only half of top vassals to Ner'zhul turned undead, rest kept their race (like giants).

**Comment by zumbak04** [comment]
> 1 noticeable thing (maybe I'm wrong): Only half of top vassals to Ner'zhul turned undead, rest kept their race (like giants).

Can't confirm. They turn.
<details>
<summary>Click to expand</summary>

image

</details>

**Review by TheGroxEmpire — COMMENTED** [review]
- I tested Arthas children with random person and Jaina. Total of 12 Children (4 Jaina + 8 Random person) none of them had big lips.
- Ner'zhul now has Truce to whoever he has waged war on and didn't turn into undead / his vassal. However I noted that the truce was one sided: Ner'zhul got the truce but his enemy didn't.
- As Ner'zhul in 583 start I tunneled ahead to where Anub'Rekhan is on the Duchy of En'kilah. After taking that through the Scourge Invasion CB, I automatically gained the entire realm of Anub'Rekhan (Top liege). So I think this one still is not fixed:
<details>

image
</details>

**Comment by zumbak04** [comment]
> Ner'zhul now has Truce to whoever he has waged war on and didn't turn into undead / his vassal. However I noted that the truce was one sided: Ner'zhul got the truce but his enemy didn't.

The truce is always one-sided.

**Comment by zumbak04** [comment]
> As Ner'zhul in 583 start I tunneled ahead to where Anub'Rekhan is on the Duchy of En'kilah. After taking that through the Scourge Invasion CB, I automatically gained the entire realm of Anub'Rekhan (Top liege). So I think this one still is not fixed:

In this case, it's intended. At least, that's how it works in vanilla.

**Review by TheGroxEmpire — APPROVED** [review]
Alright then, all works accordingly.

**Review by TheDrPibb1999 — APPROVED** [review]
All bugs were expelled for me, approved.

**Pull request merged**
