### PR TITLE
5th Small Improvments

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added the Race Family and Race Class game concepts, they're linked to the Race trait.
- Blocked the Scaly trait for everyone except mammals.
- The Oversized trait changes following this formula: `(heigh + 0.2) * 1.4`.
- The Undersized trait removes 0.5 height.
- Undead, Demons, Nature, and Arcane Beings can't get sick.
  - If you become undead with diseases, they're cured.
- Long-lived races have fewer chances of getting Lover's Pox.

# Tasks:
- [x] Add trait flags to traits
- [x] Replace `is_yaungol_trigger`, etc.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
`add_trait giant` to add the Oversized trait.
`add_trait dwarf` to add the Undersized trait.
`event WCBEI.2` to become an undead.

### CODE REVIEW

**Comment by ValianBlue** [comment]
_Looking over this, I agree with the idea of a multiplier as opposed to the linear scaling. It'll be more consistent, and it will look better for the extreme ends of the height spectrum like gnomes being incredibly short and vrykul being incredibly tall._

**Comment by zumbak04** [comment]
> _Looking over this, I agree with the idea of a multiplier as opposed to the linear scaling. It'll be more consistent, and it will look better for the extreme ends of the height spectrum like gnomes being incredibly short and vrykul being incredibly tall._

I used a formula combining adding and multiping in 011cf2164604b2371e209d9c569440f54949041d.

**Review by CantTouchThisJinTao — APPROVED** [review]
LGTM :)

**Review by ValianBlue — APPROVED** [review]
_In consideration of how the scaling functions in CK3, I think this is close enough to be satisfactory. Changes approved._

**Pull request merged**
