### PR TITLE
Dark Portal Model

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added Dark Portal model
- Swapped positions of Dark Mire and Nahohji baronies to represent correctly where the Dark Portal is in lore

Current positions:
imagen

New positions:
imagen

## Tests:
- [ ] There are no new errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Check the Dark Portal duchy

### CODE REVIEW

**Comment by Remerod** [comment]
It would be cool if we can make it a hold model instead of an terrain great work model (or what you would call it) 
Using the method the ck3 mod _The Kingdom of Heaven: Third Crusade_ have.

Linking the discord topic pic of it
<details>
<summary>Click to expand</summary>

image

So they have somehow made the hold model tied to the great works/special building model, which is very cool. and i can see us do a lot of cool warcraft stuff with this. And hopefully unlike you folks disagree, i think the Dark Portal would make a more awesome hold model rather having it being some huts (hich ain't that bad though). 

</details>

**Comment by zumbak04** [comment]
> It would be cool if we can make it a hold model instead of an terrain great work model (or what you would call it) Using the method the ck3 mod _The Kingdom of Heaven: Third Crusade_ have.

Dont get what you mean by a hold model. The Darp Portal is a buildable great work.

**Comment by Remerod** [comment]
exactly and instead of having the model show at an other place, beside the barony hold you can replace the barony hold model shown in the picture, as they've done with Jerusalem. there are no other cities/castles/temples/churces that look like Jerusalem, the Jerusalem barony hold in the picture are useing the great work (i assume) model instead somehow.

**Comment by zumbak04** [comment]
> exactly and instead of having the model show at an other place, beside the barony hold you can replace the barony hold model shown in the picture, as they've done with Jerusalem. there are no other cities/castles/temples/churces that look like Jerusalem, the Jerusalem barony hold in the picture are useing the great work (i assume) model instead somehow.

Still don't get it. Why would we replace the barony holding model with the Dark Portal?

**Comment by Remerod** [comment]
> Still don't get it. Why would we replace the barony holding model with the Dark Portal?

Because in my opinion it would look waaay cooler to have the Dark portal model for your barony-hold (and potential capital) to look like the dark portal rather then some huts. plus it would look a little weird to me if there is a castle some stone throws the Dark Portal. To "me" having the hold look like the dark portal makes more sense, and i believe it's worth at least trying it out? if it looks dump we could just redo it so it's looks like now?

**Review by robmart — APPROVED** [review]

**Review by robmart — APPROVED** [review]
LGTM

**Pull request merged**
