### PR TITLE
Dragon Ethnicities

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Made ethnicities for each dragonflight based on their [visage](https://wowpedia.fandom.com/wiki/Visage_Day) looks in-game.
  - **Green Dragons** are made up of **_Night Elves_** and **_High Elves_**.
  - **Black Dragons** are made up of **_Humans_** and **_High Elves_**.
  - **Red Dragons** are made up of **_Humans_** and **_High Elves_**.
  - **Blue Dragons** are made up of **_Humans_**, **_High Elves_**, and **_Gnomes_**.
  - **Bronze Dragons** are made up of **_Humans_**, **_High Elves_**, and **_Gnomes_**.
- The distribution of races and hair and eye colors is based on data that predates the launch of _World of Warcraft: Dragonflight_.

<details><summary>Click to view images</summary>

### Green Dragons
Mostly night elves with green hair and silver eyes, with a few high elves here and there.

image
image

### Black Dragons
Mostly humans with black hair and either orange, yellow, or red eyes. Sometimes you also get high elves.

image
image

### Red Dragons
A mixture of humans and high elves (with a slight preference towards humans). Hair colors include red, ginger, blonde, and silver. Eye colors can be either yellow or blue.

image
image

### Blue Dragons
Mostly high elves with a rarer chance for humans, and an even rarer chance for the occasional gnome. The most common hair color is blue, and for eyes it's the only color.

image
image
image

### Bronze Dragons
Mostly high elves with a few humans and gnomes. Hair colors can be quite varied, including blonde, silver, and black, but the most common one is brown. Eyes are blue 99% of the time, with a very rare chance for purple.

image
image
image

</details>

## No horns?

I wanted to add horns (specifically `male_horns_dh_4` and `female_horns_dh_4`) but it caused a lot of male characters to have a buzzcut and made some female characters bald. I don't know how to fix this, so that idea is on hold for now...
Could be done in a later branch -Grekopithikos

<details><summary>Click to view images</summary>

image
image

</details>

## To-do-list
- [ ] Find out why horns are disabling certain hairstyles and fix it.
  - [ ] Add horns to the ethnicities.
- [ ] A coder needs to take a look at the `using =` and `gene_race =` parts of the ethnicities. I don't know how these should be set up.

## ⚠️ Known issues

1. Some haircuts are clipping through headgear. This is not a problem with this branch.
2. The game may crash as this branch is based on d759a2953c8d404582c2990a198d59929c83c56e which caused instability.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
1. Start up **Crusader Kings III** and look for **_Dragon_** characters using the **Character Finder**.
4. Provide feedback on the ethnicities and report any bugs. When giving feedback, consider things such as: the choice of eye and hair colors and the selection of available races.

### CODE REVIEW

**Review by Myphicbowser — CHANGES_REQUESTED** [review]
So I would give this a big go ahead, minus the Horns issue it looked fine, I liked the colours, everything was striking, dragons felt more Draconic and looked way better, it was great

However I did find errors that I believe were caused by this mod

```
[21:31:31][portrait_decals.cpp:109]: Invalid portrait body part `eyes` at:  file: common/genes/wc_genes_special_eyes.txt line: 111
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 118
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 153
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 195
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 268
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 370
[21:31:32][ethnicity.cpp:48]: invalid gene template key 'ear_angle_Neg' for gene category gene_bs_ear_angle at  file: common/ethnicities/wc_ethnicities_dragon.txt line: 404
```

If this *isn't* the cause, then I'll change my thing to approve or if the Error log isn't a big concern rn

**Comment by Grekopithikos** [comment]
fixed

**Review by Myphicbowser — APPROVED** [review]
All fixed, no errors, works fine
LGTM

**Comment by Raged50** [comment]
Approved

**Pull request merged**
