### PR TITLE
Invisible Giant Fix

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:

This addresses the bug of invisible **_Giant_** characters reported by **Rimaka#1383** on Discord.

image

- Adjusted **_Giant_** portrait modifiers in `wc_race_portrait_modifiers.txt` to include their "clothes" as part of the same modifier as there was no need to have them in separate files.
- Added a fallback modifier for **_Giants_** whose culture isn't `storm_giant` or `frozen_giant` so that they won't be invisible.
- Added a custom portrait modifier for **Ignis the Furnace Master** (ID: `ignis_furnacemaster`) so that they are no longer invisible due to their culture being different.
- Removed `frostgiantarmor`, `firegiantarmor`, and `stormgiantarmor` modifiers from `01_clothes.txt` as they were no longer needed. Removed the `has_no_clothes_trigger` from `wc_portrait_triggers.txt` for the same reason.

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
1. Start up the game and have a look at **_Giant_** characters to make sure everything is working correctly and that there are no bugs.
  - **_Giants_** with **Hodirson** (`frozen_giant`) culture should only use `static_frostgiant` and `static_firegiant` models.
  - **_Giants_** with **Gymerir** (`storm_giant`) culture should only use `static_irongiant`, `static_stormgiant`, and `static_stonegiant` models.
  - **_Giants_** without either of these cultures should use any of the available static models for Giants. It doesn't matter which ones as long as they are no longer invisible.

### CODE REVIEW

**Review by Gaben1025 — COMMENTED** [review]
image

**Comment by ercarp** [comment]
> image

I don't understand. On my version of the branch, both have models.

image

**Review by Gaben1025 — APPROVED** [review]
LGTM

**Review by ElMariuso — APPROVED** [review]
Look okay to me too

**Pull request merged**
