### PR TITLE
Unions Tab

### PR DESCRIPTION
**Pull request by zumbak04**
# Changelog:
- Added a new sidebar tab for the Horde and Alliance, Unions. It shows the current members, leader, regent, heir, and military strength. It can be used to join, leave, and found unions.

<details>
<summary>Click to expand</summary>

image
image

</details>

# How to test:
Try to crash-test the new tab: close, open, everything that will come to your mind.
Test that the join, leave, and found buttons it provides work fine.
If you have design feedback or want to add more information, tell me.

The AI joins and creates unions during the game when the Horde conquers Stormwind.

## This PR is solely about the tab. You may leave bugs relating to the current decisions, but don't suggest adding something new here. It will be another PR!

### CODE REVIEW

**Review by Deuce20201 — COMMENTED** [review]
Well, I spammed the Union tab and nothing bad happened. 
Joining/founding/ leaving the faction works for me. 
AI founded Horde/Alliance before Stormwind was conquered in 583 start.

Is there going to be an option to invite?

Also found a typo:

**Comment by TheDrPibb1999** [comment]
> Well, I spammed the Union tab and nothing bad happened.
> Joining/founding/ leaving the faction works for me.
> AI founded Horde/Alliance before Stormwind was conquered in 583 start.
> 
> Is there going to be an option to invite?
> 
> Also found a typo:
> 

Also "I and my" is improper English, it would be "My nation and I" its an unspoken rule in English but a vast majority of English speakers will point it out

**Comment by TheDrPibb1999** [comment]
_"This is not the way we say it in English.

One of the unspoken rules of English is that we always put the first-person pronoun second. We never use ‘I’ first when there is another person involved in the subject.

Hence, the absolute correct way to say this would be:

My father and I

Consider these examples:

Incorrect: I and my brother went hunting.

Correct: My brother and I went hunting.

Incorrect: I and John skate in the mornings.

Correct: John and I skate in the mornings."_

**Review by TheGroxEmpire — COMMENTED** [review]
- Call to War tab is hidden behind the Union tab if you attempt to Call to War a member of the union from the Union tab. You need to close the Union tab to see the Call to War tab:

<details>

image
</details>

- The realm requirement to make an Alliance is redundant. You could make Alliance with having realm as big as 2 counties:
<details>

image
</details>

- The Union game concept mentions the ability for the Union leader to invite someone to their union. I didn't see such option in the Union tab nor in the character interaction tab. Complimenting that, there should also be an option to kick a Union member as a leader.

- Stormwind should not be a member of the Alliance on RoC and TFT start date. They are pretty much out of the 3rd war entirely. We should also see Night Elves joining the Alliance at this start date. Stormwind should make their Alliance sometimes after the TFT.
<details>

RoC:
image

TFT:
image

</details>

**Comment by Deuce20201** [comment]
Also, I forgot to mention this yesterday.

in the 583 start date when the AI created the Horde, the Wildhammer Dwarves joined the Horde instead of the Alliance. 
Is there a way to make AI less likely to join a faction? Lore wise it makes no sense for the Wildhammer Clan to be in the Horde.

**Comment by zumbak04** [comment]
> * Stormwind should not be a member of the Alliance on RoC and TFT start date. They are pretty much out of the 3rd war entirely. We should also see Night Elves joining the Alliance at this start date. Stormwind should make their Alliance sometimes after the TFT.

Stormwind always was a part of the Alliance, never left it.
<details>
<summary>Click to expand</summary>

image

</details>

Reminder, the 605 bookmark is the end of the Frozen Throne. 3 years before the WoW, the night elves just sailed to the Eastern Kingdoms chasing Illidan. It's unlikely they joined the Alliance just a few months after.

**Comment by zumbak04** [comment]
## This PR is solely about the tab. You may leave bugs relating to the current decisions, but don't suggest adding something new here. It will be another PR!

I added it to the description too.

**Comment by zumbak04** [comment]
> AI founded Horde/Alliance before Stormwind was conquered in 583 start.

> Also found a typo:

> Also "I and my" is improper English, it would be "My nation and I" its an unspoken rule in English but a vast majority of English speakers will point it out

Fixed in 7d8bc6d552431ce4306588bc210040b3b754216d.

**Comment by zumbak04** [comment]
> * Call to War tab is hidden behind the Union tab if you attempt to Call to War a member of the union from the Union tab. You need to close the Union tab to see the Call to War tab:

Fixed this and a few more tabs in 47f4de93a8008549ed74fd28048565a1ef39bf35.

**Review by Deuce20201 — APPROVED** [review]
Changes appear for me. 

I think the Union tab works as well as can be expected.

**Review by TheGroxEmpire — APPROVED** [review]
Confirming the window tab fix on 47f4de9.
Looks like there is no more issue on the GUI part from my testing.

**Pull request merged**
