### PR TITLE
Blood Troll Improvements

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Added **12** blood troll tattoo variations (**8** female, **4** male).
- Added **2** new blood troll ethnicities: `blood_troll_dark` and `blood_troll_green`. Both of these are based on blood troll NPCs seen in-game.
- Added **1** body paint option.

The `blood_troll_dark` ethnicity has dark gray skin and red eyes:

<details><summary>Click to expand</summary>

image
image

</details>

The `blood_troll_green` ethnicity has pale green skin and blue eyes:

<details><summary>Click to expand</summary>

image
image

</details>

## To-do:
- [x] Add localization to the tattoos.
- [x] Fix whatever is causing the Debug Portrait Editor to crash.
- [x] _(optional)_ Add the bodypaint to the Ruler Designer / Barbershop.
- [x] _(optional)_ Add localization to the bodypaint.

## Known issues:
- ❗ **Debug Portrait Editor currently crashes the game. Working on fixing it.** ❗
- The tattoos used by the green and dark blood trolls in-game are more brown than red, but making brown variants of all of the facial markings (as well as the body markings which will be added in another PR) may be a bit excessive.

### Bodypaint

**body_bloodtroll_tattoos_01**

<details><summary>Click to expand</summary>

image
image
image

</details>

### ✔️ Female Tattoos (8/8)

**facial_bloodtroll_tattoos_01**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_02**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_03**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_04**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_05**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_06**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_07**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_08**

<details><summary>Click to expand</summary>

image
image

</details>

### ✔️ Male Tattoos (4/4)

**facial_bloodtroll_tattoos_09**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_10**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_11**

<details><summary>Click to expand</summary>

image
image

</details>

**facial_bloodtroll_tattoos_12**

<details><summary>Click to expand</summary>

image
image

</details>

# How to test:
- Provide feedback on the added facial tattoos. There are a few ways you can view them: 
  - **A.** You can view them in the [Debug Portrait Mode](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode) under `gene_facial_markings`.
  - B. You can view them in **Ruler Designer** under _Accessories -> Markings_.
  - C. You can open up the **Character Finder** in-game and look for characters with the **_Nazmani_** culture.
- Provide feedback on the two new ethnicities (`blood_troll_dark` and `blood_troll_green`). You can view them in [Debug Portrait Mode](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode) or in-game.

### CODE REVIEW

**Review by Remerod — COMMENTED** [review]
I absolutly love this face markings, most of them are amazing. I do however have some nit-picking about them that i think stood out. 

on the Facial_bloodtroll_tattoo_5 the jaw part of the tattoo is a bit to close the eye line tattoo thing, the original have a lot more space in it.

<details>
<summary>Click to expand</summary>

image

</details>

the head parts of the tattoe on facial_bloodtroll_tattoos_3, facial_bloodtroll_tattoos_4, facial_bloodtroll_tattoos_9 & facial_bloodtroll_tattoos_10 feels a bit... off to me, thehair roots on their heads stands a bit out, i kind of wish it was a bit more... balder? i dunno if this is changeable or not.

<details>
<summary>Click to expand</summary>

image

</details>

the Ck3 version of the tattoo have the red blood colour darker, I don't know if i like the ck3 darker colour better or worse compared to the original, i feel like ck3's version is more realistic but is it possible to see a portait with a colour closer to the wow's models red? (the current ck3 is probably better but i dunno).

**Comment by ercarp** [comment]
> on the Facial_bloodtroll_tattoo_5 the jaw part of the tattoo is a bit to close the eye line tattoo thing, the original have a lot more space in it.

I feel like the difference is so small it doesn't need to be changed as long as it looks good and blood troll-ish. It's more about the feel of the tattoos rather than creating 1:1 replicas in CK3.

> the head parts of the tattoe on facial_bloodtroll_tattoos_3, facial_bloodtroll_tattoos_4, facial_bloodtroll_tattoos_9 & facial_bloodtroll_tattoos_10 feels a bit... off to me, thehair roots on their heads stands a bit out, i kind of wish it was a bit more... balder? i dunno if this is changeable or not.

As far as I know, this isn't something that can be _easily_ changed. The default skin textures all have an outline of their hair (a buzzcut of sorts). We would have to create completely bald versions for 7 different complexions to get around something that, in my personal view, isn't noticeable enough to warrant the attention.

<details><summary>Click to expand</summary>

image

</details>

> 
> the Ck3 version of the tattoo have the red blood colour darker, I don't know if i like the ck3 darker colour better or worse compared to the original, i feel like ck3's version is more realistic but is it possible to see a portait with a colour closer to the wow's models red? (the current ck3 is probably better but i dunno).

This is something I considered as well. I can try to see what it looks like, but if we make it too saturated it might not look like blood anymore.

**Review by Remerod — CHANGES_REQUESTED** [review]
I've been looking around in game and with the new eye and skin colours the Blood trolls feels really diverse and interesting.

<details>
<summary>Click to expand</summary>

image

</details>

In-game i can see the Blood_troll_dark ethnicity  but **not** the blood_troll_green one in character customization/Ruler Designer

<details>
<summary>Click to expand</summary>

image

</details>

the Marking alternative and names look good to me, although they are never picked when i click on **randomize appearance**. Also with the other markings, like the night elf ones, it could be hard for players to know what to pick, i dunno if this is intended or if it's this way because this is alpha and made for testing, just wanted to point it out just in case.

<details>
<summary>Click to expand</summary>
 
image

</details>

Is the eye colours supposed to be tied to the different etnicites? if so it works.

Overall i think this is an amazing addition to the blood troll, and as off now they are the most interesting looking ones of all the trolls in the game. Great work! 

I feel that the blood_troll_green ethnicity should be fixed in ruler designer (or if you gonna mix all 3? ) But they are shown in game, so i gonna make this a Request changes for now, but once you've made a comment about this or fixed blood_troll_green if that was a bug/problem you'll have my reviewer seal of approval ;)

**Comment by ercarp** [comment]
> In-game i can see the Blood_troll_dark ethnicity but **not** the blood_troll_green one in character customization/Ruler Designer

Actually, neither of them are supposed to be visible in the Ruler Designer, as @zumbak04 and I decided it would be better if we made them hidden. I had accidentally left `blood_troll_dark` visible as I was testing some things, so thanks for bringing it to my attention.

<details><summary>Click to expand</summary>

image

</details>

> the Marking alternative and names look good to me, although they are never picked when i click on **randomize appearance**. Also with the other markings, like the night elf ones, it could be hard for players to know what to pick, i dunno if this is intended or if it's this way because this is alpha and made for testing, just wanted to point it out just in case.

@zumbak04 set up the markings so I'm not sure why they're not being chosen when randomizing appearance, but seeing as it concerns both night elves and not just blood trolls, perhaps that will be more appropriately addressed in another PR if needed.

> Is the eye colours supposed to be tied to the different etnicites? if so it works.

Yes! In WoW, the two additional variations are only found paired with these specific eye colors. Gray/dark-skinned blood trolls have red eyes and green-skinned blood trolls have blue eyes. Of course, if they intermingle you can get different generations such as a green blood troll with red eyes (which is normal).

<details><summary>Click to expand</summary>

image
image

</details>

> Overall i think this is an amazing addition to the blood troll, and as off now they are the most interesting looking ones of all the trolls in the game. Great work!

> I feel that the blood_troll_green ethnicity should be fixed in ruler designer (or if you gonna mix all 3? ) But they are shown in game, so i gonna make this a Request changes for now, but once you've made a comment about this or fixed blood_troll_green if that was a bug/problem you'll have my reviewer seal of approval ;)

The two additional ethnicities (`blood_troll_dark` and `blood_troll_green`) are planned to be hidden to players in order to prevent clutter, but they will all be part of the same culture.

<details><summary>Click to expand</summary>

image

</details>

**Review by Remerod — APPROVED** [review]
It's all Gold~!

LGTM! ;)

**Comment by zumbak04** [comment]
> the Marking alternative and names look good to me, although they are never picked when i click on **randomize appearance**. Also with the other markings, like the night elf ones, it could be hard for players to know what to pick, i dunno if this is intended or if it's this way because this is alpha and made for testing, just wanted to point it out just in case.

They're not possible to be randomized in the Ruler Designer.

**Review by zumbak04 — APPROVED** [review]
LGTM! Great job!

**Comment by Remerod** [comment]
* The tattoos used by the green and dark blood trolls in-game are more brown than red, but making brown variants of all of the facial markings (as well as the body markings which will be added in another PR) may be a bit excessive.

I think it can be left as it is for now, on the pic you showed the colour difference between the markings was hardly noticeably.

**Pull request merged**
