### PR TITLE
Skin Shader Without Decals

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- Created `portrait_skin_attachment_alpha_to_coverage` shader that doesn't apply decals.

# How to test:
Check the draenei horns, check they have no issues and look like they did before.

### CODE REVIEW

**Comment by Remerod** [comment]
Just opened the branch up and looked on draenei in appearance customizer and just saw this (pic bellow), there seem to one "static" horn that is not tied to the horns customize slider, so the outcome that there are 2 horns at the same time 

<details>
<summary>Click to expand</summary>

image


</details>

**Comment by Remerod** [comment]
wait, now i'm Master and it seems horn's are just customable on randomize Appearance? couse choiceing horns leaves the same result as i showed earlier.

<details>
<summary>Click to expand</summary>

This seems to work (Master Branch)
image

But this does not (master Branch)
image

</details>

I know this is for the other branch, just thought i reported it here becouse it is relevant?

**Review by Remerod — COMMENTED** [review]
Should I continue to see if the horns look the same? It would be harder to do right now when the horn slider seems not to be working, but I can say that by just scrolling around on both branches while seeing the other bug i mentioned i did not see any notable difference at least

**Comment by zumbak04** [comment]
> Just opened the branch up and looked on draenei in appearance customizer and just saw this (pic bellow), there seem to one "static" horn that is not tied to the horns customize slider, so the outcome that there are 2 horns at the same time

For now I put it in the Debug mode (thus it won't be visible for the players).

**Comment by Remerod** [comment]
I can see Horn differences on males on master and this new branch, I think the problem is that the horns are higher up on the skull 

<details>
<summary>Click to expand</summary>
Master Branch

image

This New Branch, seems to have whitish/beech colour differences at the bottom of the horns
image

image

image
Man'ari
image

At first glance it seems that Females have the same horns, but after taking a second glance i can see that the new branch females horn are also higher up i believe
Master Branch
image

This Branch
image


</details>

**Comment by zumbak04** [comment]
> At first glance it seems that Females have the same horns, but after taking a second glance i can see that the new branch females horn are also higher up i believe

Because you generated females with different head heights.

**Comment by zumbak04** [comment]
> This New Branch, seems to have whitish/beech colour differences at the bottom of the horns

Fixed in 5f5d0c02bfe05ad5613655a45b36beadc9d6c6e7.

**Review by Remerod — APPROVED** [review]
It seems to be fixed now, I can see no apearent issues on the draenei horns, and they look like they did before I believe.
 
<details>
<summary>Click to expand</summary>

image

</details>

**Pull request merged**
