### PR TITLE
1st Title and Dynasty CoAs

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Assigned historical CoAs to dynasties:
   - Blackhand
   - Blackrock
   - Frostwolf
   - Deadeye
   - Greymane
   - Menethil
   - Wrynn
   - Perenolde
   - Proudmoore
   - Foreeye
   - Burning Blade (appears after the Horde Invitation)
   - Skullcrusher (appears after the Horde Invitation)
   - Dragonmaw (appears after the Horde Invitation)
- Assigned historical CoAs to titles:
   - Kingdom, Duchy and County of Alterac
   - Empire, Kingdom, Duchy and County of Lordaeron
   - Kingdom, Duchy and County of Dalaran
   - Kingdom of Kul Tiras
   - The Horde
   - Blackrock Clan (orcish)
   - Bleeding Hollow Clan (orcish)
   - Frostwolf Clan (orcish)
   - Twilight's Hammer Clan (orcish)
   - Dragonmaw Clan (appears after the Horde Invitation)
   - Burning Blade Clan (appears after the Horde Invitation)
   - Kingdom, Duchy and County of Stormwind
   - Kingdom, Duchy and County of Stromgarde
- Sometimes these patterns used in random CoAs of their religions and cultures:
   - Human cultures use their cultural emblems
   - Orcish cultures use their cultural emblems
   - Arcane religions use Dalaran eye

# How to test:
Check these dynasties, houses and titles in-game.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Frostwolf Dynasty and House is named "of Frostwolf":
<details>

image
</details>

- Deadeye and Bleeding Hollow are using the alternate universe Draenor CoA(https://wow.gamepedia.com/Bleeding_Hollow_clan_(alternate_universe)). It should be like the one on this wiki instead (https://wow.gamepedia.com/Bleeding_Hollow_clan)
<details>

image
</details>

- There's some count in Northshire on 583 start with his house named "Wrynn" but not the actual house Wrynn:
<details>

image
</details>

- The changelog says that random religious order will use the eye of Dalaran CoA. However, it's assigned to culture and religion combination that would not fit with such. For example, Gnomes and Elves.
<details>

image
image
image
image
</details>

- This doesn't look right for Mechagon. Aren't they supposed to be Mechagnomes with gear and such as their CoA? (https://wow.gamepedia.com/File:Mechagon_City.jpeg)
<details>

image
</details>

- Blackrock CoA should be replaced with the CoA like in the wiki (https://wow.gamepedia.com/Blackrock_clan)
<details>

image
</details>

**Comment by ulricee** [comment]
not much to say more that wasn't already told but for the fact I've made a very basic coa for the Mechagon based on the banner from wow. Other than that pretty good job.

Mechagon1

**Comment by ElMariuso** [comment]
>     * Frostwolf Dynasty and House is named "of Frostwolf": 
Yes, I think it's better that they call themselves that, not only for the location but also because just calling the family reigning over the clan "Frostwolf" makes it seem like it's just a title for them, and that it is not the leaders of the "frostwolf"

>     * Deadeye and Bleeding Hollow are using the alternate universe Draenor CoA(https://wow.gamepedia.com/Bleeding_Hollow_clan_(alternate_universe)). It should be like the one on this wiki instead (https://wow.gamepedia.com/Bleeding_Hollow_clan)
This is the flag that was used in GOA 1, but if it's really annoying I can change it.

>     * There's some count in Northshire on 583 start with his house named "Wrynn" but not the actual house Wrynn:
This is the name of all randomly generated dynasties at the moment.

>     * The changelog says that random member from Order religions family will use the eye of Dalaran CoA. However, it's assigned to culture and religion combination that would not fit with such. For example, Gnomes and Elves.
Done in b0ed81f8

>     * Blackrock CoA should be replaced with the CoA like in the wiki: (https://wow.gamepedia.com/Blackrock_clan)
Done in 4b5481af

**Comment by TheGroxEmpire** [comment]
> Yes, I think it's better that they call themselves that, not only for the location but also because just calling the family reigning over the clan "Frostwolf" makes it seem like it's just a title for them, and that it is not the leaders of the "frostwolf"

That's understandable. However, if you are doing this for Frostwolf you should also do the same for other orcish clans dynasty e.g., "of Blackrock", "of Bleeding Hollow".
One thing more that I could see happening in the future is that in some localization it might introduce some weird wording. like "House of of Frostwolf". I cannot prove that there's some localization like this yet, but it's a possibility.

> This is the flag that was used in GOA 1, but if it's really annoying I can change it.

Yes please, it's better for consistency.

> This is the name of all randomly generated dynasties at the moment.

That makes sense.

> Done in b0ed81f8
> Done in 4b5481af

These both fixed the issues.

**Review by TheGroxEmpire — COMMENTED** [review]
- Duchy of Stromgarde still uses the vanilla CoA:
<details>

image
</details>

- Not about the CoA but it should be written as Twilight's Hammer (https://wow.gamepedia.com/Twilight%27s_Hammer)

**Comment by ElMariuso** [comment]
>     * Duchy of Stromgarde still uses the vanilla CoA:
done in 1e5c2dc4

**Review by TheGroxEmpire — APPROVED** [review]
Okay, 95bfb64 fixed the Stromgarde Duchy CoA. Since the name is on another branch this PR looks good to me.

**Comment by zumbak04** [comment]
> Since the name is on another branch this PR looks good to me.

Changed in 2f68fc86792ed1b971201b1b7b9d68004c18fd89.

**Pull request merged**
