### PR TITLE
1.4.2 Adaptation

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Adapted the mod to 1.4.2.
- The mod no longer freezes on the loading screen of the map (when you click the new game and select a bookmark).

# How to test:
Before testing, copy-paste `Warcraft-Guardians-of-Azeroth-2.mod` from `Crusader Kings III\mod\Warcraft-Guardians-of-Azeroth-2` into `Crusader Kings III\mod`.

Confirm the freezing fix.

### CODE REVIEW

**Review by Deuce20201 — COMMENTED** [review]
Freezes for me when I click start game picking King Llane in first bookmark. Technically after character page.

**Review by Deuce20201 — APPROVED** [review]
Works for me now. No freezing

**Review by CatWitchLily — CHANGES_REQUESTED** [review]
I froze on the Initializing game loading screen after clicking on the Play as any ruler button to get into the map.

**Comment by robmart** [comment]
IT WORKS BITCHES, WOOOOOOOOOOOOO

*clears throat*

Fix works, LGTM

**Review by robmart — APPROVED** [review]

**Review by hamjustine — APPROVED** [review]
it works :D

**Review by CatWitchLily — APPROVED** [review]
I can load up the map!

**Pull request merged**
