### PR TITLE
Pygmy Ethnicity

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- **Mar 23 2023**:
  - e7be20e42001a342280693eaf90f5c84d3807835:
    - Created a custom ethnicity for the **_Pygmy_** race.
  - 7eaf0a921765bcd65d7d7f95d318aca7e9716d1b:
    - Assigned custom beards, hairstyles, and `mena_clothing_gfx` clothes.
- **Mar 26, 2023**:
  - 39f5deddc85eecee851aef754052a2ab17fe08d7:
    - Added a specially curated set of clothes and headger for **_Pygmies_**, including slight differences depending on the character's rank.
    - Altered `forehead_roundness_neg` to prevent clipping.
    - Removed two helmets that were clipping badly.
    - Changed legwear to the FP1 pants.
- **Mar 27 2023:**
  - 3e705696859699f6a2beb34afc647d822a8befd0:
    - Added `male_beard_steppe_01_wc` for Pygmies.
  - ea1fad254ce325ad93696b43d8c738b331da62f9:
    - Made **_Pygmies_** a bit wrinklier and switched up the complexions to ones that have more blemishes so that they don't look quite as smooth.

<details><summary>Images (updated Mar 26, 2023)</summary>

image
image

image
image

image
image

image
image

</details>

## To-do list:

- [x] Disable the MENA war helmet for **_Pygmies_** (it causes pretty bad clipping). (Fixed in 39f5deddc85eecee851aef754052a2ab17fe08d7)
- [x] Adjust brow/forehead gene to not be quite as extreme in order to avoid clipping through one of the turban models. (Fixed in 39f5deddc85eecee851aef754052a2ab17fe08d7)
- [x] Add Temple Headwrap for **_Pygmies_**. (Added in 39f5deddc85eecee851aef754052a2ab17fe08d7)
- [x] Add 70% chance for topless **_Pygmy_**, 30% chance for clothed. (Added in 39f5deddc85eecee851aef754052a2ab17fe08d7)
- [ ] Fix legwear clipping if possible (see ⚠️ _**Known issue 2**_)..
- [x] Change Pygmy animations to the dwarf variants if possible (see ⚠️ _**Known issue 5**_)..
- [x] Figure out what's going on with the `male_beard_steppe_01_wc` (see ⚠️ _**Known issue 3**_). (Fixed in fdc52a8d4da58fb402ef5788205f6ff4a09cecb5)

## ⚠️ Known issues:

- [x] 1. For some reason, the Pygmy are using some of the default `mena` beards and hairstyles in addition to the custom ones that I've assigned to them. (Fixed in 39f5deddc85eecee851aef754052a2ab17fe08d7)
- [ ] 2. Legwear is clipping really badly on topless Pygmies.
- [x] 3. Some Pygmies are still using the bugged `male_beard_steppe_01_wc` even though I didn't add it to their set of beards. (Fixed in 3e705696859699f6a2beb34afc647d822a8befd0)
- [x] 4. Game crashes on start-up sometimes. (Likely not an issue with this branch specifically.)
- [x] 5. Animations are clipping because Pygmies aren't using the dwarf variants of animations. (Fixed in 4f9eea6d17975ca831ce083ec78e64828b59c337)

## Tests:
- [ ] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [ ] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
1. To view the characters in-game, downgrade your **Crusader Kings III** to `1.5.0.1` and look for characters with the **_Pygmy_** creature trait using the **Character Finder** panel.
2. Provide feedback on clothing, headgear, and the general look of the ethnicity. Is there anything you would change?

### CODE REVIEW

**Review by CantTouchThisJinTao — COMMENTED** [review]
In general i like the look of the pygmies. Face wise they're decent in my opinion. The beards/hair I've seen seem to fit the race. From the CK3 outfits I'd say a lot of the basic clothes would probably work so mena is good. The hats seem to fit the race, i would however say that the Temple Headwrap fits very well based on some images i found so could be added.

<details>
<summary>TempleHeadwrap</summary>

templeheadwrap

205847-cavorting-pygmy
</details>

The Pygmy male ears clip through some of the helmets.

<details>
<summary>Ear Clipping</summary>

earhelmet

earhelmet2

</details>

One Pygmy i found had his forehead/eyebrows clipping through one of the helmets.

<details>
<summary>Forehead/brow clip</summary>

forehead

</details>

They also tend to put their fingers through their chin when holding a particular pose (although i'm pretty sure this is just a common ck3 issue).

<details>
<summary>Hand Chin</summary>

handchin

</details>

The fur trimmed hat is another potential hat for the Pygmies, looks good on them and like something the race could potentially wear (not sure so up to you).

<details>
<summary>Click to expand</summary>

furtrimmed

</details>

Overall the oufits are decent, the individuals look varied enough etc. Not really any major issues in my opinion. Just the matter of the clipping.

**Comment by ercarp** [comment]
> i would however say that the Temple Headwrap fits very well based on some images i found so could be added.

Implemented in 39f5deddc85eecee851aef754052a2ab17fe08d7.

> The Pygmy male ears clip through some of the helmets.
> One Pygmy i found had his forehead/eyebrows clipping through one of the helmets.

Fixed in 39f5deddc85eecee851aef754052a2ab17fe08d7.

> They also tend to put their fingers through their chin when holding a particular pose (although i'm pretty sure this is just a common ck3 issue).

This is an issue with the Pygmies still using normal animations as opposed to the dwarfism variety of them. I tried to fix it but I had no success, so we'll need someone else like @zumbak04 to take a look at it.

> The fur trimmed hat is another potential hat for the Pygmies, looks good on them and like something the race could potentially wear (not sure so up to you).

I ended up not including this hat as I thought it looked a bit too similar to the hat worn by Grummles, another small humanoid race.

<details><summary>Grummles</summary>

image

</details>

**Review by CantTouchThisJinTao — COMMENTED** [review]
Not noticed any major clipping issues (maybe some very minor ones on some of the turbans but still looks fine honestly, not too noticeable and obviously to resolve that either the headwear or ears would have to be edited - certainly looks good for now anyway).

I noticed some of the Pygmies have quite smooth skin, only references i find tend to have wrinkly foreheads however i kind of like the possibility of them having smoother skin due to more unique appearances to ensure less pygmies look similar. Think there's enough variation with the other races to stop these smooth skinned pygmies looking like other small races/dwarf humans etc but probably need a 2nd opinion.

<details>
<summary>SmoothPygmy</summary>

smoothforehead
</details>

Other than this not noticed any potential issues (other than those already stated in known issues). 

The 70% topless to 30% clothed chance seems to be working well, still discovering a decent number of clothed pygmies so the % hasn't completely killed them off.

**Comment by zumbak04** [comment]
> They also tend to put their fingers through their chin when holding a particular pose (although i'm pretty sure this is just a common ck3 issue).

@ercarp @CantTouchThisJinTao so I used dwarf animations on them but they still tend to clip. Even vanilla dwarves clip but with pygmies due to their huge chin it becomes worse. I see 3 solutions:
- 1. Proper fix, but it will take time. Basically, need someone with knowledge of Blender animations. Need to correct positions in the rational dwarf animations: increase the distance between the fingers and the chin.
- 2. Fast fix, block these animations from happening, but I'll open task for the proper fix anyway.
- 3. No fix, overall, clipping is a low prio issue, may ignore. I'll open task for the proper fix anyway.

**Comment by zumbak04** [comment]
> 3. Some Pygmies are still using the bugged male_beard_steppe_01_wc even though I didn't add it to their set of beards.

Investigated this. First, I fixed a colorless bug. If it's the only reason why you left this beard out, it can be marked as resolved.

Second, I found out why the beard may appear anyway.
<details>
<summary>Click to expand</summary>

image

</details>

It's because of this piece of code. The beard may appear if the ethnicity has `hair_straight_thin_beard` in the `gene_hair_type` category.

**Comment by zumbak04** [comment]
> 2. Legwear is clipping really badly on topless Pygmies.

So I checked them in vanilla, they clip too (maybe it's fixed in current versions?) Which ones you want to use? I can fix those. The rest I would pass to Paradox.

**Comment by zumbak04** [comment]
> Game crashes on start-up sometimes.

Doubt it's caused by the branch.

**Comment by ercarp** [comment]
@zumbak04
> > 2. Legwear is clipping really badly on topless Pygmies.
> 
> So I checked them in vanilla, they clip too (maybe it's fixed in current versions?) Which ones you want to use? I can fix those. The rest I would pass to Paradox.

I think `fp1_common_legwear` looks the best, so we should use those for Pygmies. But it's a DLC item, so I don't know how that will work for players without Northern Lords. Would need a fallback of some kind. If it makes things easier in the long run, you can just use whatever default non-DLC legwear they have instead.

> > Game crashes on start-up sometimes.
> 
> Doubt it's caused by the branch.

Fair enough. I marked it as solved.

> > 5\. Some Pygmies are still using the bugged male_beard_steppe_01_wc even though I didn't add it to their set of beards.
> 
> investigated this. First, I fixed a colorless bug. If it's the only reason why you left this beard out, it can be marked as resolved.

Awesome! I've added the beard to Pygmies in 3e705696859699f6a2beb34afc647d822a8befd0. It's a great fit for them, the only reason I had it commented out was because of the colorless bug.

> so I used dwarf animations on them but they still tend to clip. Even vanilla dwarves clip but with pygmies due to their huge chin it becomes worse. I see 3 solutions:
> 
>    1. Proper fix, but it will take time. Basically, need someone with knowledge of Blender animations. Need to correct positions in the rational dwarf animations: increase the distance between the fingers and the chin.
> 
>    2. Fast fix, block these animations from happening, but I'll open task for the proper fix anyway.
> 
>    3. No fix, overall, clipping is a low prio issue, may ignore. I'll open task for the proper fix anyway.

Right now, I'm going to vote for 3. There's a lot of clipping in Vanilla CK3 and I don't think people are too bothered by it. Besides, when it comes to fixing most of the clipping issues in CK3, the ball is in PDX's court.

@CantTouchThisJinTao 

> I noticed some of the Pygmies have quite smooth skin, only references i find tend to have wrinkly foreheads however i kind of like the possibility of them having smoother skin due to more unique appearances to ensure less pygmies look similar. Think there's enough variation with the other races to stop these smooth skinned pygmies looking like other small races/dwarf humans etc but probably need a 2nd opinion.

This is a good point and something I had overlooked. I've switched up the skin complexions the Pygmies use and also increased their "wrinkliness" slightly in ea1fad254ce325ad93696b43d8c738b331da62f9.

**Comment by CantTouchThisJinTao** [comment]
@ercarp Ye i think the skin looks better now with the complexions.

**Review by TheGroxEmpire — APPROVED** [review]
LGTM!

**Pull request merged**
