### PR TITLE
#1070 Polishing & error.log fixes [PR] 

### LINKED ISSUE #1093: #1070 Polishing & error.log fixes
### ERROR "Province [ID] has no associated title in common/landed_titles. FIX THIS. Game will probably crash if you don't"
<details>
<summary></summary>

image
</details>

- [x] Province 6378
- [x] Province 6379
- [x] Province 6383
<hr>

### ERROR "Province [ID] [NAME] has no visual geographical region assigned"
<details>
<summary></summary>

image
</details>

- [x] Province 6378 RESERVED6378
- [x] Province 6379 RESERVED6379
- [x] Province 6383 PLACEHOLDER AQ
<hr>

<details>
<summary></summary>

image
</details>

- [x] Province 6383
<hr>

### ERROR "Province [ID] [NAME] has no pixels in provinces.bmp"
<details>
<summary></summary>

image
</details>

- [x] Province 6378 RESERVED6378
- [x] Province 6379 RESERVED6379
<hr>

<details>
<summary></summary>

image
</details>

- [x] RESERVED6378
- [x] RESERVED6379
- [x] PLACEHOLDER AQ
<hr>

### ERROR "No points for area name, should never happen! in: [NAME] ([Area ID]), [Province ID]."
<details>
<summary></summary>

image
</details>

- [x] Eldara ( Area ID: 765), Province ID: 1876
- [x] Hetaera ( Area ID: 823), Province ID: 1866
- [x] Arkkoran ( Area ID: 211), Province ID: 1876
- [x] Storm Isles ( Area ID: 231), Province ID: 1866
<hr>

### Misshapen Provinces.png: Azshara, Darkshore, Feathermoon Isles, Western Kalimdor
<details>
<summary>Azshara</summary>

image
</details>
<details>
<summary>Darkshore</summary>

image
</details>
<details>
<summary>Feathermoon Isles</summary>

image
</details>
<details>
<summary>Western Kalimdor</summary>

image
</details>

- [x] ~~Azshara~~ (Addressed separately in #1095)
- [x] Darkshore
- [x] Feathermoon Isles
- [x] Western Kalimdor
<hr>

### Oversized Counties: "Falaeth" & "Placeholder AQ"
<details>
<summary>Falaeth</summary>

image
</details>
<details>
<summary>Placeholder AQ</summary>

image
</details>

- [x] Province 5122 FALAETH
- [x] Province 6383 PLACEHOLDER AQ
<hr>

### PR DESCRIPTION
**Pull request by ValianBlue**
> Resolves #1093.

_A host of polishing and error.log fixes meant to follow up on #1070 after its merge to `master`._

# Changelog
### "Province [ID] has no associated title in common/landed_titles. FIX THIS. Game will probably crash if you don't"
- Created "Djanta" using ID 6378
- Created "Khanei" using ID 6379
- Created "Tarsai" using ID 6383

### "Province [ID] [NAME] has no visual geographical region assigned"
- Assigned Province 6378 to South Silithus geographic region
- Assigned Province 6379 to South Silithus geographic region
- Assigned Province 6383 to South Silithus geographic region

### "Province '6383' is neighbouring but not part of island region 'island_kalimdor'"
- Assigned Province 6383 to South Silithus island region

### "Province [ID] [NAME] has no pixels in provinces.bmp"
- Painted Province 6378 using RGB(153,160,191)
- Painted Province 6379 using RGB(66,42,27)

### "Province with no county data [NAME]. Setting to arbitrary county data to avoid CTD"
- Added relevant county data to RESERVED6378 (Djanta)
- Added relevant county data to RESERVED6379 (Khanei)
- Added relevant county data to PLACEHOLDER AQ (Tarsai)

- Deleted Provinces 1866 Hetaera, 1876 Eldara, 1875 Arkkoran, & 5633 Alalyia

### Azshara

> As previously mentioned, Azshara will receive its own update in #1095.

### Darkshore
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

### Feathermoon Isles
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

### Western Kalimdor
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

### _NOTE: I also adjusted the province lines for the north coast of Kalimdor._
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

### Falaeth
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

#### Added the following provinces
- Province 6405: Veiled Sea
- Province 6406: Alynath
- Province 6407: Mosscrest
- Province 6408: Benarian
- Province 6409: Onsin
- Province 6410 Myris:
- Province 6411: Valdan
- Province 6412: Uthas
- Province 6413: Branlor
- Province 6414: Fahnel
- Province 6415: Sylaste
- Province 6416: Madril
- Province 6417: Ylaellorn
- Province 6418: Sherian
- Province 6419: Ragos

### Placeholder AQ
<details>
<summary>Before</summary>

image
</details>
<details>
<summary>After</summary>

image
</details>

#### Added the following provinces
- Province 6378: Djanta
- Province 6379: Khanei
- Province 6382: Westersea
- Province 6383: Tarsai
- Province 6384: South Sea
- Province 6385: South Sea
- Province 6386: South Sea
- Province 6387: Sekhe
- Province 6388: Wasys
- Province 6389: Djedpesut
- Province 6390: Besretjer
- Province 6391: Arrepet
- Province 6392: Ekneitennu
- Province 6393: Nemru
- Province 6394: Djetu
- Province 6395: Sakselzum
- Province 6396: Fane
- Province 6397: Kerzu
- Province 6398: Sepsairis
- Province 6399: Tjennei
- Province 6400: Benu
- Province 6401: Aqri
- Province 6402: Khassyma
- Province 6403: Akcasiris
- Province 6404: Zasou

# Known Issues

```
1114;255;135;255;;x;
1626;208;101;197;;x;
1864;219;209;177;;x;
1866;0;7;74;RESERVED1866;x;
1875;0;7;83;RESERVED1875;x;
1876;0;7;84;RESERVED1876;x;
1877;227;105;195;;x;
1878;167;77;34;;x;
2029;13;60;156;;x;
2301;139;60;103;;x;
2325;182;67;255;;x;
5050;208;52;155;;x;
5070;255;67;255;;x;
5072;115;103;153;;x;
5633;0;22;1;RESERVED5633;x;
5634;106;91;48;;x;
5637;131;69;40;;x;
```

<details>
<summary></summary>

image
</details>

<details>
<summary></summary>

image
</details>

<details>
<summary></summary>

image
</details>
<details>
<summary></summary>

image
</details>
<details>
<summary></summary>

image
</details>
<details>
<summary></summary>

image
</details>

<details>
<summary></summary>

image
</details>

<details>
<summary></summary>

image
</details>
<details>
<summary></summary>

image
</details>

- Zandalar
- Pandaria
- "Most islands in the middle"

## Additional error.log issues

```
c_arkkoran, near line: 115
c_crystalwood, near line: 94
c_hetaera, near line: 96
c_storm_coast, near line: 184
```

- k_desolace
- k_thousand_needles
- k_shimmering_flats
- k_dragonblight
- k_wyrmrest
- k_wintergrasp

### [CHARACTER] should hold at least one landed title (barony or county) but doesn't has any
- Moamin Winterwood of d_wintergrasp
- Xogdresk Xec of d_thorvald
- Rmgmr Ghmgh of d_murkgill

### [COUNTY] doesn't have a holder in history. All counties should have one.
```
c_assmel
c_olysemel
c_thaneras
c_forlorn
c_shazuna
c_thva_taesi
c_branlor
c_falaeth
c_madril
c_mosscrest
c_yaeda
c_jagged_reef
c_ravencrest
c_bilgetrade
c_jozaes
c_mylora
c_xemrir
c_grim_ulang
c_serilanna
c_xonulzis
c_atelanor
c_vesrinar
c_woodscream
c_dunwald
c_crucible_of_tin
c_silverslopes
c_victors_point
c_wildgulch
c_obsidian_hills
c_dead_highlands
c_elementium_ravine
c_flat_shore
c_loose_cliffs
c_low_islands
c_verdant_forest
c_storm_cost
c_verrall_delta
c_cape_of_fist
c_severe_coast
c_windward_slopes
c_aamsk
```

### Character 29166 with primary title d_wintergrasp has no capital
```
[18:52:35][succession_partition.cpp:377]: Character 29166 with primary title d_wintergrasp has no capital
```

# Author Notes
_I've significantly restructured `k_ahnqiraj`, `k_feralas`, `k_khintaset`, and `k_silithus`. This is meant to accommodate the heightmap changes from #1070 that created province discrepancies. The mountain range between Silithus/Ahn'qiraj & Uldum was shifted eastward, thus I've modified the provinces (including duchies) to fit this new mountain range. Additionally, I added an impassible terrain zone over it. On the topic of impassible terrain, I modified its province color from RGB(0,0,0) to RGB(10,10,10) as the prior color caused conflicts with Province 0 in the map-editor._

_Much of Kalimdor's coastline was altered by #1070 due to c5f1555. I've covered most of the discrepancies in this PR, and have listed an additional one in the **Known Issues** section. There may still be more potential discrepancies._

_In adding a series of new provinces to Ahn'Qiraj and the Isle of Dread (Feathermoon Isles), I've addressed title holders through the following ways:_
- _For Ahn'Qiraj, I divided the realm roughly evenly between the Twin Emperors Vek'lor and Vek'nilash. Vek'lor has two duchies and the empire title, while Vek'nilash has three duchies and the kingdom title._
<details>
<summary>Revised Duchies Map</summary>

image
</details>

- _For the Isle of Dread, four new provinces were created: `c_branlor`, `c_falaeth`, `c_madril`, & `c_mosscrest.` These provinces currently do not have assigned rulers (as mentioned in **Known Issues**)_

# How to test:
(This section shamelessly copied from ercarp)

Consider the following when giving your feedback:

**Gameplay:** For pertinent bugs, verify if the bugfixes are working as intended.

**Canonicity:** Compare the map changes to ensure accuracy according to the information made available by official canon.

**Familiarity:** Observe whether or not the changes are recognizable and fitting for their respective locations.

**Aesthetics:** Comment on the general look and appeal on the changes. Suggestions should be as specific as possible.

Additionally, ensure that necessary gameplay features like holdings are not obscured by map changes such as trees, water, or steep cliffs.

### CODE REVIEW

**Comment by VespertinePetrichor** [comment]
### "Province [ID] has no associated title in common/landed_titles. FIX THIS. Game will probably crash if you don't"
Provinces Djanta, Khanei and Tarsai are verified.

### "Province [ID] [NAME] has no visual geographical region assigned"
Errors resolved.

### "Province '6383' is neighbouring but not part of island region 'island_kalimdor'"
Error resolved, but new ones have cropped up in its stead:
image

### "Province [ID] [NAME] has no pixels in provinces.bmp"
Errors resolved.

### "Province with no county data [NAME]. Setting to arbitrary county data to avoid CTD"
These errors are still appearing in the log. They may go away after you resolve the other residual bugs I have mentioned in this review.

### "No points for area name, should never happen! in: [NAME] ([Area ID]), [Province ID]."
```
[geographical_region.cpp:255]: Province 1866 RESERVED1866 has no visual geographical region assigned
[geographical_region.cpp:255]: Province 1875 RESERVED1875 has no visual geographical region assigned
[geographical_region.cpp:255]: Province 1876 RESERVED1876 has no visual geographical region assigned
[geographical_region.cpp:255]: Province 5633 RESERVED5633 has no visual geographical region assigned
```
I take it these are the result of the deletion?

### Misshapen Provinces.png: Azshara, Darkshore, Feathermoon Isles, Western Kalimdor
Darkshore, Feathermoon Isles. Northern and Western Kalimdor changes are verified.

### Oversized Counties: "Falaeth" & "Placeholder AQ"
Falaeth and Placeholder AQ changes are in effect. 

The expansion of the isle of dread was a well-informed choice. However, I feel it is somewhat too wide. Perhaps its width may be reduced to match that of sardor isle? Either that, or Kalidar/Azuremyst/Bloodmyst ought to be enlarged. As a matter of fact, Kalidar does look undersized compared to the rest of the continent. I would suggest shifting it northeast in another PR such that its western coast lines up with the cape of Lordanel. This ought to give more room for an expanded Kalidar.

Also, may I ask what further changes you intend for the AQ provinces?

### Other Comments
I quite like the added impassable terrain to the eastern boundary of Ahn Qiraj. Why did you opt for it over a terrain change? What of the northern reaches of Silithus?

This PR was a feast for the eyes, in both the changes and its presentation. I am awed by the meticulous eye for detail. Your extensive documentation is exemplary to the rest of the team.

**Comment by ValianBlue** [comment]
@VespertinePetrichor 

> ### "Province '6383' is neighbouring but not part of island region 'island_kalimdor'"
> 
> Error resolved, but new ones have cropped up in its stead: image

_Indeed. I am tracking those under "Provinces 1866, 1875, 1876, & 5633" in Known Issues._

> ### "Province with no county data [NAME]. Setting to arbitrary county data to avoid CTD"
> 
> These errors are still appearing in the log. They may go away after you resolve the other residual bugs I have mentioned in this review.

_See above._

> ### "No points for area name, should never happen! in: [NAME] ([Area ID]), [Province ID]."
> 
> ```
> [geographical_region.cpp:255]: Province 1866 RESERVED1866 has no visual geographical region assigned
> [geographical_region.cpp:255]: Province 1875 RESERVED1875 has no visual geographical region assigned
> [geographical_region.cpp:255]: Province 1876 RESERVED1876 has no visual geographical region assigned
> [geographical_region.cpp:255]: Province 5633 RESERVED5633 has no visual geographical region assigned
> ```
> 
> I take it these are the result of the deletion?

_Correct, see above._

> ### Oversized Counties: "Falaeth" & "Placeholder AQ"
> 
> Falaeth and Placeholder AQ changes are in effect.
> 
> The expansion of the isle of dread was a well-informed choice. However, I feel it is somewhat too wide. Perhaps its width may be reduced to match that of sardor isle? Either that, or Kalidar/Azuremyst/Bloodmyst ought to be enlarged. As a matter of fact, Kalidar does look undersized compared to the rest of the continent. I would suggest shifting it northeast in another PR such that its western coast lines up with the cape of Lordanel. This ought to give more room for an expanded Kalidar.
> 
> Also, may I ask what further changes you intend for the AQ provinces?

_I modeled the sizes of both isles using the Chronicles map to be as lore-accurate as possible. I had been planning on reworking Azuremyst+Bloodmyst in the future (though haven't tracked it as of yet). Given that Kalidar isn't a 100% canon location, the changes you've requested can be accommodated._

_I have no further intended changes for Ahn'Qiraj._

> ### Other Comments
> 
> I quite like the added impassable terrain to the eastern boundary of Ahn Qiraj. Why did you opt for it over a terrain change? What of the northern reaches of Silithus?

_I modeled Ahn'Qiraj using the WoW terrain. I'm not certain what you are referring to in terms of a terrain change, but I had imported the terrain changes from an old commit on `terrain-2`. I opted to modify the provinces as I felt that Ahn'Qiraj was too diminutive in its original state, and that Uldum was too expansive in comparison to its neighboring regions._

_The northern regions of Silithus could use a rework, but this is a low priority._

> 
> This PR was a feast for the eyes, in both the changes and its presentation. I am awed by the meticulous eye for detail. Your extensive documentation is exemplary to the rest of the team.

_Thank you kindly for your review!_

**Review by VespertinePetrichor — APPROVED** [review]

**Comment by ValianBlue** [comment]
# 33b1982 Changelog
@VespertinePetrichor @Gaben1025 
- Reworked the appearances for Azshara, Durotar, and the Echo Isles.

## To Do
- Redraw provinces once heightmap is satisfactory
- Add map objects (trees)

## How to Review
Consider the following when giving your feedback:

**Canonicity:** Compare the map changes to ensure accuracy according to the information made available by official canon.

**Familiarity:** Observe whether or not the changes are recognizable and fitting for their respective locations.

**Aesthetics:** Comment on the general look and appeal on the changes. Suggestions should be as specific as possible.

Additionally, ensure that necessary gameplay features like holdings are not obscured by map changes such as trees, water, or steep cliffs.

### -- @ValianBlue

**Review by Gaben1025 — APPROVED** [review]

**Review by ercarp — APPROVED** [review]
All of the visual changes look great! More provinces in AQ is a treat. ❤️

@Gaben1025 asked me to test this branch for stability so I ran a few Observer games and got four Dec 31 crashes. However, we know by now that this is related to `1.5.0.2` (which this branch is based on) so I wouldn't worry about it too much.

LGTM!

**Comment by ValianBlue** [comment]
# df335c6 Changelog
@VespertinePetrichor @Gaben1025 @ercarp 
> Resolves #1095.

_Completion of the Azshara Overhaul, the elimination of all Ghost Provinces, among other changes to Ingmill Mere Lake & Zul'gurub._

## Azshara
### Province Redrawing
> Remapped the provinces of Azshara to fit its adjusted coastline and heightmap changes.
<details><summary>Before</summary>

image
</details><details>
<summary>After</summary>

image
</details><hr>

## Ingmill Mere Lake
### Province Redrawing
<details><summary>Before</summary>

image
</details><details>
<summary>After</summary>

image
</details><hr>

## Province Alterations
### Provinces Restored
#### Azshara
- 1863 Southridge
- 1864 Bjorrmr
- 1866 Falanoor Isles
- 1875 Arkkoran
- 1876 Eldara
- 1877 Jagged Reef
- 1878 Ravencrest
- 5633 Alalyia
- 5634 Shadris
- 5636 Sarai
- 5637 Kaste
- 5649 Mil'lynn

#### Silithus
- 1626 Xernannoss
- 2301 Qintoku
- 2324 Zuvaru
- 2325 Valad
- 5050 Coprinix
- 5070 Yobir
- 5072 Basrat
<hr>

### Provinces Removed
> Removed c_echo_isle.
- 1114 Red Cloud Lake (Mulgore?)
- 1882 Bilgetrade (Azshara)
- 2028 Lake (Durotar)
- 2029 Lake (Durotar)
<hr>

### Provinces Added
- 6427 Cache of Madness (Zul'gurub)
#### Azshara
> Added c_falanoor_isles.
- 1114 Calomon Isles
- 1882 Manathas
- 2028 Orenlar Isles
- 2029 Eldas

#### Echo Isles
> Added c_echo isles & c_darkspear_isle.
- 6420 Isle of Night
- 6421 Pyre Island
- 6422 Zalazane's Fall
- 6423 Darkspear Training Grounds
- 6424 Zekhan
- 6425 Ten'kin
- 6426 Mojojojo
<hr>

## Adjacencies
 > Added an adjacency between Zul'gurub and Cache of Madness. Added a series of adjacencies to Azshara and the Echo Isles. See the images for details.
<details><summary>Azshara</summary>

image
</details>
<details><summary>Echo Isles</summary>

image
</details>
<details><summary>Zul'gurub</summary>

image
</details><hr>

# Author Notes
_There are still a few outlying errors in error.log. These are history related errors, and will be covered in a future update._

# How to test:
(This section shamelessly copied from ercarp)

Consider the following when giving your feedback:

**Gameplay:** For pertinent bugs, verify if the bugfixes are working as intended.

**Canonicity:** Compare the map changes to ensure accuracy according to the information made available by official canon.

**Familiarity:** Observe whether or not the changes are recognizable and fitting for their respective locations.

**Aesthetics:** Comment on the general look and appeal on the changes. Suggestions should be as specific as possible.

Additionally, ensure that necessary gameplay features like holdings are not obscured by map changes such as trees, water, or steep cliffs.

### -- @ValianBlue

**Review by ercarp — APPROVED** [review]
All looks good to me, I have no complaints. Love the look of the new Azshara. 👌

**Review by ElMariuso — APPROVED** [review]
This seems correct for the most part, there are just a few things left that give errors as you mentioned yourself.
But I think it can be merge for now.

**Pull request merged**
