### PR TITLE
Alex Horns

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added the Aspect of Life horns for Alex.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Check the Horns tab in the Ruler Designer.

### CODE REVIEW

**Review by ercarp — CHANGES_REQUESTED** [review]
The horns look very nice to me, but I should mention that Alexstrasza seems to have two sets of horns. She has smaller horns below her larger horns.

<details><summary>Click to expand</summary>

image
image
image
image

</details>

I'm not personally too fussed about this, but it may be important to others so I think we should add them if possible.

**Comment by zumbak04** [comment]
> The horns look very nice to me, but I should mention that Alexstrasza seems to have two sets of horns. She has smaller horns below her larger horns.

Ooopsie, added in ffc88b71cb0c4d621719dfb779c61b1217780ddb.

**Review by ercarp — APPROVED** [review]
Looks perfect now. LGTM!

**Review by Darknight367 — COMMENTED** [review]
The horn models look fine albeit a bit 'boxy' but it's beautiful nonetheless

**Comment by zumbak04** [comment]
> a bit 'boxy'

I guess it's because it's from WoW.

**Review by Darknight367 — APPROVED** [review]
All's good

**Pull request merged**
