### PR TITLE
Update frostnymph history

### PR DESCRIPTION
**Pull request by Gaben1025**
## Changelog:
- Fixed frostnymph bug

### CODE REVIEW

**Comment by Gaben1025** [comment]
image
I unlocked it for them in history, however, I noticed that we gave them a tech level this is beyond their government type...are we working on this?

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Comment by zumbak04** [comment]
> I unlocked it for them in history, however, I noticed that we gave them a tech level that is beyond their government type...are we working on this?

I see. You may make them tribal level I guess.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
