### PR TITLE
Blending Elves

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added High Elven, Night Elven and Highborne Elven ethnicities.

# How to test:
Check them in-game and tell your opinion.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Some hairstyle are clipping with the ears.
<details>

image
</details>

- These ears are too long for High Elves. They should have shorter ears and they should be angled a bit upwards compared to Night Elves' ears.
<details>

image
</details>

- High Elves eyes need to be a bit brighter in color. It looks a bit too greenish rather than light blue.
<details>

In-game:
image
How their eyes should be:
image

</details>

- High Elves should have thinner eyebrows than Night Elves
<details>

image
</details>

- Maybe add random eye color for Night Elves and Highborne

**Comment by zumbak04** [comment]
> * Maybe add random eye color for Night Elves and Highborne

It's random. Open the Ruler Designer, eyes and randomize it to see.

**Comment by zumbak04** [comment]
Thanks for your review!

> * Some hairstyle are clipping with the ears.

Fixed in 738a1c5ee6c9146d72160f3c29d58a2a17537a70.

> * These ears are too long for High Elves. They should have shorter ears and they should be angled a bit upwards compared to Night Elves' ears.

Added in dd246af9cd9b91976c3291b355fd1bb9df57871a and 054067caad41b7be8fe466687c54b0a6c27dde6f.

> * High Elves eyes need to be a bit brighter in color. It looks a bit too greenish rather than light blue.

Changed in 2441871467242e6fb61d234f7bdce00d6dc03841.

> * High Elves should have thinner eyebrows than Night Elves

Added in 13b412f0076465b47e463829737800393b07ac48 and 6aeef467deb81513e35c167d4142e726a8df131f.

**Review by TheGroxEmpire — COMMENTED** [review]
Excellent job! I didn't check the ruler designer, thanks for telling me.

The eyes are indeed brighter and better now, but the blue eyes color is still a bit too green imho.
<details>

What random generation mostly getting:
image

My suggested eye color:
image

</details>

I like the new ears and eyebrows. But I feel that the female High Elves ears are way too short even at max ear length.
<details>

Wowhead models:
image

In-game:
image
</details>

Clipping hairs are mostly fixed, except for some of the hairstyles here that I got from using randomizer in Ruler Designer (Warning, long spoiler):
<details>

image
image
image
image
image
image
image
image
image

</details>

**Comment by zumbak04** [comment]
> I like the new ears and eyebrows. But I feel that the female High Elves ears are way too short even at max ear length.

Because of perspective. Comparing two models in Blender. This is the longest female ears.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by TheGroxEmpire** [comment]
> Because of perspective. Comparing two models in Blender. This is the longest female ears.

I think it is shorter than the one on wowhead modelviewer:
<details>

image
</details>

Maybe the slope also play a bit of factor here.

**Comment by zumbak04** [comment]
> I think it is shorter than the one on wowhead modelviewer:

Comparing models with hair.
The first is with perspective.
The second is without.
<details>
<summary>Click to expand</summary>

image
image

</details>

**Comment by TheGroxEmpire** [comment]
> Comparing models with hair.
> The first is with perspective.
> The second is without.

Hmm, yeah I guess you are right. The one on Wowhead is also a bit angled upward so it looks taller.

**Comment by zumbak04** [comment]
> The eyes are indeed brighter and better now, but the blue eyes color is still a bit too green imho.

Changed in a6e1961545087c9ba186a04a6b1241c78a7ff633.

> Clipping hairs are mostly fixed, except for some of the hairstyles here that I got from using randomizer in Ruler Designer (Warning, long spoiler):

Should be fixed in b2a3a8a7cb1a2ae8dab8d4d1ce86d9f936b66634, c61a97a8410260dcb32d40a1f69cea46af295bf5, a884d8faa1c6c5ccc55edc8ad4f1fa2f0dd1845d.

**Review by TheGroxEmpire — COMMENTED** [review]
The new eyes color is perfect.
Major clipping issues are all fixed, just some minor clipping and excess polygon left:
<details>

image
image
image
</details>

**Comment by zumbak04** [comment]
> Major clipping issues are all fixed, just some minor clipping and excess polygon left:

Should be fixed.

**Review by TheGroxEmpire — APPROVED** [review]
Excellent, they all look dandy now.

**Review by ulricee — COMMENTED** [review]
Theirs still some clipping issue with facial hair on fat and obese character.

**Comment by zumbak04** [comment]
> Theirs still some clipping issue with facial hair on fat and obese character.

Take screenshots. If they are not related to elven ears, report them straight to Paradox, they have a clipping thread.

**Review by ulricee — COMMENTED** [review]
The beard problem was also on vanilia CK3 and was reported to paradox. However I found that extremelly wide top head would clip with prick styled ears. 


Megamind type of character are quite rare but it's still technically clipping.

**Comment by zumbak04** [comment]
> The beard problem was also on vanilia CK3 and was reported to paradox. However I found that extremelly wide top head would clip with prick styled ears.

Fixed.

**Review by Deuce20201 — APPROVED** [review]

**Review by ulricee — APPROVED** [review]
I have found no clipping from the head itself to the ears after the fix

**Pull request merged**
