### PR TITLE
More History

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added a ton of new baronies.
- Added a lot of new counties.
- Added new duchies, to make sure every duchy has 5-3 counties. Not more.
- Added new kingdoms, to make sure every kingdom has 5-3 duchies. Not more.
- Made sure characters have 4-1 holdings, not over the limit.
- Added fords (over major rivers) and straits (over seas).

# How to test:
Check the history of all the dates. If you notice something weird or you want to change something, tell me.

# Notes:
- Don't force governments in the history files. It's bad! It makes you not able to use your own holdings. If you really want to change the government, change the holdings they own instead.
<details>
<summary>Click to expand</summary>

image

</details>

- Don't force laws in the history files. They were ported from CK2 where title laws played a bigger role. Now religions play this role thus we don't need them.
<details>
<summary>Click to expand</summary>

image

</details>

- I made the [Character Generator](https://github.com/Warcraft-GoA-Development-Team/CK3-Character-Generator/releases/tag/1.0.0), feel free to use it for generating more characters. Pay attention there are 2 tabs: **Characters** and **Titles**. **Characters** shows generated characters. **Titles** shows an inheritance line for their titles.

# Tasks
<details>
<summary>Click to expand</summary>

- [x] Clean forcing governments in history files. Read **Notes**.
- [x] Clean forcing laws in history files. Read **Notes**.
- [x] Rework the Barrens history. It needs a closer look. It's very different from what we had in CK2.
- [x] Write history for Un'goro
- [x] We should fix `landedtitlemanager.cpp:618`: county doesn't have a holder in history.
- [x] Lots of new history needed. Any province/dutchy marked with `#NEEDS NEW` requires new history. Some/many of them require new characters/holders as well.
  - [x] Eastern Kingdoms
  - [x] Northrend
  - [x] South Seas
  - [x] Kalimdor
  - [x] Pandaria
- [x] Since there are new dutchies/kingdoms, the liege will need to be updated in many places.
- [x] c_krasarang needs to be renamed
- [x] Counties that changes government type need to change holdings instead
- [x] Remove Drysnout duchy title
- [x] Restore the Defias Brotherhood
- [x] Restore the Dragonmaw
- [x] Generate Scourge rulers (a bit bunch of lands are controlled by Ner'zhul in 603).
- [x] Fix `landedtitlemanager.cpp:637`
- [x] `titlehistory.cpp:266`: Title holder dead
- [x] Keep some nerubs in Northrend
- [x] Make taurens independent from the Horde in 605
- [x] Populate Plunder Isle with pirates

</details>

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Empire of Shek'mag (Mantid) should have more empress: https://wowpedia.fandom.com/wiki/Mantid
- High Kingdom of Zandalari missing quite a few leaders: https://wowpedia.fandom.com/wiki/Zandalari_Empire#Former_rulers
- Arathor Empire missing its history: https://wowpedia.fandom.com/wiki/Arathor
- Quel'Thalas missing quite a few leaders: https://wowpedia.fandom.com/wiki/Quel%27Thalas_(kingdom)
- Gurubashi is missing the last chief mentioned: https://wowpedia.fandom.com/wiki/Var%27gazul
- Add Deathwing to Black Dragonflight history,

**Comment by zumbak04** [comment]
> * Arathor Empire missing its history: https://wowpedia.fandom.com/wiki/Arathor

It was destroyed long before our first year.

> * Quel'Thalas missing quite a few leaders: https://wowpedia.fandom.com/wiki/Quel%27Thalas_(kingdom)

Anasterian ruled Quel'thalas for 3000 years. There's no other king in our historical period.

> * Gurubashi is missing the last chief mentioned: https://wowpedia.fandom.com/wiki/Var%27gazul

It was destroyed long before our first year.

> * Add Deathwing to Black Dragonflight history,

If we add him, he's supposed to be very OP so I wouldn't do it for now.

**Comment by zumbak04** [comment]
> * Empire of Shek'mag (Mantid) should have more empress: https://wowpedia.fandom.com/wiki/Mantid

Added in 3e527bd04a456b171bee754d7ce30ee730c424c4.

> * High Kingdom of Zandalari missing quite a few leaders: https://wowpedia.fandom.com/wiki/Zandalari_Empire#Former_rulers

Added in f8b42e0d308c8ef2415ffd63a544619683e9bbc2.

**Review by TheGroxEmpire — APPROVED** [review]
My suggestion was considered and some was added appropriately in the game. The rest looks fine to me!

**Comment by ElMariuso** [comment]
These counties needs to be tortollan:
- c_darkwood https://wowpedia.fandom.com/wiki/Tortaka_Refuge
- c_torga https://wowpedia.fandom.com/wiki/Torga
- c_atalgral (Probably not just Loristically but there is a small village of Tortollan in the area so I think this county could be.)

**Comment by zumbak04** [comment]
> These counties needs to be tortollan:
> 
> * c_darkwood https://wowpedia.fandom.com/wiki/Tortaka_Refuge
> * c_torga https://wowpedia.fandom.com/wiki/Torga
> * c_atalgral (Probably not just Loristically but there is a small village of Tortollan in the area so I think this county could be.)

You should make it a suggestion, because the tortollan race trait doesn't exist on this branch.

**Review by ElMariuso — COMMENTED** [review]
> The wyrm lived with his brood of blue dragons near the entrance to Azjol-Nerub in the mountains of Northrend, where he guarded a hoard of powerful artifacts he had collected over the centuries

https://wowpedia.fandom.com/wiki/Sapphiron

I think Sapphiron need to be vassal of Blue Dragonflight and have a territory. I propose here.

<details>
<summary>Click to expand</summary>

image

</details>

> Right after the opening of the Dark Portal, scouts from the Black Tooth Grin and Bleeding Hollow clans were sent by Blackhand to survey the Black Morass on the other side of the portal.

https://wowpedia.fandom.com/wiki/Black_Tooth_Grin_clan

It is not specified exactly that they are participating in the war or that they have a territory during the first war, but it is well specified that they are present.
In the Warcraft 2 manual on the other hand, it is said that their territory is in the Black Morass. So i propose to put a new clan leaded by Dal'rend and with Maim as vassal here.

<details>
<summary>Click to expand</summary

image

</details>

I think all major centaurs clans should have kingdom title like Kolkar clan.

<details>
<summary>Click to expand</summary>

image
image
image
image
image

</details>

**Comment by zumbak04** [comment]
> I think Sapphiron need to be vassal of Blue Dragonflight and have a territory. I propose here.

Sounds legit.

> It is not specified exactly that they are participating in the war or that they have a territory during the first war, but it is well specified that they are present.
> In the Warcraft 2 manual on the other hand, it is said that their territory is in the Black Morass. So i propose to put a new clan leaded by Dal'rend and with Maim as vassal here.

It's said that Blackhand led them. So if it's added, it should be another title of Blackhand.

> The Black Tooth Grin clan was founded by Blackhand shortly after he was named Warchief of the Horde, 5 years before the First War, and consisted of soldiers handpicked by the warchief himself.

> I think all major centaurs clans should have kingdom title like Kolkar clan.

Sounds legit.

**Comment by ElMariuso** [comment]
> 
> It's said that Blackhand led them. So if it's added, it should be another title of Blackhand.
> 

It is said here that it was Rend and Maim the chiefs.

<details>
<summary>Click to expand</summary>

image

</details>

And if they're Blackhand's vassals, they're still ruled by him in the end.

**Comment by zumbak04** [comment]
> It is said here that it was Rend and Maim the chiefs.
 
 Forgot to update the info, their description said Blackhand was the first leader and refers to the Chronicles.

**Review by DatFrenchBanana — APPROVED** [review]
Haven't found any visual bug nor event bug in the 30 minutes of test I did

**Review by Fuelgon — APPROVED** [review]
For me the map and the actual history are truth. 

But we must keep in mind  that we can't  never complete it at 100 % because lack of detailled sources ( exemple the distribution of territory) 

Approved

**Review by ElMariuso — APPROVED** [review]
I put my changes so i approved too

**Pull request merged**
