### PR TITLE
Suramar Flavor Pack + Impressions Diplomacy

### LINKED ISSUE #1535: Add content for Suramar be in arcane bubble
make it unable to delcare war or change its lands or something until the ruler decide not to

### LINKED ISSUE #1605: (Isolation) Unions are available to join when in Isolation
**Issue Description:**
For the Isolation mechanic, I am testing on the #1589 Suramar Flavor branch. I noticed that, while isolated, I managed to get 40+ opinion with the leader of the Alliance, Terenas. This unlocks the decision to join the Alliance union.

Both player and AI should be excluded from joining unions while the Isolation mechanic is in play for their nation.

**How To Reproduce:**
Play as a nation in Isolation (Suramar for example in Suramar Flavor branch, or once merged)
Gain 40+ opinion of a faction leader in range.
Decision to join leader's union is available.
Join the leader's union while in isolation.

**Screenshots:**
image

**Game Files:**

### PR DESCRIPTION
**Pull request by helloruhe**
### General Suramar Flavor
- Shal'danalism (Nightborne faith) now allows concubines
- Added Elisande's clothing
- Gave Elisande Unique DNA
- Change Elisande's traits
- Adds Suramar to the isolation mechanic
   - If the Queen/King of Suramar is ruled by AI, they will automatically open the barrier in 615, as in lore, this is when Gul'dan contacted Suramar (no events for this yet though)
- Expanded the Isolation mechanic to include traveling for activities
- Expanded the Isolation mechanic to include wars
   - But if you have any existing wars, they should be able to be ended normally now
- Added **15+** unique events for the Ruler of Suramar and it's vassals
- Added a new decision for the ruler of Suramar: Remove the Arcane Barrier
   - To get access to this decision, the ruler of Suramar must learn of the outside world via the unique events
   - Once AI learns the decision, they _usually_ won't take it until after 615
- Add a Suramar character view
- Add several Suramar event backgrounds
- Adapted Court Brewmaster and allow anyone with Shal'danalism (Nightborne faith) to have breweries
- Added a new trait: Wretched
   - If you Banish characters as a ruler in Suramar, via the events, or imprisonment, they have a chance to become Wretched (if the arcandor tree is not restored)
   - If a nightborne travels outside of suramar they have the chance to become wretched as well
   - If the arcandor tree is not restored, random nightborne outside of suramar will have the chance to become wretched
   - This is to represent the nightfallen, and in the future, represent elves who are magic-starved (like the High Elves at some point)
- Added a new artifact: Seed of Arcandor
   - Get it from various events
   - Will get a boon from restoring the tree if you have it
- Add a decision: Restore the Arcandor Tree
   - Added special Arcandor Tree building

### New Mechanic: First Contact
- Expand the diplomatic range
  - EG: If you're in quel'thalas, you should be able to interact with most of Northrend and some of Pandaria
- Inspired by Stellaris' 'First Contact' event, certain people will be able to do 'first contact' diplomacy with certain rulers
- Some situations where First Contact is available and who can interact, right now, only in Suramar, but will extend to other situations and events
   - **De-Isolation of Suramar:** Any broken isles ruler (besides Suramar), (Duke or above, or player ruler) who is of elven culture or has an elven trait, in diplomatic range of suramar will be able to have contact with the ruler of Suramar upon it's de-isolation
- You can be friendly, hostile, or 'neutral' towards them on first contact
- You can contact them via letter event

# How to test:
- Test all of the new decisions and associated event chains.
- Test the First Contact Mechanic as the ruler + one who might receive the message, for all scenarios if possible
- The following standalone events will need testing. You can test them if you meet the requirements stated, by going into the console and using `event eventid` The Event ID is listed below
- `wc_suramar_events.0001` - Opening event - Requirement: Queen/King of Suramar
- `wc_suramar_events.0002` - Event to learn about the outside world - Requirement: Ruler in Suramar (Test as vassal AND queen/king)
- `wc_suramar_events.0003` - Event to learn about the nightfallen - Requirement: Ruler in Suramar (Test as vassal AND queen/king)
- `wc_suramar_events.0004` - Event where you become wretched (sometimes will happen if you travel outside of suramar) - Requirement: Ruler in Suramar (Test as vassal AND queen/king)
- `wc_suramar_events.0010` - Aqueduct/Vaults/Arcway event chain - Requirement: Ruler in Suramar (Test as vassal AND queen/king), several outcomes to test
- `wc_suramar_events.0020` - Thinking about Aszhara - Requirement: Ruler in Suramar (Test as vassal AND queen/king)
- `wc_suramar_events.0030` - Visited by an Elune Priestess - Requirement: Ruler in Suramar (Test as vassal AND queen/king), Could also test as kaldorei religion & Non-kaldorei religion for diff options
- `wc_suramar_events.0040` - Fal'dorei Event chain start Requirement: Ruler in Suramar (Test as vassal AND queen/king), not the holder of Meredil, Bonus: test with the callous trait
- `wc_suramar_events.0050` - *Rare Event* Vision of Sargeras - Requirement: Ruler in Suramar (Test as vassal AND queen/king), Could also test as sargerite & Non-sargerite for diff options
- `wc_suramar_events.0060` - Arcwine - Requirement: Ruler in Suramar (Test as vassal AND queen/king) - Test as a ruler who's already hosted a feast, and also test as a paranoid character
- `wc_suramar_events.0070` - Murloc event chain - Requirement: Ruler in Suramar, must not have arcane barrier desc unlocked yet, must not be a murloc, in a coastal county near a murloc coastal county
- `wc_suramar_events.0080` - A nightfallen seeks asylum in your court/camp - Requirement: Physically in Suramar (including landless adventurers)
- `wc_suramar_events.0100` - *Rare Event* Someone brings you a seed of arcandor - Requirement: Ruler in Suramar, must not have the seed of arcandor
- `wc_suramar_events.0110` - *Letter Event* A faldorei asks you to restore the tree - Requirement: King/Queen of Suramar, the barrier must be down and have neighboring faldorei, OR have a faldorei vassal
- `wc_suramar_events.0120` - You see a naga  - Requirement: Ruler in Suramar, must not be a naga, in a county near a naga county
- `wc_suramar_events.0130` - An adventurer in your realm - Requirement: Ruler in Suramar, there is a laamp encampment in your realm (non-nightborne leader)

### CODE REVIEW

**Comment by FelModder** [comment]
Initial Testing Done, what each mark means=>
✅: Working as intended, as described in the PR.
🟡: Working but few bugs/issues halting the progress of the event.
❌: Not working at all.

### General Suramar Flavor ✅
Shal'danalism (Nightborne faith) now allows concubines ✅
Added Elisande's clothing ✅
Gave Elisande Unique DNA ✅
Change Elisande's traits ✅ (Only _Otherworldly_ got added)
Adds Suramar to the isolation mechanic ✅
Expanded the Isolation mechanic to include traveling for activities 🟡 (Works, but even if your destination is limited to the Suramar Realm, the player can still choose baronies outside of the barrier before reaching the destination)
Expanded the Isolation mechanic to include wars 🟡 (This has caused Peasent Revolts to not be able to end since the rebel leader counts as a person outside of the barrier. This is, by far, the only huge gameplay issue.) (Pictures of the Issue: 
Peasent Revolt but cannot Enforce Demands
Can't execute the peasent who revolted
)
Added a new decision for the ruler of Suramar: Remove the Arcane Barrier ✅
- To get access to this decision, the ruler of Suramar must learn of the outside world via the unique events ✅
- Once AI learns the decision, they usually won't take it until after 615 🟡 (Tested this only once and the barrier only opened on 1st January 615, i will test this more times and notify as such) 

Add a Suramar character view ✅
Add several Suramar event backgrounds ✅
Adapted Court Brewmaster and allow anyone with Shal'danalism (Nightborne faith) to have breweries ✅

Added a new trait: Wretched ✅
- If you Banish characters as a ruler in Suramar, via the events, or imprisonment, they have a chance to become Wretched (if the arcandor tree is not restored) ✅
- If a nightborne travels outside of suramar they have the chance to become wretched as well ✅
- If the arcandor tree is not restored, random nightborne outside of suramar will have the chance to become wretched ✅

Added a new artifact: Seed of Arcandor ✅
- Get it from various events ✅
- Will get a boon from restoring the tree if you have it ✅

Add a decision: Restore the Arcandor Tree ✅
- Added special Arcandor Tree building ✅

### New Mechanic: First Contact

Double the diplomatic range ✅
De-Isolation of Suramar: Any broken isles ruler (besides Suramar), (Duke or above, or player ruler) who is of elven culture or has an elven trait, in diplomatic range of suramar will be able to have contact with the ruler of Suramar upon it's de-isolation ✅
You can be friendly, hostile, or 'neutral' towards them on first contact 🟡 (Works but what guarantees neutrality/friendliness/enemity? I didn't see any modifier nor any opinion boost towards the Suramar)
You can contact them via letter event ✅

### EVENT CHAINS:

**Opening event** - Requirement: Queen/King of Suramar ✅

**Event to learn about the outside world** - Requirement: Ruler in Suramar (Test as vassal AND queen/king) ✅

**Event to learn about the nightfallen** - Requirement: Ruler in Suramar (Test as vassal AND queen/king) ✅

**Event where you become wretched** (sometimes will happen if you travel outside of suramar) - Requirement: Ruler in Suramar (Test as vassal AND queen/king) ✅

**Aqueduct/Vaults/Arcway** event chain - Requirement: Ruler in Suramar (Test as vassal AND queen/king), several outcomes to test ✅ (got the different outcomes, they work)

**Thinking about Aszhara** - Requirement: Ruler in Suramar (Test as vassal AND queen/king) ✅

**Visited by an Elune Priestess** - Requirement: Ruler in Suramar (Test as vassal AND queen/king), Could also test as kaldorei religion & Non-kaldorei religion for diff options ✅ (tested it with kaldorei & non-kaldorei religions, they work)

**Fal'dorei Event** chain start Requirement: Ruler in Suramar (Test as vassal AND queen/king), not the holder of Meredil, Bonus: test with the callous trait 🟡 (works, but if the vassal who is the holder of county of Meredil this event basically does not work for them as they need to Travel to Meredil to Meredil (_which that vassal already owns_) and end up traveling in one day which does not trigger the events for other days. Long story short, this even does not work for the Vassal Ruler of Meredil)

Rare Event **Vision of Sargeras** - Requirement: Ruler in Suramar (Test as vassal AND queen/king), Could also test as sargerite & Non-sargerite for diff options ✅ (tested it with sargerite and non-sargerite religions too)

**Arcwine** - Requirement: Ruler in Suramar (Test as vassal AND queen/king) - Test as a ruler who's already hosted a feast, and also test as a paranoid character ✅ (tested it with a ruler who already hosted a feast and with a paranoid character)

**Murloc event** chain - Requirement: Ruler in Suramar, must not have arcane barrier desc unlocked yet, must not be a murloc, in a coastal county near a murloc coastal county ✅

**A nightfallen seeks asylum in your court/camp** - Requirement: Physically in Suramar (including landless adventurers) ✅ (also works for landless adventurers)

Rare Event **Someone brings you a seed of arcandor** - Requirement: Ruler in Suramar, must not have the seed of arcandor ✅

Letter Event **A faldorei asks you to restore the tree** - Requirement: King/Queen of Suramar, the barrier must be down and have neighboring faldorei, OR have a faldorei vassal ✅

**You see a naga** - Requirement: Ruler in Suramar, must not be a naga, in a county near a naga county ✅

**An adventurer in your realm** - Requirement: Ruler in Suramar, there is a laamp encampment in your realm ❌ (Not working at all. Images below:
Adventurer Event
Adventurer Event 2

)

**Comment by FelModder** [comment]
**An adventurer in your realm** - Requirement: Ruler in Suramar, there is a laamp encampment in your realm _(non-nightborne leader)_ ✅ (Working as intended:
Adventurer Event working
)

**Comment by Rimaka94** [comment]
Some observations from my testing on 12/10/2024:

- :x: wc_suramar_events.1002.desc needs a few adjustments on apostrophes:
  - `It's roots are deep` to `Its roots are deep`
  - `it's mana flows through` to `its mana flows through`
- :x: wc_suramar_events.0044.desc_outro needs apostrophe removal:
  - `about the Arcan'dor tree, it's corruption, and` to `about the Arcan'dor tree, its corruption, and`
- :x: wc_suramar_events.0044.desc_seed has an unnecessary space:
  - `pull out the glowing rock.  "The seed of the Arcan'dor!`
- :x: wc_suramar_events.0120.desc needs an adjustment:
  - `but the most intrigue theory` should be `but the most intriguing theory`
- :x: wc_suramar_events.0012.monster_2 needs slight adjustment:
  - `Bring this beasts' corpse back` to `Bring this beast's corpse back`
- :x: wc_suramar_events.0060 issues:
  - :x: If you have no valid city locations for a Brewing House, either because you have no cities or already have a Brewing House in all valid cities, the option to gain a new Brewing House is still shown and looks bad:
    - `Holding of  gains the Brewing House Building`
  - :x: The option to gain a Brewing House also states the target character will be recruited to join the travel Entourage, despite this event having the requirement to not be traveling.
- :x: wc_suramar_events.0012 event, in which you encounter a wretched elf, had no target for me. This led to issues in both event description and the first option.
  - If needed, the game I encountered this in I converted to Nzothi as soon as possible and immediately brought down the barrier. I was also in the middle of a war. The Arcan'dor Tree was not yet restored.

<details>
<summary>[Screenshot] wc_suramar_events.0012</summary>

image
</details>

**Comment by Rimaka94** [comment]
One last thing to add to the above list -

Nightfallen-Wretched trait needs to have uppercase "Arcan'dor" in description: `Only with restoration of their magic via the arcan'dor tree,`

**Comment by FelModder** [comment]
Expanded the Isolation mechanic to include wars ✅.
(Peasent War Bug has been fixed and can now enforce demands when the faction is beated.)
Peasent War Fixed

I completely forgot to mention this fact in my initial test:
Other factions can still raid you despite you being Isolated (pretty immersion breaking)
Isolated but Raided

**Review by Rimaka94 — DISMISSED** [review]
All previous feedback has been addressed so I'm leaving my approval from in-game testing perspective. No new issues to bring up after doing a quick check through each of the individual issues to confirm fixes.

**Pull request merged**
