### PR TITLE
Shenism holy sites

### PR DESCRIPTION
**Pull request by Loralius**
## Changelog:
- Add Mogu'Shan Palace and Lei Gong (Throne of Thunder) as Shenic Holy Sites. 
- Removed Uldaman and Dun Niffleheim 
- Changed tenet 'Progressivim' to 'Cult of Strength'

## Developer changelog:
Holy Site modifiers:
- mogushan:
  - domain tax mult
  - same faith opinion
- lei_gong
  - dread per tyranny gain
  - scheme resistance

- Included localisation.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
- Religion gui for holy sites
- Correct county locations for holy sites
- Give feedback on type, balance of modifiers + locations of holy sites (refer to #793)

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Ulduar still appeared in the game:
<details>

image
</details>

**Comment by Loralius** [comment]
Oops, this is my bad. I decided to replace Uldaman instead of Ulduar after posting the PR but forgot to update the origibal post.

**Review by TheGroxEmpire — APPROVED** [review]
Yup, everything else looks good to me.

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Pull request merged**
