### PR TITLE
3rd Static Models

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Exported these models from WoW:
  - Qiraji Prophet for qiraji males
  - Battleguard for qiraji females
  - Twin Emperor for qiraji twin emperors
  - Crypt Lord for nerubians
  - Faceless for n'raqi
  - 2 C'Thrax models for C'Thraxxi
- Used neural networks to improve furbolg textures.
- Quilboar and murloc models change when they become undead.
- Updated the character view mask. On the character screen, the bottom corners are no longer cut.

# Tasks:
- [x] Use undead murloc, quilboar models

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Search by race to find characters in the Ruler Designer.

`add_trait being_undead` to make character undead.

### CODE REVIEW

**Review by ercarp — APPROVED** [review]
>* Qiraji Prophet for qiraji males
>* Battleguard for qiraji females
>* Twin Emperor for qiraji twin emperors
>* Crypt Lord for nerubians
>* Faceless for n'raqi
>* 2 C'Thrax models for C'Thraxxi

All of these look very good to me. The C'Thraxxi and N'raqi look especially nice as they're a bit higher quality than some of the older models (not a complaint, just an observation). Great job! It's nice to have more static models added, it makes the world feel more alive when they're not just using human placeholder models anymore. 👍 

>* Used neural networks to improve furbolg textures.

This was a good idea, the difference is very noticeable to me personally.

>* Quilboar and murloc models change when they become undead.

Works. I don't think the difference is as noticeable as it is with the CK3 characters since they get glowy eyes, but it is much better than having nothing at all.

>* Updated the character view mask. It no longer cuts bottom corners.

I don't know what this means so I can't test it, but I didn't notice any visual errors.

**Review by CantTouchThisJinTao — APPROVED** [review]
Checked exported models, all looking good.
Furbolgs definitely look better than before.
Murloc + Quilboar definitely a noticeable difference but as ercarp said it's not as noticeable as ck3 characters (i definitely like the Quilboar undead more than the murlocs though, the skin change definitely is appealing).

Overall everythings decent (as with ercarp i'm not too sure what the character view mask is), didn't notice any issues with anything though.

Pretty much agree with everything ercarp said.

**Review by Remerod — APPROVED** [review]
Murloc & Quilbor with their Undead traits look ok to me. 

I also like the N'raqi & C'Thraxxi.

I really like the Crypt Lord for nerubians, I hope more are added. Like Nerubian vizier, Living normal Nerubians and Crypt fiends. it's to bad there are not many female nerurbians in lore with special models, but here are 2 females in lore + some wc3 pics of nerubians if we would want to add this.
<details>
<summary>Click to expand</summary>

**Nezar'Azret** 
image
https://wowpedia.fandom.com/wiki/Nezar%27Azret

**Underqueen Zarzhet**
image
https://hearthstone.fandom.com/wiki/Underqueen_Zarzhet

**Nerubian Warrior**
image

**Nerubian Queen** 
image

</details>

I also really think the qiraji models are nice to have, I do however want to ask if we can add the qiraji gladiator to it's roaster, since they should be more common then the qiraji prophets. I like to keep the prophets to but if i have to choice i'd would like to have the gladiators, even if the prophets probably have more court jobs, i think it's more representative as a race to have the qiraji gladiator added.
 >Qiraji gladiators are walking, male qiraji warriors with pincer-like claws led by General Rajaxx. They have human-like feet, and some of their carapace seems to be armor. They are the most common type of qiraji. **They are apparently the male counterpart to the qiraji battleguards**, but how qiraji actually reproduce is unknown.  

So apart for the things i suggested, the things that was added, looked all good to me, So I'll approve of this!

**Review by Darknight367 — APPROVED** [review]
All the Qiraji models are looking fine. 
The Nerubians, N'raqi and C'thraxx models are very beautiful, really fits the vanilla CK3 aesthetics.
Can't really comment much on the Furbolgs but they're beautiful still.

The undead models of the Quilboars and Murlocs are really noticeable though I would say that their eyes are a bit dead..... (hehe)

Overall very beautiful!

**Comment by zumbak04** [comment]
> I really like the Crypt Lord for nerubians, I hope more are added. Like Nerubian vizier, Living normal Nerubians and Crypt fiends.

> I also really think the qiraji models are nice to have, I do however want to ask if we can add the qiraji gladiator to it's roaster, since they should be more common then the qiraji prophets.

Before adding their models, we have to add their casts. I opened this task here:
https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/666

**Pull request merged**
