### PR TITLE
DNA for Greymane, Fordring, VanCleef, Wrynn + Others

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Made very small fixes to **Anasterian**, **Lor'themar**, and **Alleria**. _(These are barely noticeable so they are not included in the list.)_
- Added **15** new character portraits:

_[Link to DNA spreadsheet](https://docs.google.com/spreadsheets/d/1Cf0FGh_iNoyDsIwceDkL_Fr4B7_rOZKaa0QbzLNqmYQ/edit#gid=652876950) for additional information, such as what was used as reference for the portraits._

### Gnomes

 **Mekkatorque**
- Gelbin Mekkatorque (by @ercarp)

<details><summary>Screenshot</summary>

image

</details>

### Humans

**Greymane**
- Tess Greymane (by @ercarp)
- Liam Greymane (by @ercarp)
- Mia Greymane (by @ercarp)
- Archibald Greymane (by @ercarp)

<details><summary>Screenshots</summary>

image
image
image
image

</details>

**Fordring**
- _**Reworked**_ Tirion Fordring (by @ercarp)
- Taelan Fordring (by @ercarp)
- Karandra Fordring (by @ercarp)

<details><summary>Screenshots</summary>

**New Tirion DNA**
image

**Old Tirion DNA**
_He looked like he was angry all the time so I adjusted his brows a bit._
image

image
image

</details>

**Menethil**
- _**Reworked**_ Arthas Menethil (by @ercarp)

<details><summary>Screenshot</summary>

**New DNA**
image

**Old DNA**
image

</details>

**VanCleef**
- Edwin VanCleef (by @ercarp)
- Vanessa VanCleef (by @ercarp)

<details><summary>Screenshots</summary>

image
image

</details>

**Wrynn**
- Landan Wrynn (by @ercarp)
- Barathen Wrynn (by @ercarp)
- Varia Wrynn (by @ercarp)
- Taria Wrynn (by @ercarp)

<details><summary>Screenshots</summary>

image
image
image
image

</details>

# Tasks:
- [x] `is_taelan_trigger` used in `is_any_historical_character_trigger`

# How to test:
Consider the following when giving your feedback:
- **Canonicity**: Observe if the character's appearance matches the information provided by canon in terms of hair, eye, and skin color; hairstyle, facial hair; body shape, etc.
- **Familiality**: Observe whether or not characters look sufficiently related to each other if they have family members with custom DNA.
- **General Feedback**: Give general feedback on how you feel about each addition. In simple terms: does the portrait look good to you personally?

**How to view the portraits**:

- You can either **A)** rely on the screenshots provided above (although most portraits look much better once you see them in motion) or **B)** have a look at the portraits in-game.
  - Enable [Debug Mode](https://ck3.paradoxwikis.com/Console_commands#Enabling_debug_mode) and use the `age [amount] [character id]` console command to change a character's age if they are too young or old in the current bookmark.

### CODE REVIEW

**Review by ValianBlue — APPROVED** [review]
_After looking at each of them as closely as I could, I think they all look great. The families look related to each other, and for the characters that do have art or in-game sources they resemble them pretty closely. Obviously not all of the hairstyles are accurate, but this is out of your hands._

_Varia and Taria do look very similar, and I don't believe they're related. I de-aged Varia to 40 to compare. It is plausible that they have some similarities (perhaps the Wrynn men have similar tastes, heh), but I wanted to make a note on this._

_Personally, I'd love to see the VanCleefs one day with their red masks, but I'm getting ahead of myself here._

**Comment by ercarp** [comment]
> _Varia and Taria do look very similar, and I don't believe they're related. I de-aged Varia to 40 to compare. It is plausible that they have some similarities (perhaps the Wrynn men have similar tastes, heh), but I wanted to make a note on this._

Hmm, I don't think they look _that_ similar, although if they do, I know why. I used Varian's DNA to make Taria and Llane's DNA to make Varia. Llane was originally made by modifying Varian's DNA, so it makes sense that they would have some similarities. Their lips do look very similar.

<details><summary>Click to expand</summary>

image
image

</details>

> _Personally, I'd love to see the VanCleefs one day with their red masks, but I'm getting ahead of myself here._

I opened an issue for this yesterday (https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/issues/606). I hope our 3D wizards can make it a reality someday.

**Comment by ValianBlue** [comment]
> 
> 
> > _Varia and Taria do look very similar, and I don't believe they're related. I de-aged Varia to 40 to compare. It is plausible that they have some similarities (perhaps the Wrynn men have similar tastes, heh), but I wanted to make a note on this._
> 
> Hmm, I don't think they look _that_ similar, although if they do, I know why. I used Varian's DNA to make Taria and Llane's DNA to make Varia. Llane was originally made by modifying Varian's DNA, so it makes sense that they would have some similarities. Their lips do look very similar.
> Click to expand
> 
> image
> image
> 
> > _Personally, I'd love to see the VanCleefs one day with their red masks, but I'm getting ahead of myself here._
> 
> I opened an issue for this yesterday (#606). I hope our 3D wizards can make it a reality someday.

Seeing them from the side clears it up more. I looked mostly at the screenshots you had attached in the original post and thought their noses, mouths, and chins looked alike, but there's more to it than what I had seen at first glance.

**Review by Remerod — COMMENTED** [review]
I generally really like the **Mekkatorque, Fordring, Fordring, VanCleef & Wrynn** portraits.
I am not as convinced though on the Greymanes

<details>
<summary>Click to expand</summary>

So i think **Liam** is good. But i don't get that attitude from **Tess** that i would get from her in wow or other media.
ck3 version
image
Art & Media
image
image

I also think that **Mia Greymane** looks different, I get the well maid point of her being more ginger, for it make sense because of **Liam**. But i don't really see the madam/loving wife of her old self in her younger one. I guess i see Mia more as a confident madam, lady & queen Elizabeth kind of character while this ... well young? so i don't really have a critic of how to make it better.
image
image
image

So i guess  my suggestion would be to make Tess more.. adventurous looking like her hearthstone art? I mean they all work and look good. the Gilneas are just a bit harder since they fall more into a Victorian themed look witch ck3 base game does not represent well. I just think the other looked better then the Greymane's but i can't really say that this or that would be better. So i may just be wasting time here, but i wanted to leave a comment on me "feels" for you to nod to or totally disregard. but perhaps it would inspire to something new? Anyway if you think it's unnecessary to change anything i think it work's well as it if for now.

Good job with the portraits. 

</details>

**Comment by ercarp** [comment]
> So i think **Liam** is good. But i don't get that attitude from **Tess** that i would get from her in wow or other media.

The artwork of Tess that you linked is one I actually used as reference when making her portrait, but it's worth keeping in mind that she's scowling in that picture whereas in CK3 she is not. I try to avoid making characters' resting faces look like scowls because it makes their other emotions, especially idle ones, look strange.

If you give Tess a hood and pose her the right way, you should still be able to capture the kind of adventurousness her artwork has:

<details><summary>Click to expand</summary>

image
image
image
image

</details>

> I also think that **Mia Greymane** looks different, I get the well maid point of her being more ginger, for it make sense because of **Liam**. But i don't really see the madam/loving wife of her old self in her younger one. I guess i see Mia more as a confident madam, lady & queen Elizabeth kind of character while this ... well young? so i don't really have a critic of how to make it better.

Mia's portrait was based on the DNA used by Liam and Tess to make sure she looks like their mother, which I believe is important. Once again, if you age her up (she is younger in this bookmark) and give her the right pose, you can see that under the right circumstances she can still elicit the kind of "confident lady" look that you were looking for. But it's hard to capture these kinds of emotions in a character's idle pose, when artwork relies so much on being expressive.

<details><summary>Click to expand</summary>

image
image
image
image

</details>

Please let me know if this clarifies the design choices I made, or if you feel like they should still be changed. And if so, let me know more specifically which parts of them you feel should be altered.

**Review by Remerod — APPROVED** [review]
You make a good point, and i agree with you. so I'll go ahead and give my expectationist testing approval ;)

**Review by zumbak04 — APPROVED** [review]
LGTM! Good job!

**Pull request merged**
