### PR TITLE
CoA Fixes

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Fixed issues where Loa, Geo, and Chi religious followers weren't using their unique CoAs.

# How to test:
Enter the game, check which CoAs have trolls, centaurs, and pandaren, tell your opinion.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
So from how I interpreted the changelog. Pandaren, Centaurs, and Trolls would have their CoA not be a generic one. 

- For Pandaren, I still see some generic CoA and most of them are still out of place. Like having generic multi color, European, Indian, and Pagan CoA all mixed at once:
<details>

image

</details>

- I think we should not group all Pandaria as one CoA umbrella. It introduces some inappropriate CoA for some:
<details>

image
image
</details>

- Pedantic but, I don't think trolls should have star shaped CoA:
<details>

image

</details>

**Comment by zumbak04** [comment]
> * For Pandaren, I still see some generic CoA and most of them are still out of place. Like having generic multi color, European, Indian, and Pagan CoA all mixed at once:

Don't see them. Maybe it was side-fixed in 860a3bc45f1d15592a4437c3248273620d216a4e.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by zumbak04** [comment]
> * I think we should not group all Pandaria as one CoA umbrella. It introduces some inappropriate CoA for some:

Changed in 860a3bc45f1d15592a4437c3248273620d216a4e.

> * Pedantic but, I don't think trolls should have star shaped CoA:

Changed in 1b9f067ce158100b0b285654aeb4d315afc77929.

**Review by TheGroxEmpire — COMMENTED** [review]
- Is it possible to restrict animal CoA? Ox, Goat, Bull, and Camel are not usual / cultural for to be a CoA on Warcraft Setting. There's also some inappropriate symbols on Trolls CoA:
<details>

image
image
image
image
</details>
- Pandaren are also still getting European CoA. Most of them imo doesn't fit for Pandaren. There's also a Star of David here for some reason:
<details>

image
image
</details>

**Comment by zumbak04** [comment]
> * Pandaren are also still getting European CoA. Most of them imo doesn't fit for Pandaren. There's also a Star of David here for some reason:

This is so strange. Now I see wrong CoAs too though the last time everything was fine.

**Comment by zumbak04** [comment]
> * Pandaren are also still getting European CoA. Most of them imo doesn't fit for Pandaren. There's also a Star of David here for some reason:

Should be fixed in f7209dfe0dcc9b45b9cf136eda0af0910060f364.

**Review by TheGroxEmpire — COMMENTED** [review]
- The trolls are all good now.
- Pandaren CoA are mostly fixed except for few of these animals (Elephants and cow) and one European CoA:
<details>

image
image
image
<details>

**Comment by zumbak04** [comment]
> * Pandaren CoA are mostly fixed except for few of these animals (Elephants and cow) and one European CoA:

I kept the cow or bull because it reminds me Niuzao.
And that European CoA is a tiger.
<details>
<summary>Click to expand</summary>

image

</details>

**Review by TheGroxEmpire — APPROVED** [review]
All CoAs are appropriate to me then. Good job!

**Review by TheDrPibb1999 — APPROVED** [review]
All CoAs seem fitting and well designed for their respective religions, didn't see any issues or displacements. A++ great work zumbak!

**Pull request merged**
