### PR TITLE
Glowing Eyes

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Using EK2 shader as a base, made our magical eyes glowing. It affects the Zandalari, Blood and Ice trolls, elves, Dark Iron and Frostborn trolls, draenei, etc.

<details>
<summary>Click to expand</summary>

image

</details>

# Tasks:
- [x] Check for eye errors.

# How to test:
Open the Ruler Designer and check mentioned ethnicities. Tell how it looks.

### CODE REVIEW

**Review by ValianBlue — COMMENTED** [review]
<details>
<summary>Draenei (Before)</summary>


</details>

<details>
<summary>Draenei (After)</summary>


</details>

<details>
<summary>Eredar (Before)</summary>


</details>

<details>
<summary>Eredar (After)</summary>


</details>

<details>
<summary>Blood Troll (Before)</summary>


</details>

<details>
<summary>Blood Troll (After)</summary>


</details>

<details>
<summary>Dark Iron Dwarf (Before)</summary>


</details>

<details>
<summary>Dark Iron Dwarf (After)</summary>


</details>

<details>
<summary>Night Elf (Before)</summary>


</details>

<details>
<summary>Night Elf (After)</summary>


</details>

_Overall the brighter eyes stand out significantly more after the test compared to before. In my personal opinion, Blood Troll eyes are in a perfect condition. For the other races, the pupils seem to stick out oddly. While this works more for some races like High Elves, I would be more for reducing the pupil contrast for races like the Eredar who have a subtle transition from sclera to iris/pupil._

**Comment by zumbak04** [comment]
> _Overall the brighter eyes stand out significantly more after the test compared to before. In my personal opinion, Blood Troll eyes are in a perfect condition. For the other races, the pupils seem to stick out oddly. While this works more for some races like High Elves, I would be more for reducing the pupil contrast for races like the Eredar who have a subtle transition from sclera to iris/pupil._

Eyes with pupils just look better aesthetically and Blizzard understand it. They show elves with pupils in the cinematics. So I wouldn't change it for many races.
<details>
<summary>Click to expand</summary>

image

</details>

I'll try to experiment with the draenei though to give them alien look.

**Comment by zumbak04** [comment]
> Eyes with pupils just look better aesthetically and Blizzard understand it. They show elves with pupils in the cinematics. So I wouldn't change it for many races.

Added in 59e278eabe81b8fbc27c3e26ba61482f0d2cf0dd. But we found the draenei from the BC cinematic, he has pupils so I would stick to the draenei having them too.

<details>
<summary>Click to expand</summary>

image

</details>

Anyway, I added such eyes and they may be used for spooky creatures.

**Review by TheGroxEmpire — COMMENTED** [review]
- Some randomly generated Zandalari Troll have green eyes. From how it is explained on wowpedia, they should only have blue and yellow eyes:
> ...accompanied by glowing eyes in the color of yellow or blue.

- The Night Elves could have silver eye color. Many official depictions of them mostly have this eye color:
<details>

image
image
image

</details>

**Comment by zumbak04** [comment]
> * Some randomly generated Zandalari Troll have green eyes. From how it is explained on wowpedia, they should only have blue and yellow eyes:

They have green eyes in game.
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by ValianBlue** [comment]
Looks good! A few points I want to raise:

**Dark Iron Dwarves** appear to have an orange pupil and iris with red sclera. 

<details>
<summary>Dark Iron Racials</summary>


</details>


<details>
<summary>This one is harder to see</summary>


</details>


<details>
<summary>In-game model</summary>


</details>

**Blood Elves** would look great with those green eyes you gave the eredar.

<details>
<summary>Click to expand</summary>


</details>


**Frost Trolls** are definitely an interesting case. You've got models like Malakk who have more subtle, not glowing eyes.

<details>
<summary>Click to expand</summary>


</details>

<details>
<summary>Click to expand</summary>


</details>

<details>
<summary>Click to expand</summary>


</details>

https://i.imgur.com/mkwEFBw.png

**Comment by zumbak04** [comment]
> * The Night Elves could have silver eye color. Many official depictions of them mostly have this eye color:

Added in bcd1392716b10e8584beb083900a28a34ca20bde.

> _**Dark Iron Dwarves** appear to have an orange pupil and iris with red sclera._

> _**Blood Elves** would look great with those green eyes you gave the eredar._

> _**Night Elves** can also have golden eyes. While these were rare pre-Sundering, they are now a lot more common. Typically a sign of druidic potential. They are also the black eyes for the Night Warrior, although that depends if such a mechanic would be fit for the mod._

**Comment by zumbak04** [comment]
> Hekima with yellow eyes (albeit behind a mask, so it might actually be different?)

Hekima is Zandalari.
https://wowpedia.fandom.com/wiki/Hekima_the_Wise

**Comment by zumbak04** [comment]
> _**Frost Trolls** are definitely an interesting case. You've got models like Malakk who have more subtle, not glowing eyes.

I would stick to red eyes anyway but I made them a bit orange in f8425d2246d4a050f15e7f80c34b00cb84308bff to represent orange iris of Malakk.

**Review by ValianBlue — APPROVED** [review]
> 
> 
> > Hekima with yellow eyes (albeit behind a mask, so it might actually be different?)
> 
> Hekima is Zandalari.
> https://wowpedia.fandom.com/wiki/Hekima_the_Wise

_Ah, I apologize. Thank you for catching this._ 

_I checked things over again and it looks good! I'm especially a fan of the Dark Iron eyes you made._

**Review by Remerod — CHANGES_REQUESTED** [review]
I generally really love this glowing eye change.
 I have a nitpic about the yellow glowing eyes on the Zandalari, I think they are to dark, and should be a little lighter in colour, as shown in the examples bellow. 

<details>
<summary>Click to expand</summary>

Zandalari from Isle of Thunder with bright yellow/golden eye's
image
Ingame seem more "dark" or not as light golden colour
image
Zul in WoW defiantly have really light coloured eyes
image
While in ck3 it certainly look gold golden or like to other example
image

</details>

I dunno if blood trolls though should have such glowy eyes on their non-black eyes
<details>
<summary>Click to expand</summary>

WoW Model of green Blood Troll with blue eyes, it's not glowy at all, in my opinion 
image

Our Ck3 Troll is more glowy i think
image

Same with the dark Skinned one with red eyes, it looks more.. bloody or blood red, but not glowy
image
Our's look more shiny red
image

</details>

Eredar and Draenai looks really good, but perhaps they could be a little brither? or atleast eredar maybe. But i don't feel like they have to change.
<details>
<summary>Click to expand</summary>

WoW Eredar, have a much brighter neon green with greenish-yellow iris
image
While our is more very Bright, with almost a bit of pale-ness Green colour
image

</details>

I really like the Night Elven, Dark Iron Dwarf, Darakkari (although i wouldn't mind them, the Ice Trolls having pupils also, like Malakk instead of just irises)

**Comment by zumbak04** [comment]
> I have a nitpic about the yellow glowing eyes on the Zandalari, I think they are to dark, and should be a little lighter in colour, as shown in the examples bellow.

Done in 2e7e9ca2db79245d33139c93594668f1473c778a.

> I dunno if blood trolls though should have such glowy eyes on their non-black eyes

Done in 2786823a4873bba27fc93e90bae5830f7e3abe34.

> Eredar and Draenai looks really good, but perhaps they could be a little brither? or atleast eredar maybe. But i don't feel like they have to change.

Done in e7d67bf3b0a0852c436e1087eab1f290dc04be53.

**Review by Remerod — APPROVED** [review]
It's all great stuff!

**Review by TheGroxEmpire — APPROVED** [review]
I like the new Night Elf eyes color. Everything looks good to me.

**Pull request merged**
