### PR TITLE
Made Dwarves A Bit Taller

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Made dwarves a bit taller because [MATH](https://docs.google.com/spreadsheets/d/1FdPTeaHegaMOoimYUPWNuMl69vcJ6F-2vBmc1ZuxH3g/edit?usp=sharing).

# How to test:
I'm sure in this PR, but check how the dwarves look just in case.

### CODE REVIEW

**Review by ulricee — APPROVED** [review]
Nothing wrong to report!

**Review by Chipawa12 — COMMENTED** [review]
I think the new heights look good.  Dont see anything weird in my testing of them.

**Review by TheGroxEmpire — COMMENTED** [review]
Their height are fine. But I am noticing that Wildhammer Dwarves now have the same height as other Dwarven Ethnicities. We made them a bit taller on original branch.

**Comment by zumbak04** [comment]
> Their height are fine. But I am noticing that Wildhammer Dwarves now have the same height as other Dwarven Ethnicities. We made them a bit taller on original branch.

Fixed in c7d40c1b56f79375e77f1062524fdb77775b3d30.

**Review by TheGroxEmpire — APPROVED** [review]
> Fixed in c7d40c1.

Yup, can confirm this fix.

**Pull request merged**
