### PR TITLE
Special buildings 3

### PR DESCRIPTION
**Pull request by Gaben1025**
## What's new:
- Added new special buildings (12 new)
  - Atul' Aman (County of Atul'Aman)
  - Caverns of Time (County of Caverns of Time)
  - Corpse of Agamaggan (County of Razorfen)
  - Dire Maul Arena (County of Avalune)
  - Onyxia's Lair (county of Zertixia)
  - Stormwind Harbor (County of Landenking) 
  - Sulfuron Spire (Tribe of Shadra'dar)
  - Temple of Ahn'Qiraj (Barony of Skunn)
  - Temple of Arkkoran (County of Arkkoran)
  - The Necropolis (Temple of Necropolis)
  - Undermine (County of Mount Kajaro)
  - Zuldazar (County of Zulduzar)

## How to help add localization:
- Go to this file 
image
- Add descriptions (the first should be a very general description, and the second description should be very in detail, look at examples here or vanilla files)
image

Based on WIP tab from:https://docs.google.com/spreadsheets/d/18zS-FAte6nsejx7rpzSmVuioRXps3iWSvSkx_xRJSWI/edit#gid=1906407470

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
These special buildings still need flavor text:
- Caverns of Time

Discrepancy between in-game values and sheet values:
- Corpse of Agamaggan: 50% caster mult damage vs 40% in sheet
- Dire Maul Arena: missing counter efficiency in the game
- Temple of Arkkoran has 0 Learning scheme power vs 0.2 in the sheet
- Undermine has pretty different stat in the game than the sheet

Missing special buildings in the listed county:
- Sulfuron Spire
- Temple of Ahn'Qiraj

**Comment by Gaben1025** [comment]
image
sulfuron spire working fine, but its something that needs to be implemented for a later bookmark or created by the event bc by lore it appears at around 611

**Review by TheGroxEmpire — APPROVED** [review]
My issues have been fixed.

**Review by VespertinePetrichor — CHANGES_REQUESTED** [review]
`gfx/interface/icons/building_types/gude-2023-02-07.log` and `gfx/interface/icons/building_types/gude-2023-02-08.log` should be deleted. 

`building_nexus_01_desc` is missing localisation.

Everything else LGTM.

**Review by VespertinePetrichor — APPROVED** [review]
LGTM!

**Pull request merged**
