### PR TITLE
Green Dragon Horns

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added horns for Ysera called Green Dragon.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
Open the Horns in the Ruler Designer.

### CODE REVIEW

**Review by ercarp — CHANGES_REQUESTED** [review]
Overall I think they look pretty good, but I would probably move them a bit lower on the sides. Ysera's horns appear to be a bit more on the sides of her head and not as close together on the top. Making them ever so slightly bigger wouldn't be a bad idea either.

As for the color, I'm not sure if it could be altered to be a bit more like her WoW model (although not quite as extreme, just slightly more bone-colored than it currently is).

<details><summary>Click to expand</summary>

image

</details>

Side view on the horns is good. 👍

<details><summary>Click to expand</summary>

image

</details>

**Review by Remerod — COMMENTED** [review]
Had a Quick look. And I personally agree with @ercarp comment above. I also want to add that i think that the horn should be a little thicker, witch can be seen on the pictures Ercarp posted, that the WoW model is clearly ticcer then ours.

Other wise it looks good in my opinion!

**Comment by zumbak04** [comment]
@ercarp @Remerod done in https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/655/commits/40f97f20f13ab4425ae6f75ddbe2bc82948b0e52.

**Review by ercarp — APPROVED** [review]
The horns look perfect to me now! Very excited to apply these to Ysera's custom DNA in-game.

Great job!

<details><summary>Click to expand</summary>

image

</details>

**Pull request merged**
