### PR TITLE
Blending Dwarves

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added Bronzebeard, Dark Iron, Wildhammer and Frostborn Dwarven ethnicities.
- Dwarves are allowed to marry elves and humans.

# How to test:
Check them in-game and tell your opinion.

## Note:
The Frostborn look based on their HoTs appearance.
<details>
<summary>Click to expand</summary>

image
image

</details>

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Wildhammer dwarves are too similar to Bronzebeard.
> Wildhammer dwarves are taller, leaner, and wilder than their earthier Ironforge cousins. Wildhammers are similar in appearance to Ironforge dwarves, though they have different skin tones in comparison to their cousins. Where the Ironforge dwarves range from tan to pale and ashy, Wildhammers are near exclusively tan, with some having nearly orange-toned skin. (https://wow.gamepedia.com/Wildhammer_dwarf#Appearance_and_equipment)

- Current Dark Iron dwarves looks like Bronzebeard with more melanin (Human skin tones kind of black / brown). They should have a more gray ash-like skin color as shown in their [in-game model](https://www.wowhead.com/dressing-room#bv0z0zM89c8Vy83g8Vn83u8Vx83l8Vt83J8Vg83W8Vv84m8o38348av8MmR87vYb387a) and official drawing:
<details>

image
image
image

</details>

- A lot of male dwarves have receding / bald hairstyle. Suggestion: hairstyle like these could work without the front hairs:
<details>

image
image
</details>
- Some clipping issues:
<details>

image
image
image
image
image
</details>

**Comment by zumbak04** [comment]
> * Wildhammer dwarves are too similar to Bronzebeard.

Changed in e19517c24b77feb75a5dbfee95c8e0a488edab68.

> * Current Dark Iron dwarves looks like Bronzebeard with more melanin (Human skin tones kind of black / brown). They should have a more gray ash-like skin color as shown in their [in-game model](https://www.wowhead.com/dressing-room#bv0z0zM89c8Vy83g8Vn83u8Vx83l8Vt83J8Vg83W8Vv84m8o38348av8MmR87vYb387a) and official drawing:

Changed in 9d1dc785775c7519708c25b21883ababaea9f13c.

> * A lot of male dwarves have receding / bald hairstyle. Suggestion: hairstyle like these could work without the front hairs:

Did better, I added **BALDNESS**  in 020d17486141ac848eb6800ef773cb271aa7c98e.

> * Some clipping issues:

The first two are vanilla, I reported them to Paradox.
The 4th is intended, the back of the head is shaved.
The rest 2 are fixed.

**Review by TheGroxEmpire — COMMENTED** [review]
I'm liking all of the changes, all of the previous issues are resolved 👍 

- The Frostborn dwarves have some funny hair color combination that imo not fitting. a6b1ef9e9dd2cbc6b0381bf63a09c67674a9d292 seems to have not changed it:
<details>

image
image

</details>

**Comment by zumbak04** [comment]
> * The Frostborn dwarves have some funny hair color combination that imo not fitting. [a6b1ef9](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/a6b1ef9e9dd2cbc6b0381bf63a09c67674a9d292) seems to have not changed it:

Changed in 36a8cb5202a8616dbbbc929a9629b560c4d41478.

**Review by TheGroxEmpire — APPROVED** [review]
> Changed in 36a8cb5.

This one fixed the funny hair color. They all look good enough now.

**Comment by PapaWarius** [comment]
Found a couple clipping issues whit the Dwarves hairs:

<details>
<summary>Click to expand</summary>

High Bun Hair
High Bun

The 2 listed bellow occur only when the Head Top Width slider is kinda high
Pulled Back Hair
HW Pulled Back

Roman Fade Hair
HW Roman Fade
</details>

**Review by PapaWarius — APPROVED** [review]

**Comment by zumbak04** [comment]
> Found a couple clipping issues whit the Male Dwarves hairs:

Fixed.

> When the Beautiful trait its added the head stretches into a weird form.

Fixed in 0ab35f92370f51d06da5deeb3cfbd6cbe076c9d3.

> When the Hideous trait is added, the characters eyes get smashed together, it looks like like every 1 out of 3 random characters I tested it out.

I don't think it's a problem. It looks hilarious.

**Review by PapaWarius — APPROVED** [review]

**Pull request merged**
