### PR TITLE
Basic Racial Mechanics

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Spawned and born characters always have a racial trait.
- Blocked interracial marriages and romances though some races can intermarry like humans and elves.

## How to test:
Play the game for a while, look for characters without racial traits.
Try to interracial marriages.

### CODE REVIEW

**Comment by TheGroxEmpire** [comment]
- Some Highborne have Highborne trait, but most have Night Elf trait.
<details> 

image
</details>

- Lowborn Dragons are missing their racial trait.
<details>

image
</details>

- Lowborn Grummles are missing their racial trait.
<details>

image
</details>

- This random guy doesn't have racial trait.
<details>

image
</details>

- Changing culture, racial trait, and religion through console command didn't change who I could marry.
<details>

image
</details>

Other than that interracial marriage restriction seems to be working without using console command to change things.

**Review by TheGroxEmpire — COMMENTED** [review]
- Some Highborne have Highborne trait, but most have Night Elf trait.
<details> 

image
</details>

- Lowborn Dragons are missing their racial trait.
<details>

image
</details>

- Lowborn Grummles are missing their racial trait.
<details>

image
</details>

- This random guy doesn't have racial trait.
<details>

image
</details>

- Changing culture, racial trait, and religion through console command didn't change who I could marry.
<details>

image
</details>

Other than that interracial marriage restriction seems to be working without using console command to change things.

**Comment by zumbak04** [comment]
Thanks for your review!

> * Some Highborne have Highborne trait, but most have Night Elf trait.

> * Lowborn Dragons are missing their racial trait.

> * Lowborn Grummles are missing their racial trait.

Fixed in e0e76eca8090cbb6216fd63c1c0260a7e1428aa6.

> * This random guy doesn't have racial trait.

Should be fixed in b8bfdeb1435999094a4f12d3b9b3bdd7b8914c95.

> * Changing culture, racial trait, and religion through console command didn't change who I could marry.

The console can't change your race trait, there's a hidden variable involved.

**Review by TheGroxEmpire — APPROVED** [review]

**Review by ArchmageTanor — APPROVED** [review]
Races Seem to all have traits from my checking.

**Pull request merged**
