### PR TITLE
Demonic Clothes

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Demons use darker colors for their clothes.

## Tests:
- [x] There are no errors in `wc` files in `Documents\Paradox Interactive\Crusader Kings III\logs\error.log` except `portrait_decals.cpp:101`
- [x] The mod takes less than 5.5 GB in the Task Manager (Windows)

# How to test:
There are 2 ways:
- Check what Kalimdor satyrs wear.
- Check clothes in the Portrait Editor
  - Press the `~`.
  - Open the Portrait Editor
  - Select `manari_ethnicity` as Ethnicity
  - Find `clothes` gene
  - Find `demonic` sub groups at the end
  - Click Randomize DNA to get new variation
  - Open 3D View to see the whole model

<details>
<summary>Click to expand</summary>

image
image

</details>

Give feedback. Do you like colors? Do you want to see some other color variation?

### CODE REVIEW

**Review by ercarp — COMMENTED** [review]
The dark red, dark green, and black clothes all look wonderful and I like them a lot. They definitely make them look more like "the bad guys".

<details><summary>Click to expand</summary>

image
image
image
image
image
image

</details>

Unsure about the dark blue. I like the color and how it looks, but it's not giving me the same kind of demonic vibe as the ones above. Just makes me mostly think of the Alliance.

<details><summary>Click to expand</summary>

image
image

</details>

Not a huge fan of the garish purple either as I think it overlaps with the coloration of Night Elf clothes.

<details><summary>Click to expand</summary>

image
image

</details>

Then again, with a skin color like this, it does look quite nice. But perhaps it would still be better suited for Uncorrupted Eredar (i.e. Draenei) instead of demons.

<details><summary>Click to expand</summary>

image
image

</details>

In regards to the war clothes, I find that the coloring isn't as apparent since it only colors a small part of the overall outfit, but my color preferences would be the same.

✔️ Dark Red
✔️ Dark Green
✔️ Black
⌛ Dark Blue _(unsure, up to you)_
❌ Purple

**Comment by zumbak04** [comment]
> Unsure about the dark blue. I like the color and how it looks, but it's not giving me the same kind of demonic vibe as the ones above. Just makes me mostly think of the Alliance.

I used this gallery to have some idea of what kind of colors the eredar have.
Blue colors taken form here:
https://wowpedia.fandom.com/wiki/Eredar#Gallery
<details>
<summary>Click to expand</summary>

image
image

</details>

> Not a huge fan of the garish purple either as I think it overlaps with the coloration of Night Elf clothes.

Purple from here:
<details>
<summary>Click to expand</summary>

image

</details>

**Comment by ercarp** [comment]
> I used this gallery to have some idea of what kind of colors the eredar have.

I see. Well, in that case, it should be fine to keep these colors if there's precedent for them in WoW.

**Review by Darknight367 — COMMENTED** [review]
The black, dark red, dark green looks good to me. But the blue one I must say I agree with Ercarp, it mostly reminds me of an Alliance character more or less, a clothing that might be worn by Arthas or so...

On the contrary, the purple variant of the clothing looks quite good, as long as the skin is also not purple.

War clothing looks okay, though it clips with their goat legs a bit 👍

**Comment by ercarp** [comment]
Are they supposed to use the same set of clothes for each tier (commoner, low nobility, and high nobility)? I would be okay to approve this on my behalf as soon as I get an answer. I just want to know if it's intended.

Also, it seems I forgot to even look at the other set of clothes included and I have to say it looks excellent on the Man'ari Eredar:

<details><summary>Click to expand</summary>

image
image
image
image

</details>

**Comment by zumbak04** [comment]
> Are they supposed to use the same set of clothes for each tier (commoner, low nobility, and high nobility)? I would be okay to approve this on my behalf as soon as I get an answer. I just want to know if it's intended.

Added in c37d73e3a3fa351c7d003db086e89a916e81e752.

**Comment by zumbak04** [comment]
> The black, dark red, dark green looks good to me. But the blue one I must say I agree with Ercarp, it mostly reminds me of an Alliance character more or less, a clothing that might be worn by Arthas or so...

Silver + dark blue is one of the main color schemes. I used it for reference.
<details>
<summary>Click to expand</summary>

image
image
image

</details>

**Review by Darknight367 — APPROVED** [review]
All's good!

**Review by ercarp — APPROVED** [review]
> Added in [c37d73e](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/commit/c37d73e3a3fa351c7d003db086e89a916e81e752).

Everything looks good to me then. Approved!

**Review by Remerod — COMMENTED** [review]
I think they are okay, I would approve... but i was scrolling in the character search when i was looking and "satyrs" when this female marshal I had on the screen ui whom was wearing "war cloths" on and they started to change/glitch colours. so perhaps something is wrong?

<details>
<summary>Click to expand</summary>

image

image

image

</details>

**Comment by zumbak04** [comment]
> I think they are okay, I would approve... but i was scrolling in the character search when i was looking and "satyrs" when this female marshal I had on the screen ui whom was wearing "war cloths" on and they started to change/glitch colours. so perhaps something is wrong?

Are there steps to reproduce?

**Comment by zumbak04** [comment]
> I think they are okay, I would approve... but i was scrolling in the character search when i was looking and "satyrs" when this female marshal I had on the screen ui whom was wearing "war cloths" on and they started to change/glitch colours. so perhaps something is wrong?

Fixed in f97dbea5fe596c5d7c3aca2c8d595a41a28c2ec5.

**Review by Remerod — APPROVED** [review]
Yeah, the glitch is gone now to my knowledge. To bad you had to change it back though, because it looked good before, but it's better now when the colours don't glitch/bug colours when wearing the war attire/clothes 

<details>
<summary>Click to expand</summary>

image

</details>

**Pull request merged**
