### PR TITLE
Shatter Realm

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- The Horde falls apart if it loses Great Invasion (the cheap CB they use) giving lands to claimants and freeing vassals.
  - Claimants get Rebuilding Kingdom modifier and event troops to help.
- The Great Invasion CB no longer allows white peace.
- If the Horde loses the Great Invasion, the defender and allies get 1000 prestige.
- Added the Shatter Realm CB to attack and stop invaders like the Horde.
- Nerfed the Horde: they get fewer event troops and gold now.
- Only orcs can use Call the Horde decision to create the Horde Union.

## Tasks:
- [x] Disband the Horde faction on losing the war
- [x] Add Shatter Realm CB
- [x] Fix `invasion` errors
[error.log](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/files/6246485/error.log)

# How to test:
Test features and tell your feedback on each one.

The branch works on the CK3 1.2.2 version!

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Losing the war as Horde before Stormwind falls (Either through Great Invasion of Stormwind or Shatter Realm CB) only demotes Horde Warchief to King-tier without them losing any vassals or title:
<details>

image
</details>

- The former Warchief still gets the ``Great Invader`` modifier after losing:
<details>

image
</details>

- After Stormwind fell, losing the war as Horde fractured the realm and giving the title back to the claimant. However as you can see here, Stormwind did not get all of their previously held de-jure title, the rest was owned by random Orcs:
<details>

image
</details>

**Comment by zumbak04** [comment]
> * After Stormwind fell, losing the war as Horde fractured the realm and giving the title back to the claimant. However as you can see here, Stormwind did not get all of their previously held de-jure title, the rest was owned by random Orcs:

Claimants don't get all titles, but titles close to their capital.

> * Losing the war as Horde before Stormwind falls (Either through Great Invasion of Stormwind or Shatter Realm CB) only demotes Horde Warchief to King-tier without them losing any vassals or title:

Fixed in 07ab457f1390c63ef52c436c982bb09efc980403.

> * The former Warchief still gets the `Great Invader` modifier after losing:

Fixed in 07ab457f1390c63ef52c436c982bb09efc980403.

**Review by TheGroxEmpire — APPROVED** [review]
My issues were fixed, LGTM!

**Review by TheDrPibb1999 — APPROVED** [review]
Did a war run on both sides, all LGTM! issues that were previous addressed were fixed for me!

**Pull request merged**
