### PR TITLE
Basic + Capital Development

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Assigned basic development to all the counties.
- Assigned development to all the capitals.

# How to test:
Check the development map in-game and tell your opinion.

### CODE REVIEW

**Review by PapaWarius — APPROVED** [review]

**Review by TheGroxEmpire — COMMENTED** [review]
I have quite a few suggestion to make:
<details>
<summary>All Start Date</summary>

**Eastern Kingdom**
- County of Gilneas could be more developed than its neighbor: 13 -> ~20
- Jin'tha'alor is a pretty functional big troll city that is still being used after Third War: 4 -> ~15 (https://wow.gamepedia.com/Jintha%27Alor)
- Blackrock Spire is an extension of the Blackrock Depths, definitely should be more developed than its surrounding: 12 -> 20

**Kalimdor**
- Timbermaw is an impressive tunnel system / capital connecting Moonglade, Winterspring, and Felwood. It should definitely be the one that receives the development bump instead of Timberpoof: 8 -> 12 (https://wow.gamepedia.com/Timbermaw_Hold)
- Maraudon, a sacred site, home of Princess Theradras could use a bit of bump than zero: 0 -> ~5 (https://wow.gamepedia.com/Maraudon)
- Caverns of time being the lair of Bronze Dragonflight could be bumped also: 3 -> 10
- Some area within Silithus (Hive'Regal, Haasra, Ashakx, Xernannoss, Scarab Wall) have too much development, they are literally deserts just like the area north of them: 12 -> 3
- Most area on Uldum should have a lot less development on it. The halls of origination destroyed most of the things that was there: 10 -> 3 
> Waves of energy erupted from the Forge, bathing the surrounding lands in the powers of uncreation and instantly killing Lei Shen and his entire army; however, it also devastated the surrounding lands, turning Uldum into a barren desert. (https://wow.gamepedia.com/Uldum#History)

**Northrend**
- Ulduar is the biggest titan facility. Unlike most titan facility, it is still functional even if it doesn't serve the original purpose anymore: 10 -> ~30 (https://wow.gamepedia.com/Ulduar)
- Coldarra could use a bit bump on its development. It's the lair of Malygos and has quite a bit interesting structure on it like the Nexus: 4 -> 10 (https://wow.gamepedia.com/Coldarra)
- Wintergrasp has magnificent complexes on it. Could be more than just zero: 0 -> ~15 (https://wow.gamepedia.com/Wintergrasp)
</details>

<details>
<summary>603 Start</summary>

**Eastern Kingdom**
- Major Nerf on every county in Empire of Azeroth De-Jure tiles after being ransacked by the horde: Flat -4 maybe?
</details>
<details>
<summary>605 Start</summary>

**Eastern Kingdom**
- Major Nerf on every county in Empire of Lordaeron De-Jure tiles after being ransacked by the Scourge: Flat -4 maybe?
- Bump Orgrimmar as the Horde built a city on it: 1 -> ~10 (Maybe we could just do it with events in-game progressively)
- Bump every county on Kingdom of Stormwind De-Jure tile as they rebuilt it (Could also be included in events)
</details>

**Comment by zumbak04** [comment]
> I have quite a few suggestion to make:

Implemented everything except...

> Bump every county on Kingdom of Stormwind De-Jure tile as they rebuilt it (Could also be included in events)

Since rebuilding is a long process that couldn't happen in 2 years. Thus regions near Stormwind in 603 have the same development they had in 583 except Westfall and Duskwood suffering a development loss in both 603 and 605.

**Review by Deuce20201 — APPROVED** [review]
It all seems good to me.

**Review by TheGroxEmpire — APPROVED** [review]
> Rebuilding is a long process that couldn't happen in 2 years. Thus regions near Stormwind in 603 have the same development they had in 583 except Westfall and Duskwood suffering a development loss in both 603 and 605.

That makes sense.

My suggestions were implemented correctly. All looks good to me!

**Pull request merged**
