### PR TITLE
Dragons overhaul

### PR DESCRIPTION
**Pull request by ElMariuso**
## Changelog:
**Aspects traits**

- [ ] - _Aspect of Life_: Prowess bonuses, diplomacy, steward and learning bonuses, life and fire magic bonuses (when magic lifestyle is done)

- [ ] - _Aspect of Nature_: Prowess bonuses, diplomacy, steward and learning bonuses, huge life magic bonuses (when magic lifestyle is done)

- [ ] - _Aspect of Earth_: Huge prowess bonuses (Aspect of Earth was made to protect through combat.), martial and intrigues bonuses, earth and fire magic bonuses (when magic lifestyle is done)

- [ ] - _Aspect of Magic_: Prowess bonuses, learning and steward bonuses, huge arcane magic bonuses (when magic lifestyle is done), more health

- [ ] - _Aspect of Time_: Prowess bonuses, learning and steward bonuses, arcane (and another for balancing ?) magic bonuses (when magic lifestyle is done), more health

**Others Aspects traits**

- [ ] - _Aspect of Death (Corrupted Aspect of Earth)_: Huge prowess bonuses (Inherited from Aspect of Earth), martial and intrigues bonuses, fire magic bonuses, huge void magic bonuses (when magic lifestyle is done), more health

- [ ] - _Aspect of Infinite (Corrupted Aspect of Infinite)_: Prowess bonuses , learning and steward bonuses, arcane magic bonuses, huge void magic bonuses (when magic lifestyle is done), more health

**Dragonflight government**

- [ ] - _Troops bonuses and dynastic opinion maluses_: As in CK2's Hive government, in this type of government you should have a bonus of troops per child and a dynastic opinion penalty.

- [ ] - _Dragonflight succession_: The succession of a dragonflight should be done by electing the best dragon in the flight, with choice bonuses for opinion. Some should have title claims. Which would explain why Wrathion would become the self-proclaimed leader of the black flight after the fall of Deathwing.

- [ ] - _Dragonflight succession event_: When the succession is done, there should be an event / decision that brings all the flight together for the ritual of creating a new aspect. As a result, the new leader of the dragonflight would gain the title of aspect.

- [ ] - _Brood special contract_: We should be able to create broods, which are less defended but which bring big bonuses of troops and fertility for the overlord of the brood.

**Draconic faiths**

- [ ] - _Green faith_:  Faith about nature things and protect that. Should have life syncretism. If we put back the emerald dream system, they should have wide access to it. And be subject to the corruption of the void.

- [ ] - _Black faith_: Faith about protect azeroth. Replaced in Blackdragonflight by N'Zoth worship. Except maybe for Ebonhorn ? Can be come back if we put an uncorruption system.

- [ ] - _Red faith_: Faith about life things and protect that. Should have life syncretism.

- [ ] - _Blue faith_: Faith about magic things and protect that. They should be wary of mortals who practice magic.

- [ ] - _Bronze faith_: Faith about time things and protect that. If we put back the emerald dream system, they should have a system like that for going through the corridors of time. And be subject to the corruption of the void.

**Special things**

- [ ] - _Dragonspawn/Drakonide transformation_: Mortals who practice the religions above should be able, at some point, to transform into dragonspawn or drakonid. Like on a pilgrimage to the shrines in Dragonblight. Once this is done, they become loyal to the dragonflight, perhaps automatic vassalization? If they are of imperial title, they simply ally themselves with theft.

- [ ] - _Black dragons corruption_ : Black dragons must worship the Old Gods no matter what. We can do a decorruption system later. For Ebonhorn and Wrathion for example. This is done "biologically" and not through education. Since it is only the eggs that have been decayed that are not under the influence of the Old Gods.

# How to test:
- Open the game
- Check the changes

### CODE REVIEW

**Comment by robmart** [comment]
You could base this on the magic_trees branch if you want to implement magic bonuses right now instead of waiting until it is done.

**Review by Remerod — COMMENTED** [review]
_Green faith: Faith about nature things and protect that. Should have life syncretism. If we put back the emerald dream system, they should have wide access to it. And be subject to the corruption of the void._

Been asked to help come up with some descriptions by you @ElMariuso so here is what i came up with for the green's for now
 
**Green faith**:  (they have been called "brothers and sisters of Dream" so perhaps that could be a viable name for the faith? or perhaps something like "Dragons of the Dream")
_The enchanted, ethereal green dragons live only to serve the forces of nature and uphold the balance between mortal creatures and the ever-evolving world. This they do from within the mystical realm known as the Emerald Dream, a vast, ever-changing spirit world that exists outside the boundaries of the physical world. The Dream thus serve as the verdant realm of the Great Dreaming Dragon Aspect, whom all of the green dragonflight revere, serve and view themself as the Aspects spawn and guardians of nature_

So i tried to describe the lifestyle or religious view of the green dragonflight, since there is no real afterlife view, the closes thing they revere i believe is the aspect itself so tried to write that into it. I'm no 100% happy with it, i guess one could write in more druidism into it, but i wouldn't really say that they are druids rather more beings of nature so i dunno. 
What do you folks think?

**Review by Remerod — COMMENTED** [review]
_Blue faith: Faith about magic things and protect that. They should be wary of mortals who practice magic._

Description for the Blue dragonflight's faith

**Blue Faith:**
_The magical and azure blue dragons seek proof of everything and are focused on the pursuit of ever greater power and knowledge as guardians, catalogers and researcher of Magic and Knowledge, tasked by their revered leader and greatest scientific mind, the Great Dragonic Aspect of Magic. As masters of the arcane, they wield it with a natural, almost intrinsic, ease and are the ones of all the draconic flights that are most drawn to order and calmness. These dragons believe that with this power comes a certain responsibility and so members of the blue flight can often be found in positions policing and monitoring the use of magic by non-dragons._  

I feel like this is good written to understand their faith but perhaps a bit long

**Comment by Remerod** [comment]
Bronze faith: Faith about time things and protect that. If we put back the emerald dream system, they should have a system like that for going through the corridors of time. And be subject to the corruption of the void.
 
 Description of Bronze faith 
 
 **Bronze Faith:**
Unto the Great Aspect of Time and it's dragonflight was the great task charged of keeping the purity of time. Known that there is only one true timeline, though there are those who would have it otherwise. The Bronze Dragons will protect it, throughout all the ages, in the true timeline or not. For without the truth of time as it is meant to unfold, more will be lost than any mortal could possibly imagine. For it's been told to the Bronze dragonflight that the fabric of reality will unravel. It is a heavy task always relying on observation and great planning, but their task must be protected to all costs, for nothing can transpire without time.

Perhaps a bit heavy? what do you think?

**Comment by Remerod** [comment]
Red faith: Faith about life things and protect that. Should have life syncretism

Description of Red faith

**Red faith:**
_The red dragonflight, follows the Great Aspect of Life. They are a noble and honorable group of creatures. They consider themselves the protectors of all life, and are usually found protecting sacred areas and items, seeking to keep them from lesser beings who might be hurt by their dark, corrupted or unnatural energies. The red flight are capable of rejuvenating and draining life like none others, understand the secrets of life, and in turn, those of death, they've been granted great power over both.
The red Dragons concerned itself with maintaining the harmony and prosperity of life, they consider themselves the custodians and defenders of life on Azeroth._

very generic, but their task is simple, protect life from well, unnatural stuff like undeath, void shit etc, i feelt that i might have been repeating a bit, thoughts?

**Comment by Remerod** [comment]
Black faith: Faith about protect azeroth. Replaced in Blackdragonflight by N'Zoth worship. Except maybe for Ebonhorn ? Can be come back if we put an uncorruption system.

Description of Black faith

**Black faith:**
_The Great Dragonic Aspect of the Earth, The Earth-Warder was offered domain of the earth, The soil, the ground and the deep places. The pure black dragons follow the origins and tasks of the Earth-Warder and know that the earth is the basis of all things. It is where all life is rooted. Where all life must come from, and where all is returned to. It is in the earth whence true strength comes, from the deep places within the world, and within oneself. Once long ago the black dragons where known as the defenders of Azeroth, caring for stone and mountain using their formidable abilities to cause the rise and fall of terrain. They were to watch as the world changed and to maintain the boundaries and lines of delineation between the races so that none would fall to war over land and now seek to again uphold that old but not forgotten task._ 

Tried to make it sound as if the religion is rooted in old values that have been rediscovered, as if refounded, should it still sound like that or should it sound like it have always been as it was the same as it was millennia ago?

**Pull request closed without merging**
