### PR TITLE
Draenei Clothing

### PR DESCRIPTION
**Pull request by ercarp**
## Changelog:
- Assigned clothes to the **_Draenei_** ethnicity. Mixture of **Mena**, **Indian**, and **Abbasid** (if the player has the DLC).

**Female clothes**:
```
female_clothes_secular_indian_nobility_01_common/low/high
female_clothes_secular_mena_nobility_02_common/low/high
female_clothes_secular_dde_abbasid_nobility_02_common/low/high # DLC
```

**Male clothes**:
```
male_clothes_secular_dde_abbasid_nobility_03_common/low/high # DLC
male_clothes_secular_mena_nobility_01_common/low/high
male_clothes_secular_mena_nobility_02_common/low/high
male_clothes_secular_indian_nobility_01_common/low/high
```

# How to test:
- **Seven human cultures have been replaced with the draenei_ethnicity for testing purposes.** These cultures are `Alteraci`, `Dalaranian`, `Lordaeronian`, `Hillsbrad`, `Arathorian`, `Gilnean`, and `Azerothian`. View them in-game on this branch to get an idea of what the clothing would look like on draenei.
- Provide feedback on the chosen clothes and whether you think they're appropriate for draenei or not. If not, explain why and what would work better.

### CODE REVIEW

**Review by IronyOwl — APPROVED** [review]
Looks good to me. Didn't see anything I couldn't imagine Draenei wearing.

**Review by Remerod — COMMENTED** [review]
Most of the cloth on the Draenei works for me, i missed some purpleish/pinkish colours, but the besh (white-brown) works well for me. Some of the clothes cliped weird but i think are ok to, others felt weird compared to the others. took some pics. And Jesus robes might be a bit to lore-breaking for me xD
<details>
<summary>Click to expand</summary>

Most Looks good
image
image
image


Others perhaps clip weird? 
image
image

Looks a bit weird, i don't quite get the draenei feels on these, they just feel like they takes eastern kingdom cloths, the others are a lot better/thematic
image
image

Lol, our lord and savior Valen the crucified Shirt
image
 
</details>

**Comment by zumbak04** [comment]
> Others perhaps clip weird?

They will be some clipping with bushy clothes and animations just like large beards clip.

**Comment by zumbak04** [comment]
> Looks a bit weird, i don't quite get the draenei feels on these, they just feel like they takes eastern kingdom cloths, the others are a lot better/thematic

I can agree.

**Comment by ercarp** [comment]
> Looks a bit weird, i don't quite get the draenei feels on these, they just feel like they takes eastern kingdom cloths, the others are a lot better/thematic

I agree, I had just added it in for more variety. Removed in 6c7965fa6079840465dce54d72af83c2fb0d1bde.

**Review by Remerod — APPROVED** [review]
Been checking around again now, and i can't find any that sticks out now. I think it probably looks the best it can be now with Vanilla Cloths. Good Job ;)
<details>
<summary>Click to expand</summary>

image
</details>

**Review by zumbak04 — APPROVED** [review]
LGTM! Good job!

**Pull request merged**
