### PR TITLE
Union Renaming and Description

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- The leader can rename the Union by hitting the Rename button next to its name.

<details>
<summary>Click to expand</summary>

image

</details>

- The Union tab provides a small description of the union.

<details>
<summary>Click to expand</summary>

image

</details>

# Tasks:
- [x] Clear variables after closing the Union
- [x] Clear leftovers of the old button
- [x] Union description, status

# How to test:
Test the renaming and tell if the description works and looks good.

[Filter](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/229/files?file-filters%5B%5D=.yml) to hide non-localization files for @Warcraft-GoA-Development-Team/english-proofreaders.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- We need to limit the number of character to be no more than 12 characters:
<details>

image
image
image

</details>

- The name always reverts back to default (Horde or Alliance) if you click on the rename button after renaming it.
<details>

Before clicking rename:
image

After clicking rename:
image
</details>

- Switching character mid-game after doing rename causes this one text to revert back to their default name:
<details>

image
</details>

- The locs look good to me.

**Comment by zumbak04** [comment]
> * We need to limit the number of character to be no more than 12 characters:

Not sure if it's possible to do. The renaming is very hardcoded.

> * The name always reverts back to default (Horde or Alliance) if you click on the rename button after renaming it.

Should be this way to make default options (Horde, Alliance) work right.

> * Switching character mid-game after doing rename causes this one text to revert back to their default name:

Should be fixed in a85862254c225fa0948105e5d0a3d83c2164053e.

**Review by Deuce20201 — APPROVED** [review]
Looks good to me. 

Changing name works.

Union description is good and I can see no spelling errors.

**Review by TheGroxEmpire — APPROVED** [review]
The rest look good to me then.

**Review by arithon — APPROVED** [review]
loc LGTM (except for the not changeable parts)

**Pull request merged**
