### PR TITLE
One Blind Eye

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- If you have the One-Eyed trait, your left eye is gray blind and you have a scar.
- Only humans wear eye patches if they are one-eyed.

# How to test:
- `add_trait one_eyed` in the console to add the trait.
Check how the One-Eyed affects characters of different cultures.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Elves and Dwarves wear eye-fold and it clipped through their brow:
<details>

image
image

</details>

**Comment by TheGroxEmpire** [comment]
- Missed gnomes, they clipped on the cheek this time:

<details>

image

</details>

**Comment by zumbak04** [comment]
> * Elves and Dwarves wear eye-fold and it clipped through their brow:

Fixed in dc289d0419a4f1e3bed516ff292d54c2f8d53a6f.

> * Missed gnomes, they clipped on the cheek this time:

I would let Paradox fix it since they made the eye patch static.

**Comment by TheDrPibb1999** [comment]
_Only humans wear eye patches if they are one-eyed._ 

I couldn't get the eye patch on any human, but other than that the blind eye was fine on every culture and other than the eyebrow clip that you addressed i don't see any issues
Capture

**Review by TheGroxEmpire — APPROVED** [review]
Confirming the fixes.

**Comment by TheDrPibb1999** [comment]
> _Only humans wear eye patches if they are one-eyed._
> 
> I couldn't get the eye patch on any human, but other than that the blind eye was fine on every culture and other than the eyebrow clip that you addressed i don't see any issues

should have made this clearer, it doesn't add the eye patch in the character creator only, humans do get the eye patch if they get it in game

**Comment by zumbak04** [comment]
> I couldn't get the eye patch on any human, but other than that the blind eye was fine on every culture and other than the eyebrow clip that you addressed i don't see any issues
> Capture

Not affect the Ruler Designer because the culture is undecided.

**Review by TheDrPibb1999 — APPROVED** [review]
Looks good to me :)

**Pull request merged**
