### PR TITLE
Naaru Religion

### PR DESCRIPTION
**Pull request by zumbak04**
## Developer changelog:
- Added a separate religion for the naaru. Thus the Holy Light and naaru faiths are no longer in the same religion.

# How to test:
Check the new religion in-game and tell your opinion.

### CODE REVIEW

**Review by TheGroxEmpire — COMMENTED** [review]
- Armed Pilgrimage (Lightbound) and Adaptive (Velenism) is not allowed for new heresy tenets
<details>

image
image
</details>

- Naaric faith considers Light faith to be hostile, should at least be astray imo

**Comment by zumbak04** [comment]
> * Armed Pilgrimage (Lightbound) and Adaptive (Velenism) is not allowed for new heresy tenets

Fixed in 4fc8ebf4bff8698cf452e08a470bd249ca4eb272.

> * Naaric faith considers Light faith to be hostile, should at least be astray imo

Changed in 28d5b8d4541e36454f7400c8c8a05c9e8698b5ed.

**Review by TheGroxEmpire — COMMENTED** [review]
- Naarist considers Suntouched as Astray and vice versa. Suntouched should consider non-titanic faith as evil as described in the tooltip itself.
<details>

image
</details>

**Comment by zumbak04** [comment]
> * Naarist considers Suntouched as Astray and vice versa. Suntouched should consider non-titanic faith as evil as described in the tooltip itself.

Changed it in c6dd283c9cb60b8a9935bed909ca0c3332c67205. It's `religious-doctrines` branch since it's the main branch for doctrines.

**Review by TheGroxEmpire — APPROVED** [review]

**Review by MemeWizard — APPROVED** [review]

**Pull request merged**
