### PR TITLE
Custom Unions

### PR DESCRIPTION
**Pull request by zumbak04**
## Changelog:
- Added an option for the players to **_Found a New Union_** in the decisions. There can be only one custom union. The option should be around year 603. Rulers of the same cultural group and religion prefer to join such unions.
- Added the Features tooltip to the Unions tab explaining some union features.
<details>
<summary>Click to expand</summary>

image

</details>

# Tasks:
- [x] Test every feature again
- [x] Look for horde, alliance, union errors
- [x] Add the event where you enter a custom union name
- [x] Add custom union description
- [x] Add custom union features
- [x] Change decision pictures

# How to test:
Create a custom union and check for basic functions like joining, leaving, renaming, inviting.

[Filter](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/pull/233/files?file-filters%5B%5D=.yml) to hide non-localization files for @Warcraft-GoA-Development-Team/english-proofreaders.

### CODE REVIEW

**Comment by ercarp** [comment]
I don't know if this is intended but if you're playing as the **_Union Heir_**, the **_Leave the Alliance_** Decision does not show up under Major Decisions, and therefore you can't create a Custom Union either.

<details><summary>Click to expand</summary>

image

image


image

</details>

**Review by ercarp — COMMENTED** [review]
I made some small localization tweaks but other than that everything looks good to me. If there's anything I would change, I would probably get rid of the cooldown for creating a Custom Union after leaving your current one.

**Comment by zumbak04** [comment]
> If there's anything I would change, I would probably get rid of the cooldown for creating a Custom Union after leaving your current one.

Done in bc8b5cbbce7bea27e938f5b8900b4a6459b05183.

**Review by ercarp — APPROVED** [review]
LGTM!

**Review by TheGroxEmpire — COMMENTED** [review]
- bc8b5cb I think caused leaving Alliance or Horde to not incurs union CD. Meanwhile, leaving custom union incurs union CD so it's a bit inconsistent right now. Imo it should be the other way, creating union doesn't require you to fulfill the CD
<details>

image

</details>

- The Scourge, Mantid, Qiraji, and other ruler with evil religion could not create a custom union:
<details>

image
</details>

- Union related events pop up caused GUI bugs, resetting the windows however fix it. I think we should close this window whenever Union events pop up.
<details>

image
</details>

**Comment by zumbak04** [comment]
> I think caused leaving Alliance or Horde to not incurs union CD. Meanwhile, leaving custom union incurs union CD so it's a bit inconsistent right now. Imo it should be the other way, creating union doesn't require you to fulfill the CD

I left the custom union, no cooldown. Creating the union should give a cooldown to prevent the custom union spam by players.
<details>
<summary>Click to expand</summary>

image
image

</details>

> * The Scourge, Mantid, Qiraji, and other ruler with evil religion could not create a custom union:

They can't. I added it to the Features in 9a8d7fd798dc3a0adf71791c14c0a515e9110884.

> * Union related events pop up caused GUI bugs, resetting the windows however fix it. I think we should close this window whenever Union events pop up.

Should be fixed in 21661415f7829e8f31b87e2a6d7207ccac4f7c9a.

**Review by TheDrPibb1999 — APPROVED** [review]
All changed LGTM, cooldowns, the "Union related events pop up caused GUI bugs, resetting the windows however fix it. I think we should close this window whenever Union events pop up." was fixed for me with the fix. good work :)

**Review by TheGroxEmpire — COMMENTED** [review]
The GUI bugs still happens after I closed the custom union event popup.
<details>

image
</details>

**Comment by zumbak04** [comment]
> The GUI bugs still happens after I closed the custom union event popup.

What popup? Couldn't reproduce it.

**Review by TheGroxEmpire — COMMENTED** [review]
> What popup? Couldn't reproduce it.

Here's how to reproduce it:
1. Go to decision tab and click on the create custom union.
2. Open up the union tab.
3. Name your custom union then finalize it.
4. An event about your custom union should popup.
5. Dismiss the event.
6. The union tab will appear blank. Resetting the tab will fix it.

**Comment by zumbak04** [comment]
> 1. Go to decision tab and click on the create custom union.
> 2. Open up the union tab.
> 3. Name your custom union then finalize it.
> 4. An event about your custom union should popup.
> 5. Dismiss the event.
> 6. The union tab will appear blank. Resetting the tab will fix it.

That's what I did. No bug.
<details>
<summary>Click to expand</summary>

image
image
image
image

</details>

**Comment by TheDrPibb1999** [comment]
Im on 1.2.2 and wasnt able to reproduce it either with your exact instructions.
Capture

**Review by TheGroxEmpire — APPROVED** [review]
Looks like it was fixed, I think I didn't pull the latest origin. All good then!

**Review by arithon — APPROVED** [review]
loc LGTM

**Comment by robmart** [comment]
@zumbak04 should this not close #216 ?

**Comment by zumbak04** [comment]
> @zumbak04 should this not close #216 ?

That's right, closing.

**Pull request merged**
