### PR TITLE
Adding stormheim culture and rename vrykuls

### PR DESCRIPTION
**Pull request by ElMariuso**
## Changelog:
- Adding Stormheim Vrykul culture named "Stormheimir" for future mapping.
- Changed "Vrykul" culture name in "Fjorthir". (Norsiced Fjord + ir)
- Changed "Frost Vrykul" culture name in "Iskronir". (Ice/Is + Crown/Krona + ir)

# How to test:
Open the game and read the names. To see if the names are correct. Otherwise, put your suggestion.

### CODE REVIEW

**Comment by TheDrPibb1999** [comment]
Personally, within the lore of the game, I don't think they ever refer to the Vrykul/Ice Vrykul by their Norse counterpart, I know the names of the Vrykul within the game are in an old Norse, particularly Icelandic language. I don't think its fitting for it to be changed, in my opinion

**Comment by TheDrPibb1999** [comment]
Just those cultural terms are not brought up once in the game nor by any spoken character. It can confuse players who arent too familiar with the language 

https://wow.gamepedia.com/Vrykul

**Comment by ercarp** [comment]
> 
> 
> **Just those cultural terms are not brought up once in the game nor by any spoken character**. It can confuse players who arent too familiar with the language
> 
> https://wow.gamepedia.com/Vrykul

Many names of cultures and especially names and religions in the mod are completely made-up. Blizzard has chosen not to expand on these areas of the lore so we have to do it ourselves sometimes.

I think both Fjorthir and Iskronir sound quite cool and @ElMariuso clearly took care staying faithful to the root inspiration of Vrykul when he came up with them. That said, I'm not opposed to changing them back to Vrykul and Frost Vrykul if others don't like them as much.

I think it will be easier to tell the difference between Fjorthir and Iskronir once the Vrykul portraits are active. They look very different from each other so it should be easy to tell what's what.

**Comment by TheDrPibb1999** [comment]
I agree, they are quite unique and awesome names for the culture, that was my only concern - Approved by my standard, great work @ElMariuso!

**Review by zumbak04 — APPROVED** [review]
LGTM!

**Review by TheDrPibb1999 — COMMENTED** [review]
Approved, good concept - with the new models with tie together nicely

**Pull request merged**
